'use strict';
/**
 * جدول‌های پایه: تنظیمات، کاربران، سطوح دسترسی، نشست‌ها، لاگ‌ها، سازمان
 * و فرآیند جذب و استخدام.
 */

const T = [
  /* ================================ هسته ================================ */
  {
    name: 'settings',
    label: 'تنظیمات',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['skey', 'str:120', ['nn', 'u']],
      ['value', 'longtext', ['nn']],
      ['group_name', 'str:60'],
      ['title', 'str:200'],
      ['updated_by', 'int'],
      ['updated_at', 'dt'],
    ],
    indexes: [['group_name']],
  },
  {
    name: 'users',
    label: 'کاربران',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['username', 'str:60', ['nn', 'u']],
      ['password_hash', 'str:255'],
      ['full_name', 'str:150', ['nn']],
      ['email', 'str:150'],
      ['mobile', 'str:20'],
      ['national_id', 'str:20'],
      ['avatar', 'str:255'],
      ['role_id', 'int'],
      ['employee_id', 'int'],
      ['is_superadmin', 'bool'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['theme', 'str:10', ['def:light']],
      ['must_change_password', 'bool'],
      ['password_changed_at', 'dt'],
      ['last_login_at', 'dt'],
      ['last_login_ip', 'str:45'],
      ['failed_attempts', 'int', ['def:0']],
      ['locked_until', 'dt'],
      ['remember_token', 'str:100'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['role_id'], ['employee_id'], ['mobile'], ['status']],
  },
  {
    name: 'roles',
    label: 'نقش‌ها',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['rkey', 'str:60', ['nn', 'u']],
      ['name', 'str:120', ['nn']],
      ['description', 'text'],
      ['scope', 'str:30', ['nn', 'def:employee']],
      ['is_system', 'bool', ['def:1']],
      ['is_locked', 'bool'],
      ['sort_order', 'int'],
      ['dashboard', 'str:60'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['created_at', 'dt'],
      ['updated_at', 'dt'],
    ],
  },
  {
    name: 'permissions',
    label: 'مجوزها',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['pkey', 'str:150', ['nn', 'u']],
      ['module', 'str:60', ['nn']],
      ['action', 'str:60'],
      ['name', 'str:200'],
      ['group_name', 'str:80'],
      ['sort_order', 'int'],
      ['created_at', 'dt'],
    ],
    indexes: [['module']],
  },
  {
    name: 'role_permissions',
    label: 'مجوزهای نقش‌ها',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['role_id', 'int', ['nn']],
      ['permission_id', 'int', ['nn']],
      ['created_at', 'dt'],
    ],
    indexes: [['role_id'], ['permission_id']],
  },
  {
    name: 'user_permissions',
    label: 'مجوزهای اختصاصی کاربر',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['user_id', 'int', ['nn']],
      ['pkey', 'str:150', ['nn']],
      ['allow', 'bool', ['def:1']],
      ['created_by', 'int'],
      ['created_at', 'dt'],
    ],
    indexes: [['user_id']],
  },
  {
    name: 'sessions',
    label: 'نشست‌ها',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['sid', 'str:120', ['nn', 'u']],
      ['user_id', 'int', ['nn']],
      ['csrf', 'str:80'],
      ['ip', 'str:45'],
      ['user_agent', 'str:255'],
      ['expires_at', 'dt', ['nn']],
      ['revoked_at', 'dt'],
      ['last_seen_at', 'dt'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['user_id'], ['expires_at']],
  },
  {
    name: 'login_logs',
    label: 'گزارش ورود',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['user_id', 'int'],
      ['username', 'str:120'],
      ['ok', 'bool', ['def:1']],
      ['reason', 'str:120'],
      ['ip', 'str:45'],
      ['user_agent', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['user_id'], ['created_at']],
  },
  {
    name: 'otp_codes',
    label: 'کدهای یک‌بارمصرف',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['mobile', 'str:20', ['nn']],
      ['code_hash', 'str:191', ['nn']],
      ['purpose', 'str:30', ['nn', 'def:login']],
      ['ref_type', 'str:40'],
      ['ref_id', 'int'],
      ['attempts', 'int', ['def:0']],
      ['max_attempts', 'int', ['def:5']],
      ['expires_at', 'dt', ['nn']],
      ['consumed_at', 'dt'],
      ['ip', 'str:45'],
      ['send_status', 'str:20'],
      ['provider_ref', 'str:120'],
      ['provider_response', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['mobile'], ['expires_at'], ['purpose']],
  },
  {
    name: 'audit_logs',
    label: 'لاگ عملیات',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['user_id', 'int'],
      ['user_name', 'str:150'],
      ['action', 'str:40'],
      ['module', 'str:60'],
      ['entity', 'str:80'],
      ['entity_id', 'int'],
      ['title', 'str:255'],
      ['changes', 'json'],
      ['meta', 'json'],
      ['ip', 'str:45'],
      ['user_agent', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['user_id'], ['module'], ['entity'], ['created_at']],
  },
  {
    name: 'notifications',
    label: 'اطلاع‌رسانی‌ها',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['user_id', 'int', ['nn']],
      ['title', 'str:200', ['nn']],
      ['body', 'text'],
      ['level', 'str:20', ['def:info']],
      ['link', 'str:255'],
      ['ref_type', 'str:60'],
      ['ref_id', 'int'],
      ['read_at', 'dt'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['user_id'], ['read_at']],
  },
  {
    name: 'modules',
    label: 'ماژول‌ها',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['mkey', 'str:60', ['nn', 'u']],
      ['name', 'str:150', ['nn']],
      ['description', 'text'],
      ['category', 'str:80'],
      ['menu_group', 'str:80'],
      ['icon', 'str:60'],
      ['version', 'str:20'],
      ['is_enabled', 'bool', ['def:1']],
      ['is_core', 'bool'],
      ['is_licensed', 'bool', ['def:1']],
      ['dependencies', 'json'],
      ['permissions', 'json'],
      ['settings', 'json'],
      ['sort_order', 'int'],
      ['enabled_at', 'dt'],
      ['installed_at', 'dt'],
      ['updated_at', 'dt'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['category'], ['is_enabled']],
  },
  {
    name: 'module_events',
    label: 'رویدادهای ماژول',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['mkey', 'str:60', ['nn']],
      ['action', 'str:30', ['nn']],
      ['user_id', 'int'],
      ['detail', 'text'],
      ['ip', 'str:45'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['mkey'], ['created_at']],
  },
  {
    name: 'schema_migrations',
    label: 'نسخه‌های پایگاه‌داده',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['version', 'str:20', ['nn']],
      ['name', 'str:120'],
      ['applied_at', 'dt'],
    ],
  },

  /* ============================ ساختار سازمانی ============================ */
  {
    name: 'departments',
    label: 'واحدهای سازمانی',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['name', 'str:150', ['nn']],
      ['code', 'str:40'],
      ['parent_id', 'int'],
      ['manager_user_id', 'int'],
      ['location_id', 'int'],
      ['cost_center', 'str:60'],
      ['description', 'text'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['sort_order', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['parent_id'], ['manager_user_id']],
  },
  {
    name: 'job_titles',
    label: 'عناوین شغلی',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['title', 'str:150', ['nn']],
      ['code', 'str:40'],
      ['department_id', 'int'],
      ['grade', 'str:40'],
      ['min_salary', 'money'],
      ['max_salary', 'money'],
      ['duties', 'text'],
      ['requirements', 'text'],
      ['description', 'text'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['department_id']],
  },
  {
    name: 'job_positions',
    label: 'پست‌های سازمانی',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['title', 'str:150', ['nn']],
      ['code', 'str:40'],
      ['department_id', 'int'],
      ['job_title_id', 'int'],
      ['location_id', 'int'],
      ['reports_to_user_id', 'int'],
      ['headcount', 'int', ['def:1']],
      ['occupied', 'int', ['def:0']],
      ['description', 'text'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['department_id'], ['job_title_id']],
  },
  {
    name: 'locations',
    label: 'محل‌های کار',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['name', 'str:150', ['nn']],
      ['type', 'str:40'],
      ['city', 'str:80'],
      ['address', 'text'],
      ['phone', 'str:30'],
      ['lat', 'float'],
      ['lng', 'float'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },
  {
    name: 'work_shifts',
    label: 'شیفت‌های کاری',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['name', 'str:100', ['nn']],
      ['start_time', 'time'],
      ['end_time', 'time'],
      ['break_minutes', 'int'],
      ['weekly_hours', 'int'],
      ['flexible', 'bool'],
      ['days_of_week', 'json'],
      ['description', 'text'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },

  /* ================================ کارکنان ================================ */
  {
    name: 'employees',
    label: 'کارکنان',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['user_id', 'int'],
      ['personnel_code', 'str:40', ['u']],
      ['full_name', 'str:160'],
      ['first_name', 'str:80', ['nn']],
      ['last_name', 'str:80', ['nn']],
      ['father_name', 'str:80'],
      ['national_id', 'str:20', ['u']],
      ['id_number', 'str:30'],
      ['birth_date', 'date'],
      ['birth_place', 'str:80'],
      ['gender', 'str:10'],
      ['marital_status', 'str:20'],
      ['military_status', 'str:30'],
      ['religion', 'str:30'],
      ['mazhab', 'str:30'],
      ['mobile', 'str:20'],
      ['phone', 'str:30'],
      ['email', 'str:150'],
      ['address', 'text'],
      ['postal_code', 'str:15'],
      ['emergency_name', 'str:120'],
      ['emergency_relative', 'str:40'],
      ['emergency_phone', 'str:20'],
      ['photo', 'str:255'],
      ['education_level', 'str:60'],
      ['field_of_study', 'str:120'],
      ['hire_date', 'date'],
      ['employment_type', 'str:40'],
      ['probation_end_date', 'date'],
      ['department_id', 'int'],
      ['job_title_id', 'int'],
      ['position_id', 'int'],
      ['location_id', 'int'],
      ['manager_user_id', 'int'],
      ['work_shift_id', 'int'],
      ['status', 'str:20', ['nn', 'def:active']],
      ['termination_date', 'date'],
      ['termination_reason', 'text'],
      ['base_salary', 'money'],
      ['bank_name', 'str:80'],
      ['bank_account', 'str:40'],
      ['iban', 'str:40'],
      ['insurance_no', 'str:30'],
      ['insurance_days', 'int', ['def:30']],
      ['insurance_status', 'str:30'],
      ['leave_balance_note', 'text'],
      ['notes', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['user_id'], ['department_id'], ['job_title_id'], ['status'], ['mobile'], ['national_id']],
  },
  {
    name: 'employee_documents',
    label: 'مدارک پرسنلی',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['title', 'str:150', ['nn']],
      ['type', 'str:60'],
      ['number', 'str:60'],
      ['issuer', 'str:120'],
      ['issued_at', 'date'],
      ['expires_at', 'date'],
      ['status', 'str:30'],
      ['file', 'str:255'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['employee_id'], ['expires_at']],
  },
  {
    name: 'employee_contacts',
    label: 'بستگان کارکنان',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['name', 'str:150', ['nn']],
      ['relation', 'str:40'],
      ['national_id', 'str:20'],
      ['birth_date', 'date'],
      ['mobile', 'str:20'],
      ['insurance_code', 'str:40'],
      ['is_dependent', 'bool'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['deleted_at', 'dt'],
    ],
    indexes: [['employee_id']],
  },
  {
    name: 'employee_history',
    label: 'تاریخچه پرسنلی',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['event_type', 'str:60', ['nn']],
      ['title', 'str:200', ['nn']],
      ['description', 'text'],
      ['from_value', 'str:150'],
      ['to_value', 'str:150'],
      ['amount', 'money'],
      ['effective_date', 'date'],
      ['file', 'str:255'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id'], ['event_type']],
  },
  {
    name: 'employee_notes',
    label: 'یادداشت‌ها و تذکرها',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['type', 'str:40'],
      ['title', 'str:200', ['nn']],
      ['content', 'text'],
      ['severity', 'str:30'],
      ['visibility', 'str:30', ['def:hr']],
      ['occurred_on', 'date'],
      ['file', 'str:255'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['deleted_at', 'dt'],
    ],
    indexes: [['employee_id'], ['type']],
  },
  {
    name: 'contracts',
    label: 'قراردادها',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['code', 'str:60'],
      ['type', 'str:60', ['nn']],
      ['number', 'str:60'],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['signed_at', 'date'],
      ['base_salary', 'money'],
      ['working_hours', 'int'],
      ['job_title_id', 'int'],
      ['department_id', 'int'],
      ['location_id', 'int'],
      ['status', 'str:30', ['nn', 'def:draft']],
      ['file', 'str:255'],
      ['terms', 'text'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status'], ['end_date']],
  },
  {
    name: 'employee_shifts',
    label: 'شیفت کارکنان',
    module: 'employees',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['shift_id', 'int', ['nn']],
      ['from_date', 'date'],
      ['to_date', 'date'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id'], ['shift_id']],
  },

  /* ============================ جذب و استخدام ============================ */
  {
    name: 'recruitment_stages',
    label: 'مراحل جذب',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['name', 'str:120', ['nn']],
      ['key', 'str:60', ['nn']],
      ['color', 'str:20'],
      ['is_final', 'bool'],
      ['sort_order', 'int'],
      ['is_active', 'bool', ['def:1']],
      ['created_at', 'dt', ['nn']],
    ],
  },
  {
    name: 'job_reqs',
    label: 'فرصت‌های شغلی',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['code', 'str:40', ['u']],
      ['slug', 'str:120', ['u']],
      ['title', 'str:150', ['nn']],
      ['department_id', 'int'],
      ['job_title_id', 'int'],
      ['position_id', 'int'],
      ['location_id', 'int'],
      ['employment_type', 'str:40'],
      ['openings', 'int', ['def:1']],
      ['salary_from', 'money'],
      ['salary_to', 'money'],
      ['description', 'text'],
      ['requirements', 'text'],
      ['benefits', 'text'],
      ['status', 'str:30', ['nn', 'def:draft']],
      ['is_public', 'bool', ['def:1']],
      ['require_mbti', 'bool', ['def:1']],
      ['require_interview', 'bool', ['def:1']],
      ['form_template_id', 'int'],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['applicants_count', 'int', ['def:0']],
      ['hired_count', 'int', ['def:0']],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['status'], ['department_id'], ['is_public']],
  },
  {
    name: 'form_templates',
    label: 'قالب‌های فرم',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['tkey', 'str:60', ['nn', 'u']],
      ['name', 'str:200', ['nn']],
      ['description', 'text'],
      ['scope', 'str:40', ['def:recruitment']],
      ['version', 'int', ['def:1']],
      ['is_active', 'bool', ['def:1']],
      ['is_default', 'bool'],
      ['is_locked', 'bool'],
      ['allow_save_draft', 'bool', ['def:1']],
      ['show_progress', 'bool', ['def:1']],
      ['auto_save', 'bool', ['def:1']],
      ['intro_text', 'text'],
      ['thanks_text', 'text'],
      ['thank_you_text', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },
  {
    name: 'form_sections',
    label: 'بخش‌های فرم',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['template_id', 'int', ['nn']],
      ['title', 'str:200', ['nn']],
      ['description', 'text'],
      ['icon', 'str:60'],
      ['sort_order', 'int'],
      ['is_active', 'bool', ['def:1']],
      ['is_repeatable', 'bool'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['template_id']],
  },
  {
    name: 'form_fields',
    label: 'فیلدهای فرم',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['template_id', 'int', ['nn']],
      ['section_id', 'int'],
      ['fkey', 'str:80', ['nn']],
      ['label', 'str:200', ['nn']],
      ['help_text', 'text'],
      ['placeholder', 'str:200'],
      ['type', 'str:30', ['nn', 'def:text']],
      ['options', 'json'],
      ['validation', 'json'],
      ['default_value', 'str:255'],
      ['is_required', 'bool'],
      ['is_enabled', 'bool', ['def:1']],
      ['is_system', 'bool'],
      ['visible_roles', 'str:120'],
      ['depends_on', 'str:80'],
      ['depends_value', 'str:120'],
      ['width', 'str:20', ['def:full']],
      ['sort_order', 'int'],
      ['min_length', 'int'],
      ['max_length', 'int'],
      ['unit', 'str:30'],
      ['note_hr', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['template_id'], ['section_id'], ['fkey']],
  },
  {
    name: 'applications',
    label: 'پرونده‌های استخدام',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['code', 'str:40', ['u']],
      ['job_req_id', 'int'],
      ['full_name', 'str:160'],
      ['first_name', 'str:80', ['nn']],
      ['last_name', 'str:80', ['nn']],
      ['national_id', 'str:20'],
      ['mobile', 'str:20', ['nn']],
      ['email', 'str:150'],
      ['city', 'str:80'],
      ['birth_date', 'date'],
      ['gender', 'str:10'],
      ['marital_status', 'str:20'],
      ['education_level', 'str:60'],
      ['field_of_study', 'str:120'],
      ['resume_file', 'str:255'],
      ['photo', 'str:255'],
      ['source', 'str:60'],
      ['status', 'str:30', ['nn', 'def:new']],
      ['stage_key', 'str:60'],
      ['stage_id', 'int'],
      ['score', 'int'],
      ['rating', 'int'],
      ['assigned_to', 'int'],
      ['notes', 'text'],
      ['invite_id', 'int'],
      ['form_template_id', 'int'],
      ['form_progress', 'int', ['def:0']],
      ['submitted_at', 'dt'],
      ['decided_at', 'dt'],
      ['decision', 'str:40'],
      ['rejection_reason', 'text'],
      ['hired_employee_id', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['job_req_id'], ['mobile'], ['status'], ['assigned_to'], ['national_id']],
  },
  {
    name: 'application_answers',
    label: 'پاسخ‌های فرم استخدام',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['application_id', 'int', ['nn']],
      ['field_id', 'int'],
      ['fkey', 'str:80'],
      ['section_id', 'int'],
      ['label', 'str:200'],
      ['value', 'longtext'],
      ['file', 'str:255'],
      ['row_index', 'int', ['def:0']],
      ['sort_order', 'int'],
      ['updated_at', 'dt'],
    ],
    indexes: [['application_id'], ['fkey']],
  },
  {
    name: 'application_notes',
    label: 'نظرهای پرونده',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['application_id', 'int', ['nn']],
      ['author_id', 'int'],
      ['author_name', 'str:150'],
      ['type', 'str:40', ['def:hr']],
      ['content', 'text'],
      ['decision', 'str:40'],
      ['score', 'int'],
      ['visibility', 'str:30', ['def:hr']],
      ['stage_key', 'str:60'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['application_id'], ['type']],
  },
  {
    name: 'application_attachments',
    label: 'پیوست‌های پرونده',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['application_id', 'int', ['nn']],
      ['title', 'str:200'],
      ['file', 'str:255'],
      ['mime', 'str:100'],
      ['size', 'int'],
      ['uploaded_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['application_id']],
  },
  {
    name: 'application_stage_log',
    label: 'تاریخچه مراحل پرونده',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['application_id', 'int', ['nn']],
      ['from_stage', 'str:60'],
      ['to_stage', 'str:60'],
      ['user_id', 'int'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['application_id']],
  },
  {
    name: 'interviews',
    label: 'مصاحبه‌ها',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['application_id', 'int', ['nn']],
      ['job_req_id', 'int'],
      ['round', 'int', ['def:1']],
      ['type', 'str:40', ['def:in_person']],
      ['title', 'str:150'],
      ['scheduled_at', 'dt'],
      ['duration_minutes', 'int', ['def:45']],
      ['location', 'str:150'],
      ['meeting_link', 'str:255'],
      ['interviewer_ids', 'json'],
      ['status', 'str:30', ['def:scheduled']],
      ['score', 'int'],
      ['recommendation', 'str:40'],
      ['strengths', 'text'],
      ['weaknesses', 'text'],
      ['notes', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['application_id'], ['scheduled_at'], ['status']],
  },
  {
    name: 'interview_criteria',
    label: 'معیارهای مصاحبه',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['title', 'str:150', ['nn']],
      ['description', 'text'],
      ['weight', 'int', ['def:1']],
      ['max_score', 'int', ['def:5']],
      ['type', 'str:30', ['def:general']],
      ['status', 'str:20', ['def:active']],
      ['sort_order', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
  },
  {
    name: 'interview_scores',
    label: 'امتیاز مصاحبه',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['interview_id', 'int', ['nn']],
      ['criterion_id', 'int'],
      ['criterion_title', 'str:150'],
      ['score', 'float'],
      ['max_score', 'float'],
      ['comment', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['interview_id']],
  },
  {
    name: 'recruitment_invites',
    label: 'دعوت‌نامه‌ها (QR)',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['token', 'str:120', ['nn', 'u']],
      ['job_req_id', 'int'],
      ['application_id', 'int'],
      ['name', 'str:150'],
      ['mobile', 'str:20'],
      ['national_id', 'str:20'],
      ['purpose', 'str:40', ['def:form']],
      ['channels', 'json'],
      ['form_template_id', 'int'],
      ['status', 'str:30', ['def:created']],
      ['max_uses', 'int', ['def:1']],
      ['used_count', 'int', ['def:0']],
      ['requires_otp', 'bool', ['def:1']],
      ['verified_at', 'dt'],
      ['expires_at', 'dt'],
      ['sent_at', 'dt'],
      ['last_seen_at', 'dt'],
      ['created_by', 'int'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['job_req_id'], ['application_id'], ['mobile'], ['status']],
  },
  {
    name: 'assessment_tests',
    label: 'آزمون‌ها',
    module: 'assessment',
    cols: [
      ['id', 'id'],
      ['akey', 'str:60', ['nn', 'u']],
      ['name', 'str:200', ['nn']],
      ['type', 'str:40', ['def:mbti']],
      ['description', 'text'],
      ['instructions', 'text'],
      ['duration_minutes', 'int'],
      ['question_count', 'int'],
      ['is_active', 'bool', ['def:1']],
      ['is_locked', 'bool'],
      ['is_public', 'bool', ['def:1']],
      ['version', 'int', ['def:1']],
      ['show_to_candidate', 'bool'],
      ['result_visibility', 'str:30', ['def:hr_only']],
      ['intro_text', 'text'],
      ['thanks_text', 'text'],
      ['scoring_key', 'json'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },
  {
    name: 'assessment_questions',
    label: 'سؤالات آزمون',
    module: 'assessment',
    cols: [
      ['id', 'id'],
      ['test_id', 'int', ['nn']],
      ['number', 'int'],
      ['code', 'str:30'],
      ['question_text', 'text', ['nn']],
      ['axis', 'str:8'],
      ['option_a', 'text'],
      ['option_a_value', 'str:8'],
      ['option_b', 'text'],
      ['option_b_value', 'str:8'],
      ['help_text', 'text'],
      ['sort_order', 'int'],
      ['is_active', 'bool', ['def:1']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['test_id'], ['axis']],
  },
  {
    name: 'assessment_assignments',
    label: 'تخصیص آزمون',
    module: 'assessment',
    cols: [
      ['id', 'id'],
      ['test_id', 'int', ['nn']],
      ['application_id', 'int'],
      ['employee_id', 'int'],
      ['token', 'str:120', ['u']],
      ['status', 'str:30', ['def:pending']],
      ['sent_at', 'dt'],
      ['started_at', 'dt'],
      ['completed_at', 'dt'],
      ['expires_at', 'dt'],
      ['answer_count', 'int', ['def:0']],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['test_id'], ['application_id'], ['employee_id'], ['token']],
  },
  {
    name: 'assessment_answers',
    label: 'پاسخ‌های آزمون',
    module: 'assessment',
    cols: [
      ['id', 'id'],
      ['assignment_id', 'int', ['nn']],
      ['question_id', 'int', ['nn']],
      ['choice', 'str:8'],
      ['axis', 'str:8'],
      ['value', 'str:8'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['assignment_id'], ['question_id']],
  },
  {
    name: 'assessment_results',
    label: 'نتایج آزمون (محرمانه)',
    module: 'assessment',
    cols: [
      ['id', 'id'],
      ['assignment_id', 'int', ['nn']],
      ['test_id', 'int'],
      ['application_id', 'int'],
      ['employee_id', 'int'],
      ['type_code', 'str:8'],
      ['group_name', 'str:100'],
      ['axis_scores', 'json'],
      ['percentages', 'json'],
      ['closeness', 'json'],
      ['confidence', 'str:20'],
      ['borderline_axes', 'json'],
      ['summary', 'text'],
      ['strengths', 'json'],
      ['watchouts', 'json'],
      ['communication', 'text'],
      ['leadership', 'text'],
      ['motivation', 'text'],
      ['suggestions', 'json'],
      ['fit_notes', 'text'],
      ['job_fit', 'json'],
      ['risk_notes', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['assignment_id'], ['application_id'], ['employee_id'], ['type_code']],
  },
];

module.exports = T;
