'use strict';
/**
 * جدول‌های منابع انسانی: بدو ورود، آموزش، حضور و مرخصی، حقوق و دستمزد
 * و تسویه/ترک کار.
 */

const T = [
  /* ============================== بدو ورود ============================== */
  {
    name: 'onboarding_templates',
    label: 'قالب‌های بدو ورود',
    module: 'onboarding',
    cols: [
      ['id', 'id'],
      ['name', 'str:150', ['nn']],
      ['description', 'text'],
      ['department_id', 'int'],
      ['job_title_id', 'int'],
      ['is_active', 'bool', ['def:1']],
      ['is_default', 'bool'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['department_id']],
  },
  {
    name: 'onboarding_tasks',
    label: 'کارهای بدو ورود',
    module: 'onboarding',
    cols: [
      ['id', 'id'],
      ['template_id', 'int', ['nn']],
      ['title', 'str:200', ['nn']],
      ['description', 'text'],
      ['category', 'str:40'],
      ['owner_role', 'str:60'],
      ['due_days', 'int'],
      ['is_required', 'bool', ['def:1']],
      ['sort_order', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['template_id']],
  },
  {
    name: 'employee_onboarding',
    label: 'فرآیندهای بدو ورود',
    module: 'onboarding',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['template_id', 'int'],
      ['status', 'str:30', ['def:in_progress']],
      ['progress', 'int', ['def:0']],
      ['started_at', 'dt'],
      ['completed_at', 'dt'],
      ['assigned_to', 'int'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status']],
  },
  {
    name: 'employee_onboarding_tasks',
    label: 'کارهای بدو ورود کارمند',
    module: 'onboarding',
    cols: [
      ['id', 'id'],
      ['onboarding_id', 'int', ['nn']],
      ['task_id', 'int'],
      ['employee_id', 'int'],
      ['title', 'str:200', ['nn']],
      ['category', 'str:40'],
      ['owner_user_id', 'int'],
      ['due_date', 'date'],
      ['status', 'str:30', ['def:pending']],
      ['completed_at', 'dt'],
      ['completed_by', 'int'],
      ['note', 'text'],
      ['file', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['onboarding_id'], ['status'], ['owner_user_id']],
  },

  /* =============================== آموزش =============================== */
  {
    name: 'course_categories',
    label: 'دسته‌بندی دوره‌ها',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['name', 'str:120', ['nn']],
      ['description', 'text'],
      ['sort_order', 'int'],
      ['status', 'str:20', ['def:active']],
      ['created_at', 'dt', ['nn']],
    ],
  },
  {
    name: 'courses',
    label: 'دوره‌های آموزشی',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['code', 'str:40'],
      ['title', 'str:200', ['nn']],
      ['category_id', 'int'],
      ['category', 'str:80'],
      ['description', 'text'],
      ['objectives', 'text'],
      ['type', 'str:40', ['def:internal']],
      ['provider', 'str:150'],
      ['instructor_id', 'int'],
      ['instructor_name', 'str:150'],
      ['duration_hours', 'int'],
      ['duration_minutes', 'int'],
      ['level', 'str:30'],
      ['cost', 'money'],
      ['is_mandatory', 'bool'],
      ['has_certificate', 'bool', ['def:1']],
      ['pass_score', 'int', ['def:60']],
      ['cover', 'str:255'],
      ['content', 'json'],
      ['tags', 'str:255'],
      ['capacity', 'int'],
      ['enrolled_count', 'int', ['def:0']],
      ['status', 'str:30', ['nn', 'def:draft']],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['category_id'], ['status'], ['is_mandatory']],
  },
  {
    name: 'course_lessons',
    label: 'جلسات دوره',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['course_id', 'int', ['nn']],
      ['title', 'str:200', ['nn']],
      ['type', 'str:30', ['def:text']],
      ['content', 'longtext'],
      ['file', 'str:255'],
      ['video_url', 'str:255'],
      ['duration_minutes', 'int'],
      ['sort_order', 'int'],
      ['is_preview', 'bool'],
      ['is_active', 'bool', ['def:1']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['course_id']],
  },
  {
    name: 'course_quizzes',
    label: 'آزمون‌های دوره',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['course_id', 'int', ['nn']],
      ['lesson_id', 'int'],
      ['title', 'str:200', ['nn']],
      ['pass_score', 'int', ['def:60']],
      ['questions', 'json'],
      ['is_active', 'bool', ['def:1']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['course_id']],
  },
  {
    name: 'enrollments',
    label: 'ثبت‌نام دوره‌ها',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['course_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['assigned_by', 'int'],
      ['assigned_at', 'dt'],
      ['due_date', 'date'],
      ['status', 'str:30', ['def:assigned']],
      ['progress', 'int', ['def:0']],
      ['started_at', 'dt'],
      ['completed_at', 'dt'],
      ['score', 'int'],
      ['certificate_no', 'str:60'],
      ['feedback', 'text'],
      ['rating', 'int'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['course_id'], ['employee_id'], ['status'], ['due_date']],
  },
  {
    name: 'enrollment_progress',
    label: 'پیشرفت جلسات',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['enrollment_id', 'int', ['nn']],
      ['lesson_id', 'int', ['nn']],
      ['status', 'str:30', ['def:pending']],
      ['seconds', 'int', ['def:0']],
      ['completed_at', 'dt'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['enrollment_id'], ['lesson_id']],
  },
  {
    name: 'certificates',
    label: 'گواهی‌های آموزشی',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['course_id', 'int'],
      ['enrollment_id', 'int'],
      ['title', 'str:200', ['nn']],
      ['number', 'str:60'],
      ['issuer', 'str:150'],
      ['issued_at', 'date'],
      ['expires_at', 'date'],
      ['file', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id'], ['course_id']],
  },
  {
    name: 'training_requests',
    label: 'درخواست‌های آموزشی',
    module: 'training',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['course_title', 'str:200', ['nn']],
      ['provider', 'str:150'],
      ['type', 'str:40'],
      ['cost', 'money'],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['reason', 'text'],
      ['status', 'str:30', ['def:pending']],
      ['approved_by', 'int'],
      ['approved_at', 'dt'],
      ['decision_note', 'text'],
      ['attachment', 'str:255'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status']],
  },

  /* =========================== حضور و مرخصی =========================== */
  {
    name: 'leave_types',
    label: 'انواع مرخصی',
    module: 'attendance',
    cols: [
      ['id', 'id'],
      ['lkey', 'str:60', ['nn', 'u']],
      ['name', 'str:120', ['nn']],
      ['color', 'str:20'],
      ['is_paid', 'bool', ['def:1']],
      ['max_days_year', 'float'],
      ['monthly_accrual', 'float'],
      ['requires_approval', 'bool', ['def:1']],
      ['requires_doc', 'bool'],
      ['carry_forward', 'bool'],
      ['encashable', 'bool'],
      ['hourly', 'bool'],
      ['description', 'text'],
      ['status', 'str:20', ['def:active']],
      ['sort_order', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
  },
  {
    name: 'leave_balances',
    label: 'مانده مرخصی',
    module: 'attendance',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['leave_type_id', 'int', ['nn']],
      ['year', 'int', ['nn']],
      ['entitled', 'float', ['def:0']],
      ['used', 'float', ['def:0']],
      ['pending', 'float', ['def:0']],
      ['carried', 'float', ['def:0']],
      ['adjustment', 'float', ['def:0']],
      ['encashed', 'float', ['def:0']],
      ['note', 'text'],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['leave_type_id'], ['year']],
  },
  {
    name: 'leave_requests',
    label: 'درخواست‌های مرخصی',
    module: 'attendance',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['leave_type_id', 'int', ['nn']],
      ['from_date', 'date', ['nn']],
      ['to_date', 'date', ['nn']],
      ['days', 'float'],
      ['hours', 'float'],
      ['is_hourly', 'bool'],
      ['reason', 'text'],
      ['attachment', 'str:255'],
      ['status', 'str:30', ['nn', 'def:pending']],
      ['approver_id', 'int'],
      ['manager_decision_at', 'dt'],
      ['hr_decision_at', 'dt'],
      ['decision_note', 'text'],
      ['replacement_employee_id', 'int'],
      ['address_during_leave', 'str:255'],
      ['contact_during_leave', 'str:30'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status'], ['from_date']],
  },
  {
    name: 'attendance_records',
    label: 'حضور و غیاب',
    module: 'attendance',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['work_date', 'date', ['nn']],
      ['check_in', 'str:10'],
      ['check_out', 'str:10'],
      ['worked_minutes', 'int'],
      ['overtime_minutes', 'int'],
      ['late_minutes', 'int'],
      ['early_leave_minutes', 'int'],
      ['status', 'str:30'],
      ['shift_id', 'int'],
      ['source', 'str:40', ['def:manual']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['work_date'], ['status']],
  },
  {
    name: 'overtime_records',
    label: 'اضافه‌کاری',
    module: 'attendance',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['work_date', 'date'],
      ['hours', 'float'],
      ['rate', 'float', ['def:1.4']],
      ['type', 'str:30', ['def:normal']],
      ['reason', 'str:255'],
      ['status', 'str:30', ['def:pending']],
      ['approved_by', 'int'],
      ['payroll_period_id', 'int'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id'], ['work_date'], ['status']],
  },
  {
    name: 'missions',
    label: 'مأموریت‌ها',
    module: 'attendance',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['title', 'str:200'],
      ['destination', 'str:150'],
      ['from_date', 'date'],
      ['to_date', 'date'],
      ['days', 'float'],
      ['transport_type', 'str:60'],
      ['cost', 'money'],
      ['status', 'str:30', ['def:pending']],
      ['approved_by', 'int'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id'], ['status']],
  },
  {
    name: 'holidays',
    label: 'تعطیلات رسمی',
    module: 'attendance',
    cols: [
      ['id', 'id'],
      ['title', 'str:150', ['nn']],
      ['jdate', 'str:20'],
      ['gdate', 'date'],
      ['type', 'str:30', ['def:official']],
      ['is_paid', 'bool', ['def:1']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['gdate']],
  },

  /* ============================ حقوق و دستمزد ============================ */
  {
    name: 'payroll_periods',
    label: 'دوره‌های حقوق',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['title', 'str:120', ['nn']],
      ['year', 'int', ['nn']],
      ['month', 'int', ['nn']],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['pay_date', 'date'],
      ['status', 'str:30', ['nn', 'def:draft']],
      ['employee_count', 'int', ['def:0']],
      ['total_gross', 'money'],
      ['total_deduction', 'money'],
      ['total_net', 'money'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['approved_by', 'int'],
      ['approved_at', 'dt'],
      ['locked_at', 'dt'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['year'], ['month'], ['status']],
  },
  {
    name: 'payroll_components',
    label: 'اقلام حقوق',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['ckey', 'str:60', ['nn', 'u']],
      ['name', 'str:120', ['nn']],
      ['type', 'str:20', ['nn', 'def:earning']],
      ['category', 'str:40'],
      ['calc_type', 'str:30', ['def:fixed']],
      ['default_value', 'money'],
      ['percent_of', 'str:60'],
      ['percentage', 'float'],
      ['formula', 'str:255'],
      ['taxable', 'bool', ['def:1']],
      ['insurable', 'bool', ['def:1']],
      ['affects_net', 'bool', ['def:1']],
      ['is_employer_cost', 'bool'],
      ['is_system', 'bool'],
      ['is_active', 'bool', ['def:1']],
      ['show_on_payslip', 'bool', ['def:1']],
      ['sort_order', 'int'],
      ['description', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['type'], ['category']],
  },
  {
    name: 'payroll_settings',
    label: 'تنظیمات حقوق',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['skey', 'str:80', ['nn', 'u']],
      ['value', 'str:255'],
      ['year', 'int'],
      ['title', 'str:200'],
      ['description', 'text'],
      ['updated_at', 'dt'],
    ],
    indexes: [['year']],
  },
  {
    name: 'payroll_employee_settings',
    label: 'اقلام اختصاصی کارمند',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['component_id', 'int', ['nn']],
      ['value', 'money'],
      ['percent', 'float'],
      ['effective_from', 'date'],
      ['effective_to', 'date'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['component_id']],
  },
  {
    name: 'payroll_runs',
    label: 'فیش‌های محاسبه‌شده',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['period_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['personnel_code', 'str:40'],
      ['employee_name', 'str:150'],
      ['days_worked', 'float', ['def:30']],
      ['days_insurance', 'float', ['def:30']],
      ['overtime_hours', 'float', ['def:0']],
      ['gross', 'money'],
      ['total_earnings', 'money'],
      ['total_deductions', 'money'],
      ['insurance_employee', 'money'],
      ['insurance_employer', 'money'],
      ['unemployment_insurance', 'money'],
      ['income_tax', 'money'],
      ['net', 'money'],
      ['status', 'str:30', ['def:calculated']],
      ['payment_status', 'str:30', ['def:unpaid']],
      ['paid_at', 'dt'],
      ['bank_ref', 'str:60'],
      ['snapshot', 'json'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['period_id'], ['employee_id'], ['payment_status']],
  },
  {
    name: 'payroll_items',
    label: 'ردیف‌های فیش حقوقی',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['run_id', 'int', ['nn']],
      ['component_id', 'int'],
      ['component_key', 'str:60'],
      ['title', 'str:150', ['nn']],
      ['type', 'str:20', ['nn', 'def:earning']],
      ['category', 'str:40'],
      ['calc_type', 'str:30'],
      ['qty', 'float'],
      ['rate', 'money'],
      ['amount', 'money'],
      ['taxable', 'bool', ['def:1']],
      ['insurable', 'bool', ['def:1']],
      ['is_manual', 'bool'],
      ['note', 'str:255'],
      ['sort_order', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['run_id'], ['component_key']],
  },
  {
    name: 'payroll_adjustments',
    label: 'اصلاحات حقوق',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['period_id', 'int'],
      ['component_id', 'int'],
      ['title', 'str:150', ['nn']],
      ['type', 'str:20', ['nn', 'def:earning']],
      ['amount', 'money'],
      ['reason', 'text'],
      ['status', 'str:30', ['def:pending']],
      ['created_by', 'int'],
      ['approved_by', 'int'],
      ['approved_at', 'dt'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id'], ['period_id'], ['status']],
  },
  {
    name: 'loans',
    label: 'وام‌ها',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['code', 'str:40'],
      ['title', 'str:150', ['nn']],
      ['amount', 'money'],
      ['installments', 'int'],
      ['installment_amount', 'money'],
      ['first_period_id', 'int'],
      ['paid_installments', 'int', ['def:0']],
      ['remaining', 'money'],
      ['status', 'str:30', ['def:pending']],
      ['reason', 'text'],
      ['guarantee', 'text'],
      ['approved_by', 'int'],
      ['approved_at', 'dt'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status']],
  },
  {
    name: 'loan_installments',
    label: 'اقساط وام',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['loan_id', 'int', ['nn']],
      ['period_id', 'int'],
      ['no', 'int'],
      ['amount', 'money'],
      ['status', 'str:30', ['def:pending']],
      ['deducted_at', 'dt'],
      ['note', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['loan_id'], ['period_id']],
  },
  {
    name: 'tax_brackets',
    label: 'پله‌های مالیات',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['year', 'int', ['nn']],
      ['title', 'str:100'],
      ['from_amount', 'money'],
      ['to_amount', 'money'],
      ['rate_percent', 'float'],
      ['exemption', 'money'],
      ['is_active', 'bool', ['def:1']],
      ['sort_order', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['year']],
  },
  {
    name: 'payslips',
    label: 'فیش‌های حقوقی صادرشده',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['run_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['period_id', 'int'],
      ['number', 'str:60'],
      ['serial', 'str:60'],
      ['verify_code', 'str:40'],
      ['issued_at', 'dt'],
      ['issued_by', 'int'],
      ['status', 'str:30', ['def:issued']],
      ['snapshot', 'json'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['run_id'], ['employee_id'], ['period_id']],
  },
  {
    name: 'salary_payments',
    label: 'پرداخت حقوق',
    module: 'payroll',
    cols: [
      ['id', 'id'],
      ['payroll_run_id', 'int'],
      ['period_id', 'int'],
      ['employee_id', 'int'],
      ['amount', 'money'],
      ['method', 'str:30', ['def:bank']],
      ['bank', 'str:80'],
      ['reference', 'str:80'],
      ['paid_at', 'dt'],
      ['status', 'str:30', ['def:paid']],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['period_id'], ['employee_id']],
  },

  /* =========================== تسویه و ترک کار =========================== */
  {
    name: 'offboarding_requests',
    label: 'درخواست‌های ترک کار',
    module: 'offboarding',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['title', 'str:200'],
      ['code', 'str:40'],
      ['type', 'str:40', ['nn', 'def:resignation']],
      ['requested_at', 'date'],
      ['last_working_day', 'date'],
      ['reason', 'text'],
      ['description', 'text'],
      ['status', 'str:30', ['nn', 'def:pending']],
      ['employee_decision', 'str:30'],
      ['manager_decision', 'str:30'],
      ['hr_decision', 'str:30'],
      ['ceo_decision', 'str:30'],
      ['handover_to', 'int'],
      ['handover_notes', 'text'],
      ['settlement_status', 'str:30', ['def:pending']],
      ['file', 'str:255'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['completed_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status'], ['last_working_day']],
  },
  {
    name: 'offboarding_tasks',
    label: 'کارهای ترک کار',
    module: 'offboarding',
    cols: [
      ['id', 'id'],
      ['offboarding_id', 'int', ['nn']],
      ['title', 'str:200', ['nn']],
      ['category', 'str:40'],
      ['owner_user_id', 'int'],
      ['due_date', 'date'],
      ['status', 'str:30', ['def:pending']],
      ['note', 'text'],
      ['completed_at', 'dt'],
      ['completed_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['offboarding_id'], ['status']],
  },
  {
    name: 'clearances',
    label: 'تسویه بین واحدی',
    module: 'offboarding',
    cols: [
      ['id', 'id'],
      ['offboarding_id', 'int', ['nn']],
      ['department', 'str:100', ['nn']],
      ['title', 'str:200'],
      ['items', 'json'],
      ['status', 'str:30', ['def:pending']],
      ['cleared_by', 'int'],
      ['cleared_at', 'dt'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['offboarding_id']],
  },
  {
    name: 'settlements',
    label: 'تسویه حساب نهایی',
    module: 'offboarding',
    cols: [
      ['id', 'id'],
      ['offboarding_id', 'int'],
      ['employee_id', 'int', ['nn']],
      ['last_salary', 'money'],
      ['leave_days', 'float'],
      ['leave_amount', 'money'],
      ['bonus_amount', 'money'],
      ['notice_amount', 'money'],
      ['severance_amount', 'money'],
      ['other_earnings', 'money'],
      ['debt_amount', 'money'],
      ['loan_balance', 'money'],
      ['other_deductions', 'money'],
      ['net_payable', 'money'],
      ['breakdown', 'json'],
      ['status', 'str:30', ['def:draft']],
      ['approved_by', 'int'],
      ['approved_at', 'dt'],
      ['paid_at', 'dt'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status']],
  },
];

module.exports = T;
