'use strict';
/**
 * جدول‌های عملیاتی و رفاهی: ایاب و ذهاب، آشپزخانه، نگهبانی، رفاهیات،
 * مجوزها و امور دانش‌بنیان، مالکیت فکری، سهامداران، امور ثبتی و حقوقی،
 * اموال، درخواست‌های پرسنلی، اطلاعیه‌ها و گزارش‌ها.
 */

const T = [
  /* ============================ ایاب و ذهاب ============================ */
  {
    name: 'transport_vehicles',
    label: 'ناوگان',
    module: 'transport',
    cols: [
      ['id', 'id'],
      ['plate_no', 'str:30', ['nn']],
      ['title', 'str:120'],
      ['type', 'str:40', ['def:bus']],
      ['model', 'str:80'],
      ['year_made', 'int'],
      ['capacity', 'int'],
      ['driver_employee_id', 'int'],
      ['driver_name', 'str:120'],
      ['driver_mobile', 'str:20'],
      ['own_vehicle', 'bool', ['def:1']],
      ['vendor', 'str:120'],
      ['insurance_expiry', 'date'],
      ['technical_expiry', 'date'],
      ['last_service_date', 'date'],
      ['odometer', 'int'],
      ['fuel_type', 'str:30'],
      ['status', 'str:30', ['nn', 'def:active']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['status'], ['driver_employee_id']],
  },
  {
    name: 'transport_routes',
    label: 'مسیرهای سرویس',
    module: 'transport',
    cols: [
      ['id', 'id'],
      ['name', 'str:150', ['nn']],
      ['code', 'str:40'],
      ['vehicle_id', 'int'],
      ['driver_employee_id', 'int'],
      ['driver_name', 'str:120'],
      ['driver_mobile', 'str:20'],
      ['capacity', 'int'],
      ['shift_name', 'str:80'],
      ['departure_time', 'str:10'],
      ['return_time', 'str:10'],
      ['direction', 'str:30', ['def:both']],
      ['days_of_week', 'json'],
      ['monthly_fee', 'money'],
      ['supervisor_name', 'str:120'],
      ['description', 'text'],
      ['status', 'str:30', ['nn', 'def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['vehicle_id'], ['status']],
  },
  {
    name: 'transport_stops',
    label: 'ایستگاه‌های سرویس',
    module: 'transport',
    cols: [
      ['id', 'id'],
      ['route_id', 'int', ['nn']],
      ['title', 'str:150', ['nn']],
      ['address', 'text'],
      ['landmark', 'str:150'],
      ['lat', 'float'],
      ['lng', 'float'],
      ['pickup_time', 'str:10'],
      ['dropoff_time', 'str:10'],
      ['sort_order', 'int'],
      ['status', 'str:20', ['def:active']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['route_id']],
  },
  {
    name: 'transport_subscriptions',
    label: 'اشتراک سرویس کارکنان',
    module: 'transport',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['route_id', 'int', ['nn']],
      ['stop_id', 'int'],
      ['from_date', 'date'],
      ['to_date', 'date'],
      ['days_of_week', 'json'],
      ['direction', 'str:30', ['def:both']],
      ['status', 'str:30', ['def:active']],
      ['fee', 'money'],
      ['approved_by', 'int'],
      ['approved_at', 'dt'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['route_id'], ['status']],
  },
  {
    name: 'transport_trips',
    label: 'سفرهای سرویس',
    module: 'transport',
    cols: [
      ['id', 'id'],
      ['route_id', 'int', ['nn']],
      ['vehicle_id', 'int'],
      ['trip_date', 'date', ['nn']],
      ['direction', 'str:30', ['def:outbound']],
      ['driver_employee_id', 'int'],
      ['driver_name', 'str:120'],
      ['departed_at', 'str:10'],
      ['arrived_at', 'str:10'],
      ['passenger_count', 'int', ['def:0']],
      ['capacity', 'int'],
      ['odometer_start', 'int'],
      ['odometer_end', 'int'],
      ['cost', 'money'],
      ['status', 'str:30', ['def:scheduled']],
      ['incident', 'text'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['route_id'], ['trip_date'], ['status']],
  },
  {
    name: 'transport_trip_passengers',
    label: 'مسافران سفر',
    module: 'transport',
    cols: [
      ['id', 'id'],
      ['trip_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['stop_id', 'int'],
      ['status', 'str:30', ['def:boarded']],
      ['note', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['trip_id'], ['employee_id']],
  },

  /* ============================= آشپزخانه ============================= */
  {
    name: 'meal_plans',
    label: 'طرح‌های غذایی',
    module: 'kitchen',
    cols: [
      ['id', 'id'],
      ['title', 'str:150', ['nn']],
      ['from_date', 'date'],
      ['to_date', 'date'],
      ['unit_price', 'money'],
      ['guest_price', 'money'],
      ['subsidy', 'money'],
      ['meal_types', 'json'],
      ['is_active', 'bool', ['def:1']],
      ['description', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },
  {
    name: 'kitchen_menus',
    label: 'منوی روزانه',
    module: 'kitchen',
    cols: [
      ['id', 'id'],
      ['plan_id', 'int'],
      ['menu_date', 'date', ['nn']],
      ['meal_type', 'str:30', ['def:lunch']],
      ['title', 'str:200', ['nn']],
      ['description', 'text'],
      ['items', 'json'],
      ['cost', 'money'],
      ['capacity', 'int'],
      ['reserved_count', 'int', ['def:0']],
      ['served_count', 'int', ['def:0']],
      ['status', 'str:30', ['def:published']],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['menu_date'], ['meal_type'], ['status']],
  },
  {
    name: 'meal_reservations',
    label: 'رزرو غذا',
    module: 'kitchen',
    cols: [
      ['id', 'id'],
      ['menu_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['meal_date', 'date'],
      ['meal_type', 'str:30'],
      ['count', 'int', ['def:1']],
      ['guest_count', 'int', ['def:0']],
      ['status', 'str:30', ['def:reserved']],
      ['reserved_at', 'dt'],
      ['cancel_reason', 'str:255'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['menu_id'], ['employee_id'], ['meal_date']],
  },
  {
    name: 'meal_attendance',
    label: 'حضور در وعده غذایی',
    module: 'kitchen',
    cols: [
      ['id', 'id'],
      ['menu_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['served', 'bool', ['def:1']],
      ['portions', 'int', ['def:1']],
      ['served_at', 'dt'],
      ['by_user', 'int'],
      ['note', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['menu_id'], ['employee_id']],
  },
  {
    name: 'kitchen_costs',
    label: 'هزینه‌های آشپزخانه',
    module: 'kitchen',
    cols: [
      ['id', 'id'],
      ['period_month', 'str:7'],
      ['category', 'str:40', ['def:materials']],
      ['title', 'str:150', ['nn']],
      ['amount', 'money'],
      ['qty', 'float'],
      ['unit', 'str:30'],
      ['vendor', 'str:120'],
      ['spent_on', 'date'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['period_month'], ['category']],
  },
  {
    name: 'kitchen_inventory',
    label: 'انبار آشپزخانه',
    module: 'kitchen',
    cols: [
      ['id', 'id'],
      ['title', 'str:150', ['nn']],
      ['category', 'str:40'],
      ['unit', 'str:30'],
      ['qty', 'float', ['def:0']],
      ['min_qty', 'float'],
      ['unit_price', 'money'],
      ['expiry_date', 'date'],
      ['location', 'str:80'],
      ['status', 'str:20', ['def:ok']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['category']],
  },

  /* ============================== نگهبانی ============================== */
  {
    name: 'security_posts',
    label: 'پست‌های نگهبانی',
    module: 'security',
    cols: [
      ['id', 'id'],
      ['title', 'str:150', ['nn']],
      ['location_id', 'int'],
      ['type', 'str:40', ['def:main_gate']],
      ['required_guards', 'int', ['def:1']],
      ['instructions', 'text'],
      ['status', 'str:20', ['def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['location_id']],
  },
  {
    name: 'security_shifts',
    label: 'شیفت‌های نگهبانی',
    module: 'security',
    cols: [
      ['id', 'id'],
      ['location_id', 'int'],
      ['post_id', 'int'],
      ['shift_name', 'str:60', ['nn']],
      ['start_time', 'str:10'],
      ['end_time', 'str:10'],
      ['guard_employee_id', 'int'],
      ['guard_name', 'str:120'],
      ['guard_mobile', 'str:20'],
      ['from_date', 'date'],
      ['to_date', 'date'],
      ['day_of_week', 'str:30'],
      ['status', 'str:20', ['def:active']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['location_id'], ['guard_employee_id']],
  },
  {
    name: 'security_patrols',
    label: 'گزارش گشت و نگهبانی',
    module: 'security',
    cols: [
      ['id', 'id'],
      ['location_id', 'int'],
      ['patrol_date', 'date', ['nn']],
      ['shift_name', 'str:60'],
      ['guard_employee_id', 'int'],
      ['guard_name', 'str:120'],
      ['start_at', 'str:10'],
      ['end_at', 'str:10'],
      ['checkpoints', 'json'],
      ['incidents', 'text'],
      ['handover_note', 'text'],
      ['status', 'str:20', ['def:submitted']],
      ['supervisor_note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['patrol_date'], ['location_id']],
  },
  {
    name: 'security_incidents',
    label: 'حوادث و رخدادها',
    module: 'security',
    cols: [
      ['id', 'id'],
      ['location_id', 'int'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40'],
      ['severity', 'str:20', ['def:low']],
      ['happened_at', 'dt'],
      ['description', 'text'],
      ['action_taken', 'text'],
      ['reported_by', 'int'],
      ['person_involved', 'str:150'],
      ['status', 'str:30', ['def:open']],
      ['attachment', 'str:255'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['location_id'], ['status'], ['severity']],
  },
  {
    name: 'visitors_log',
    label: 'دفتر ورود و خروج مهمان',
    module: 'security',
    cols: [
      ['id', 'id'],
      ['location_id', 'int'],
      ['visitor_name', 'str:150', ['nn']],
      ['national_id', 'str:20'],
      ['mobile', 'str:20'],
      ['company', 'str:150'],
      ['host_employee_id', 'int'],
      ['purpose', 'str:200'],
      ['badge_no', 'str:30'],
      ['entry_at', 'dt'],
      ['exit_at', 'dt'],
      ['vehicle_plate', 'str:30'],
      ['items_in', 'text'],
      ['note', 'text'],
      ['registered_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['entry_at'], ['visitor_name'], ['host_employee_id']],
  },

  /* ============================== رفاهیات ============================== */
  {
    name: 'welfare_facilities',
    label: 'امکانات رفاهی',
    module: 'welfare',
    cols: [
      ['id', 'id'],
      ['name', 'str:150', ['nn']],
      ['type', 'str:40'],
      ['location_id', 'int'],
      ['capacity', 'int'],
      ['open_hours', 'str:80'],
      ['fee', 'money'],
      ['rules', 'text'],
      ['status', 'str:20', ['def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },
  {
    name: 'facility_bookings',
    label: 'رزرو امکانات',
    module: 'welfare',
    cols: [
      ['id', 'id'],
      ['facility_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['booking_date', 'date'],
      ['from_time', 'str:10'],
      ['to_time', 'str:10'],
      ['guests', 'int', ['def:0']],
      ['purpose', 'str:255'],
      ['status', 'str:30', ['def:pending']],
      ['approved_by', 'int'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['facility_id'], ['employee_id'], ['booking_date']],
  },
  {
    name: 'welfare_requests',
    label: 'درخواست‌های رفاهی',
    module: 'welfare',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['type', 'str:40'],
      ['title', 'str:200', ['nn']],
      ['description', 'text'],
      ['amount', 'money'],
      ['status', 'str:30', ['def:pending']],
      ['approved_by', 'int'],
      ['approved_at', 'dt'],
      ['decision_note', 'text'],
      ['file', 'str:255'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status'], ['type']],
  },
  {
    name: 'welfare_events',
    label: 'برنامه‌های رفاهی',
    module: 'welfare',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40', ['def:event']],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['location', 'str:150'],
      ['description', 'text'],
      ['budget', 'money'],
      ['cost', 'money'],
      ['attendees', 'json'],
      ['organizer', 'str:150'],
      ['status', 'str:30', ['def:planned']],
      ['file', 'str:255'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['type'], ['start_date']],
  },
  {
    name: 'welfare_insurance',
    label: 'بیمه تکمیلی',
    module: 'welfare',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['insurer', 'str:150'],
      ['policy_no', 'str:60'],
      ['type', 'str:40', ['def:health']],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['premium', 'money'],
      ['coverage', 'text'],
      ['dependents', 'json'],
      ['file', 'str:255'],
      ['status', 'str:20', ['def:active']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['end_date']],
  },

  /* ========================= مجوزها و دانش‌بنیان ========================= */
  {
    name: 'licenses',
    label: 'مجوزها و پروانه‌ها',
    module: 'licensing',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['number', 'str:60'],
      ['authority', 'str:150'],
      ['type', 'str:60', ['def:license']],
      ['category', 'str:60'],
      ['issue_date', 'date'],
      ['expiry_date', 'date'],
      ['renewal_date', 'date'],
      ['owner_user_id', 'int'],
      ['responsible_name', 'str:150'],
      ['cost', 'money'],
      ['status', 'str:30', ['def:valid']],
      ['reminder_days', 'int', ['def:30']],
      ['file', 'str:255'],
      ['notes', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['status'], ['expiry_date'], ['type']],
  },
  {
    name: 'license_renewals',
    label: 'تمدیدهای مجوز',
    module: 'licensing',
    cols: [
      ['id', 'id'],
      ['license_id', 'int', ['nn']],
      ['renewed_at', 'date'],
      ['new_expiry', 'date'],
      ['cost', 'money'],
      ['reference', 'str:80'],
      ['attachment', 'str:255'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['license_id']],
  },
  {
    name: 'knowledge_based',
    label: 'امور دانش‌بنیان',
    module: 'knowledge',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['status', 'str:30', ['def:pending']],
      ['assessment_no', 'str:60'],
      ['level', 'str:30'],
      ['evaluation_date', 'date'],
      ['expiry_date', 'date'],
      ['authority', 'str:150'],
      ['product_desc', 'text'],
      ['revenue_share', 'str:150'],
      ['tax_exempt_note', 'text'],
      ['responsible_name', 'str:150'],
      ['reminder_days', 'int', ['def:60']],
      ['file', 'str:255'],
      ['notes', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['status'], ['expiry_date']],
  },
  {
    name: 'ip_assets',
    label: 'مالکیت فکری',
    module: 'ip',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40', ['def:patent']],
      ['registry_no', 'str:60'],
      ['authority', 'str:150'],
      ['owner', 'str:150'],
      ['inventors', 'str:255'],
      ['filing_date', 'date'],
      ['grant_date', 'date'],
      ['expiry_date', 'date'],
      ['renewal_date', 'date'],
      ['status', 'str:30', ['def:filed']],
      ['annual_fee', 'money'],
      ['file', 'str:255'],
      ['notes', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['type'], ['status'], ['expiry_date']],
  },

  /* ======================== سهامداران و امور شرکت ======================== */
  {
    name: 'shareholders',
    label: 'سهامداران',
    module: 'shareholders',
    cols: [
      ['id', 'id'],
      ['person_type', 'str:20', ['def:real']],
      ['name', 'str:200', ['nn']],
      ['national_id', 'str:20'],
      ['father_name', 'str:80'],
      ['birth_date', 'date'],
      ['reg_no', 'str:40'],
      ['economic_code', 'str:40'],
      ['mobile', 'str:20'],
      ['phone', 'str:30'],
      ['email', 'str:150'],
      ['address', 'text'],
      ['share_type', 'str:40', ['def:ordinary']],
      ['shares_count', 'big'],
      ['share_percent', 'float'],
      ['nominal_value', 'money'],
      ['paid_amount', 'money'],
      ['payment_date', 'date'],
      ['join_date', 'date'],
      ['status', 'str:20', ['def:active']],
      ['bank_account', 'str:40'],
      ['note', 'text'],
      ['file', 'str:255'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['status'], ['national_id']],
  },
  {
    name: 'shareholder_transactions',
    label: 'معاملات سهام',
    module: 'shareholders',
    cols: [
      ['id', 'id'],
      ['shareholder_id', 'int', ['nn']],
      ['type', 'str:40', ['nn', 'def:transfer']],
      ['tdate', 'date'],
      ['shares', 'big'],
      ['price_per_share', 'money'],
      ['amount', 'money'],
      ['from_shareholder_id', 'int'],
      ['to_shareholder_id', 'int'],
      ['reference', 'str:80'],
      ['meeting_id', 'int'],
      ['note', 'text'],
      ['file', 'str:255'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['shareholder_id'], ['type'], ['tdate']],
  },
  {
    name: 'board_members',
    label: 'اعضای هیئت‌مدیره',
    module: 'corporate',
    cols: [
      ['id', 'id'],
      ['name', 'str:150', ['nn']],
      ['national_id', 'str:20'],
      ['role', 'str:60', ['def:member']],
      ['company', 'str:150'],
      ['member_type', 'str:30', ['def:main']],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['attendance_rate', 'float'],
      ['reward', 'money'],
      ['note', 'text'],
      ['status', 'str:20', ['def:active']],
      ['file', 'str:255'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['role'], ['status']],
  },
  {
    name: 'general_meetings',
    label: 'مجامع عمومی',
    module: 'corporate',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40', ['def:ordinary']],
      ['meeting_date', 'date'],
      ['meeting_time', 'str:10'],
      ['location', 'str:150'],
      ['agenda', 'text'],
      ['decisions', 'text'],
      ['quorum_percent', 'float'],
      ['attendees', 'json'],
      ['file', 'str:255'],
      ['status', 'str:30', ['def:planned']],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['meeting_date'], ['type']],
  },
  {
    name: 'corporate_records',
    label: 'امور ثبتی شرکت',
    module: 'corporate',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40', ['def:registration']],
      ['reg_no', 'str:60'],
      ['authority', 'str:150'],
      ['rdate', 'date'],
      ['expiry_date', 'date'],
      ['description', 'text'],
      ['file', 'str:255'],
      ['status', 'str:20', ['def:active']],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['type']],
  },
  {
    name: 'legal_contracts',
    label: 'قراردادهای حقوقی',
    module: 'legal',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:60'],
      ['party_name', 'str:200'],
      ['party_national_id', 'str:20'],
      ['subject', 'text'],
      ['amount', 'money'],
      ['start_date', 'date'],
      ['end_date', 'date'],
      ['status', 'str:30', ['def:active']],
      ['responsible_user_id', 'int'],
      ['renewal_notice_days', 'int', ['def:30']],
      ['file', 'str:255'],
      ['notes', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['status'], ['end_date'], ['party_name']],
  },
  {
    name: 'legal_cases',
    label: 'پرونده‌های حقوقی',
    module: 'legal',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40', ['def:claim']],
      ['case_no', 'str:60'],
      ['court', 'str:150'],
      ['opponent', 'str:200'],
      ['opponent_national_id', 'str:20'],
      ['subject', 'text'],
      ['claim_amount', 'money'],
      ['status', 'str:30', ['def:open']],
      ['next_hearing', 'date'],
      ['lawyer', 'str:150'],
      ['lawyer_phone', 'str:30'],
      ['description', 'text'],
      ['outcome', 'text'],
      ['file', 'str:255'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['status'], ['next_hearing']],
  },
  {
    name: 'compliance_items',
    label: 'تکالیف قانونی',
    module: 'legal',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['authority', 'str:150'],
      ['requirement', 'text'],
      ['due_date', 'date'],
      ['done_at', 'dt'],
      ['status', 'str:30', ['def:open']],
      ['owner_user_id', 'int'],
      ['evidence', 'str:255'],
      ['recurrence', 'str:40'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['status'], ['due_date']],
  },

  /* ========================= اموال و درخواست‌ها ========================= */
  {
    name: 'assets',
    label: 'اموال و تجهیزات',
    module: 'assets',
    cols: [
      ['id', 'id'],
      ['code', 'str:40', ['u']],
      ['title', 'str:200', ['nn']],
      ['type', 'str:50'],
      ['brand', 'str:80'],
      ['model', 'str:80'],
      ['serial', 'str:80'],
      ['location_id', 'int'],
      ['employee_id', 'int'],
      ['assigned_at', 'dt'],
      ['purchase_date', 'date'],
      ['price', 'money'],
      ['warranty_expiry', 'date'],
      ['condition_note', 'str:255'],
      ['status', 'str:30', ['def:available']],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['deleted_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status'], ['type']],
  },
  {
    name: 'asset_assignments',
    label: 'تحویل اموال',
    module: 'assets',
    cols: [
      ['id', 'id'],
      ['asset_id', 'int', ['nn']],
      ['employee_id', 'int', ['nn']],
      ['assigned_at', 'dt'],
      ['returned_at', 'dt'],
      ['condition_out', 'str:60'],
      ['condition_in', 'str:60'],
      ['note', 'text'],
      ['by_user', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['asset_id'], ['employee_id']],
  },
  {
    name: 'hr_requests',
    label: 'درخواست‌های پرسنلی',
    module: 'requests',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['type', 'str:40', ['nn', 'def:letter']],
      ['subject', 'str:200', ['nn']],
      ['description', 'text'],
      ['status', 'str:30', ['def:pending']],
      ['ref_no', 'str:60'],
      ['decision_note', 'text'],
      ['handled_by', 'int'],
      ['file', 'str:255'],
      ['attachment', 'str:255'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
      ['done_at', 'dt'],
    ],
    indexes: [['employee_id'], ['status'], ['type']],
  },
  {
    name: 'letter_templates',
    label: 'قالب‌های نامه',
    module: 'requests',
    cols: [
      ['id', 'id'],
      ['tkey', 'str:60', ['nn', 'u']],
      ['title', 'str:200', ['nn']],
      ['category', 'str:60'],
      ['body', 'longtext'],
      ['variables', 'json'],
      ['is_active', 'bool', ['def:1']],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },
  {
    name: 'issued_letters',
    label: 'نامه‌های صادرشده',
    module: 'requests',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int'],
      ['template_id', 'int'],
      ['title', 'str:200', ['nn']],
      ['number', 'str:60'],
      ['body', 'longtext'],
      ['issued_at', 'dt'],
      ['issued_by', 'int'],
      ['file', 'str:255'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id']],
  },
  {
    name: 'announcements',
    label: 'اطلاعیه‌ها',
    module: 'announcements',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['body', 'longtext'],
      ['audience', 'str:30', ['def:all']],
      ['department_id', 'int'],
      ['role_id', 'int'],
      ['publish_at', 'dt'],
      ['expire_at', 'dt'],
      ['is_pinned', 'bool'],
      ['attachment', 'str:255'],
      ['status', 'str:20', ['def:published']],
      ['views', 'int', ['def:0']],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['audience'], ['publish_at']],
  },
  {
    name: 'reminders',
    label: 'یادآورها',
    module: 'core',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40'],
      ['ref_type', 'str:60'],
      ['ref_id', 'int'],
      ['remind_at', 'dt'],
      ['channels', 'json'],
      ['recipients', 'json'],
      ['status', 'str:20', ['def:pending']],
      ['sent_at', 'dt'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['status'], ['remind_at']],
  },

  /* ======================= ارزیابی عملکرد و گزارش ======================= */
  {
    name: 'kpis',
    label: 'شاخص‌های عملکرد',
    module: 'performance',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['description', 'text'],
      ['department_id', 'int'],
      ['job_title_id', 'int'],
      ['weight', 'int', ['def:1']],
      ['target', 'str:120'],
      ['unit', 'str:40'],
      ['period', 'str:30', ['def:quarterly']],
      ['status', 'str:20', ['def:active']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['department_id'], ['period']],
  },
  {
    name: 'performance_reviews',
    label: 'ارزیابی‌های عملکرد',
    module: 'performance',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['period_label', 'str:60', ['nn']],
      ['review_date', 'date'],
      ['reviewer_user_id', 'int'],
      ['type', 'str:30', ['def:manager']],
      ['status', 'str:30', ['def:draft']],
      ['overall_score', 'float'],
      ['summary', 'text'],
      ['strengths', 'text'],
      ['improvements', 'text'],
      ['goals', 'json'],
      ['employee_comment', 'text'],
      ['acknowledged_at', 'dt'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['employee_id'], ['period_label'], ['status']],
  },
  {
    name: 'review_items',
    label: 'ردیف‌های ارزیابی',
    module: 'performance',
    cols: [
      ['id', 'id'],
      ['review_id', 'int', ['nn']],
      ['kpi_id', 'int'],
      ['title', 'str:200'],
      ['weight', 'float'],
      ['score', 'float'],
      ['max_score', 'float', ['def:5']],
      ['comment', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['review_id']],
  },
  {
    name: 'saved_reports',
    label: 'گزارش‌های ذخیره‌شده',
    module: 'reports',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:60'],
      ['params', 'json'],
      ['owner_user_id', 'int'],
      ['is_shared', 'bool', ['def:1']],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['owner_user_id']],
  },
  {
    name: 'sms_logs',
    label: 'گزارش پیامک',
    module: 'messaging',
    cols: [
      ['id', 'id'],
      ['mobile', 'str:20', ['nn']],
      ['type', 'str:30', ['def:text']],
      ['template_key', 'str:60'],
      ['body', 'text'],
      ['ref_type', 'str:60'],
      ['ref_id', 'int'],
      ['status', 'str:20', ['def:sent']],
      ['provider_id', 'str:120'],
      ['cost', 'money'],
      ['error', 'text'],
      ['sent_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['mobile'], ['status'], ['ref_type']],
  },
  {
    name: 'message_templates',
    label: 'قالب‌های پیام',
    module: 'messaging',
    cols: [
      ['id', 'id'],
      ['mkey', 'str:60', ['nn', 'u']],
      ['title', 'str:200'],
      ['channel', 'str:20', ['def:sms']],
      ['body', 'longtext'],
      ['provider_pattern', 'str:60'],
      ['variables', 'json'],
      ['is_active', 'bool', ['def:1']],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
  },

  /* =============================== شغل‌یابی =============================== */
  {
    name: 'career_pages',
    label: 'صفحه فرصت‌های شغلی',
    module: 'recruitment',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['intro', 'text'],
      ['about', 'text'],
      ['contact_email', 'str:150'],
      ['contact_phone', 'str:30'],
      ['address', 'text'],
      ['is_active', 'bool', ['def:1']],
      ['updated_at', 'dt'],
      ['created_at', 'dt', ['nn']],
    ],
  },
  {
    name: 'onboarding_kit_items',
    label: 'اقلام تحویلی بدو ورود',
    module: 'onboarding',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['type', 'str:40', ['def:equipment']],
      ['department_id', 'int'],
      ['quantity', 'int', ['def:1']],
      ['note', 'text'],
      ['status', 'str:20', ['def:active']],
      ['created_at', 'dt', ['nn']],
    ],
  },
  {
    name: 'employee_kits',
    label: 'اقلام تحویلی کارمند',
    module: 'onboarding',
    cols: [
      ['id', 'id'],
      ['employee_id', 'int', ['nn']],
      ['item_id', 'int'],
      ['title', 'str:200'],
      ['quantity', 'int', ['def:1']],
      ['delivered', 'bool', ['def:1']],
      ['delivered_at', 'dt'],
      ['delivered_by', 'int'],
      ['note', 'text'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id']],
  },

  {
    name: 'transport_costs',
    label: 'هزینه‌های سرویس',
    module: 'transport',
    cols: [
      ['id', 'id'],
      ['route_id', 'int'],
      ['vehicle_id', 'int'],
      ['period_month', 'str:7'],
      ['category', 'str:40', ['def:fuel']],
      ['title', 'str:150', ['nn']],
      ['amount', 'money'],
      ['qty', 'float'],
      ['unit', 'str:30'],
      ['vendor', 'str:120'],
      ['spent_on', 'date'],
      ['odometer', 'int'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['period_month'], ['category'], ['vehicle_id']],
  },
  {
    name: 'gate_passes',
    label: 'مجوز خروج کالا',
    module: 'security',
    cols: [
      ['id', 'id'],
      ['number', 'str:40'],
      ['type', 'str:30', ['def:exit']],
      ['employee_id', 'int'],
      ['carrier_name', 'str:150'],
      ['plate_no', 'str:30'],
      ['items', 'json'],
      ['purpose', 'str:255'],
      ['destination', 'str:150'],
      ['exit_at', 'dt'],
      ['return_at', 'dt'],
      ['status', 'str:30', ['def:pending']],
      ['approved_by', 'int'],
      ['guard_employee_id', 'int'],
      ['file', 'str:255'],
      ['note', 'text'],
      ['created_by', 'int'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['status'], ['exit_at']],
  },
  {
    name: 'exit_interviews',
    label: 'مصاحبه‌های پایانی',
    module: 'offboarding',
    cols: [
      ['id', 'id'],
      ['offboarding_id', 'int'],
      ['employee_id', 'int', ['nn']],
      ['interviewer_id', 'int'],
      ['interview_date', 'date'],
      ['reason_category', 'str:60'],
      ['satisfaction', 'int'],
      ['would_recommend', 'bool'],
      ['pros', 'text'],
      ['cons', 'text'],
      ['suggestions', 'text'],
      ['notes', 'text'],
      ['file', 'str:255'],
      ['created_at', 'dt', ['nn']],
    ],
    indexes: [['employee_id']],
  },
  {
    name: 'company_capital',
    label: 'سرمایه شرکت',
    module: 'shareholders',
    cols: [
      ['id', 'id'],
      ['year', 'int', ['nn']],
      ['capital_amount', 'money'],
      ['shares_total', 'big'],
      ['nominal_value', 'money'],
      ['increase_amount', 'money'],
      ['reg_no', 'str:60'],
      ['rdate', 'date'],
      ['note', 'text'],
      ['file', 'str:255'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['year']],
  },
  {
    name: 'tasks',
    label: 'کارها',
    module: 'announcements',
    cols: [
      ['id', 'id'],
      ['title', 'str:200', ['nn']],
      ['description', 'text'],
      ['assignee_user_id', 'int'],
      ['creator_user_id', 'int'],
      ['due_date', 'date'],
      ['priority', 'str:20', ['def:normal']],
      ['status', 'str:30', ['def:open']],
      ['related_type', 'str:60'],
      ['related_id', 'int'],
      ['completed_at', 'dt'],
      ['created_at', 'dt', ['nn']],
      ['updated_at', 'dt'],
    ],
    indexes: [['assignee_user_id'], ['status'], ['due_date']],
  },
];

module.exports = T;

