'use strict';
/**
 * تعریف منابع ماژول‌های عملیاتی، رفاهی، امور شرکت و امور اداری
 * (ایاب و ذهاب، آشپزخانه، نگهبانی، رفاهیات، مجوزها، مالکیت فکری، سهام،
 *  امور ثبتی، حقوقی، اموال، عملکرد، درخواست‌ها، اطلاعیه‌ها و پیامک)
 */
const db = require('../db');

const src = (sql) => () => sql;
const empSource = src(`SELECT id, full_name AS label FROM ${db.t('employees')} WHERE deleted_at IS NULL ORDER BY full_name`);
const locSource = src(`SELECT id, name AS label FROM ${db.t('locations')} ORDER BY name`);
const userSource = src(`SELECT id, full_name AS label FROM ${db.t('users')} WHERE status='active' ORDER BY full_name`);
const st = (options, extra = {}) => ({ name: 'status', label: 'وضعیت', type: 'select', options, group: 'وضعیت', col: 4, ...extra });

module.exports = [
  /* ============================== ایاب و ذهاب ============================== */
  {
    key: 'transport-vehicles', module: 'transport', table: 'transport_vehicles', basePath: 'transport/vehicles',
    title: 'خودروها و رانندگان', titleSingular: 'خودرو', icon: 'truck',
    perm: { view: 'transport.view', create: 'transport.vehicles.manage', edit: 'transport.vehicles.manage', delete: 'transport.vehicles.manage', export: 'transport.export' },
    search: ['plate_no', 'title', 'driver_name', 'model'], orderBy: 'id DESC',
    listColumns: [
      { field: 'plate_no', label: 'پلاک' }, { field: 'title', label: 'عنوان' }, { field: 'type', label: 'نوع' },
      { field: 'capacity', label: 'ظرفیت' }, { field: 'driver_name', label: 'راننده' }, { field: 'driver_mobile', label: 'موبایل راننده' },
      { field: 'insurance_expiry', label: 'انقضای بیمه', type: 'date' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'plate_no', label: 'شماره پلاک', type: 'text', required: true, group: 'مشخصات خودرو', col: 4 },
      { name: 'title', label: 'عنوان/مدل خودرو', type: 'text', group: 'مشخصات خودرو', col: 4 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'bus', label: 'اتوبوس' }, { value: 'minibus', label: 'مینی‌بوس' }, { value: 'van', label: 'ون' }, { value: 'car', label: 'سواری' }, { value: 'pickup', label: 'وانت' }], group: 'مشخصات خودرو', col: 4 },
      { name: 'capacity', label: 'ظرفیت سرنشین', type: 'number', group: 'مشخصات خودرو', col: 3 },
      { name: 'model', label: 'مدل', type: 'text', group: 'مشخصات خودرو', col: 3 },
      { name: 'year_made', label: 'سال ساخت', type: 'number', group: 'مشخصات خودرو', col: 3 },
      { name: 'odometer', label: 'کارکرد (کیلومتر)', type: 'number', group: 'مشخصات خودرو', col: 3 },
      { name: 'own_vehicle', label: 'ملکی شرکت', type: 'checkbox', checkLabel: 'خودرو ملکی است (در غیر این صورت استیجاری)', group: 'مالکیت', col: 4 },
      { name: 'vendor', label: 'پیمانکار / مالک', type: 'text', group: 'مالکیت', col: 4 },
      { name: 'fuel_type', label: 'نوع سوخت', type: 'select', options: ['بنزین', 'گازوئیل', 'دوگانه‌سوز', 'برقی'], group: 'مالکیت', col: 4 },
      { name: 'driver_employee_id', label: 'راننده (کارمند)', type: 'lookup', source: empSource, group: 'راننده', col: 4 },
      { name: 'driver_name', label: 'نام راننده', type: 'text', group: 'راننده', col: 4 },
      { name: 'driver_mobile', label: 'موبایل راننده', type: 'text', group: 'راننده', col: 4, dir: 'ltr' },
      { name: 'insurance_expiry', label: 'انقضای بیمه', type: 'date', group: 'اعتبار و سرویس', col: 4 },
      { name: 'technical_expiry', label: 'انقضای معاینه فنی', type: 'date', group: 'اعتبار و سرویس', col: 4 },
      { name: 'last_service_date', label: 'تاریخ آخرین سرویس', type: 'date', group: 'اعتبار و سرویس', col: 4 },
      st([{ value: 'active', label: 'فعال' }, { value: 'repair', label: 'در تعمیرگاه' }, { value: 'inactive', label: 'غیرفعال' }, { value: 'sold', label: 'فروخته‌شده' }]),
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'transport-routes', module: 'transport', table: 'transport_routes', basePath: 'transport/routes',
    title: 'مسیرهای سرویس', titleSingular: 'مسیر', icon: 'route',
    perm: { view: 'transport.view', create: 'transport.routes.manage', edit: 'transport.routes.manage', delete: 'transport.routes.manage' },
    search: ['name', 'code', 'driver_name'],
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['active', 'inactive'] }],
    listColumns: [
      { field: 'code', label: 'کد' }, { field: 'name', label: 'نام مسیر' },
      { field: 'vehicle_id', label: 'خودرو' }, { field: 'driver_name', label: 'راننده' },
      { field: 'capacity', label: 'ظرفیت' }, { field: 'departure_time', label: 'ساعت حرکت' },
      { field: 'monthly_fee', label: 'هزینه ماهانه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'name', label: 'نام مسیر', type: 'text', required: true, group: 'مشخصات مسیر', col: 6 },
      { name: 'code', label: 'کد مسیر', type: 'text', group: 'مشخصات مسیر', col: 6 },
      { name: 'vehicle_id', label: 'خودرو', type: 'lookup', source: src(`SELECT id, plate_no AS label FROM ${db.t('transport_vehicles')} WHERE deleted_at IS NULL ORDER BY plate_no`), group: 'خودرو و راننده', col: 4 },
      { name: 'driver_employee_id', label: 'راننده (کارمند)', type: 'lookup', source: empSource, group: 'خودرو و راننده', col: 4 },
      { name: 'driver_name', label: 'نام راننده', type: 'text', group: 'خودرو و راننده', col: 4 },
      { name: 'driver_mobile', label: 'موبایل راننده', type: 'text', group: 'خودرو و راننده', col: 4, dir: 'ltr' },
      { name: 'supervisor_name', label: 'سرپرست سرویس', type: 'text', group: 'خودرو و راننده', col: 4 },
      { name: 'capacity', label: 'ظرفیت', type: 'number', group: 'زمان‌بندی', col: 3 },
      { name: 'shift_name', label: 'شیفت', type: 'text', group: 'زمان‌بندی', col: 3 },
      { name: 'departure_time', label: 'ساعت حرکت', type: 'text', group: 'زمان‌بندی', col: 3, dir: 'ltr', placeholder: '06:45' },
      { name: 'return_time', label: 'ساعت بازگشت', type: 'text', group: 'زمان‌بندی', col: 3, dir: 'ltr', placeholder: '17:15' },
      { name: 'direction', label: 'جهت سرویس', type: 'select', options: [{ value: 'both', label: 'رفت و برگشت' }, { value: 'outbound', label: 'فقط رفت' }, { value: 'inbound', label: 'فقط برگشت' }], group: 'زمان‌بندی', col: 4 },
      { name: 'days_of_week', label: 'روزهای هفته', type: 'checkbox_group', options: ['شنبه', 'یک‌شنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنج‌شنبه', 'جمعه'], group: 'زمان‌بندی', col: 8 },
      { name: 'monthly_fee', label: 'هزینه ماهانه هر نفر', type: 'money', group: 'مالی', col: 4 },
      st([{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }]),
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'transport-stops', module: 'transport', table: 'transport_stops', basePath: 'transport/stops',
    title: 'ایستگاه‌های سرویس', titleSingular: 'ایستگاه', icon: 'pin',
    perm: { view: 'transport.view', create: 'transport.routes.manage', edit: 'transport.routes.manage', delete: 'transport.routes.manage' },
    search: ['title', 'address', 'landmark'], orderBy: 'route_id ASC, sort_order ASC',
    listColumns: [{ field: 'route_id', label: 'مسیر' }, { field: 'title', label: 'ایستگاه' }, { field: 'landmark', label: 'نشانه' }, { field: 'pickup_time', label: 'ساعت سوار شدن' }, { field: 'dropoff_time', label: 'ساعت پیاده شدن' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'route_id', label: 'مسیر', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('transport_routes')} WHERE deleted_at IS NULL ORDER BY name`), group: 'مشخصات', col: 6 },
      { name: 'title', label: 'نام ایستگاه', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'landmark', label: 'نشانه / نقطه شاخص', type: 'text', group: 'موقعیت', col: 6 },
      { name: 'address', label: 'نشانی', type: 'textarea', group: 'موقعیت' },
      { name: 'lat', label: 'عرض جغرافیایی', type: 'text', group: 'موقعیت', col: 3, dir: 'ltr' },
      { name: 'lng', label: 'طول جغرافیایی', type: 'text', group: 'موقعیت', col: 3, dir: 'ltr' },
      { name: 'pickup_time', label: 'ساعت سوار شدن', type: 'text', group: 'زمان', col: 3, dir: 'ltr' },
      { name: 'dropoff_time', label: 'ساعت پیاده شدن', type: 'text', group: 'زمان', col: 3, dir: 'ltr' },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'زمان', col: 3 },
      st([{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }], { col: 3 }),
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'transport-subscriptions', module: 'transport', table: 'transport_subscriptions', basePath: 'transport/subscriptions',
    title: 'تخصیص سرویس به کارکنان', titleSingular: 'اشتراک سرویس', icon: 'user-check',
    perm: { view: 'transport.view', create: 'transport.subscriptions.manage', edit: 'transport.subscriptions.manage', delete: 'transport.subscriptions.manage' },
    orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['requested', 'approved', 'rejected', 'active', 'suspended'] }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'route_id', label: 'مسیر' }, { field: 'stop_id', label: 'ایستگاه' },
      { field: 'from_date', label: 'از', type: 'date' }, { field: 'to_date', label: 'تا', type: 'date' },
      { field: 'fee', label: 'هزینه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'تخصیص', col: 6 },
      { name: 'route_id', label: 'مسیر', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('transport_routes')} WHERE deleted_at IS NULL ORDER BY name`), group: 'تخصیص', col: 6 },
      { name: 'stop_id', label: 'ایستگاه سوار شدن', type: 'lookup', source: src(`SELECT id, title AS label FROM ${db.t('transport_stops')} ORDER BY route_id, sort_order`), group: 'تخصیص', col: 6 },
      { name: 'direction', label: 'جهت', type: 'select', options: [{ value: 'both', label: 'رفت و برگشت' }, { value: 'outbound', label: 'فقط رفت' }, { value: 'inbound', label: 'فقط برگشت' }], group: 'تخصیص', col: 6 },
      { name: 'from_date', label: 'از تاریخ', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'to_date', label: 'تا تاریخ', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'fee', label: 'هزینه ماهانه', type: 'money', group: 'اعتبار', col: 4 },
      { name: 'days_of_week', label: 'روزهای استفاده', type: 'checkbox_group', options: ['شنبه', 'یک‌شنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنج‌شنبه', 'جمعه'], group: 'زمان‌بندی', col: 12 },
      st([{ value: 'requested', label: 'درخواست‌شده' }, { value: 'approved', label: 'تأییدشده' }, { value: 'active', label: 'فعال' }, { value: 'suspended', label: 'معلق' }, { value: 'rejected', label: 'رد شده' }]),
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'transport-trips', module: 'transport', table: 'transport_trips', basePath: 'transport/trips',
    title: 'گزارش سفرهای سرویس', titleSingular: 'سفر', icon: 'map-pin',
    perm: { view: 'transport.view', create: 'transport.trips.manage', edit: 'transport.trips.manage', delete: 'transport.trips.manage', export: 'transport.export' },
    orderBy: 'trip_date DESC, id DESC',
    filters: [{ name: 'trip_date', label: 'تاریخ سفر', type: 'date_range' }],
    listColumns: [
      { field: 'trip_date', label: 'تاریخ', type: 'date' }, { field: 'route_id', label: 'مسیر' },
      { field: 'direction', label: 'جهت' }, { field: 'driver_name', label: 'راننده' },
      { field: 'passenger_count', label: 'تعداد مسافر' }, { field: 'capacity', label: 'ظرفیت' },
      { field: 'cost', label: 'هزینه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    sumFields: [{ field: 'cost', alias: 'cost_sum' }, { field: 'passenger_count', alias: 'pax_sum' }],
    fields: [
      { name: 'route_id', label: 'مسیر', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('transport_routes')} WHERE deleted_at IS NULL ORDER BY name`), group: 'سفر', col: 6 },
      { name: 'vehicle_id', label: 'خودرو', type: 'lookup', source: src(`SELECT id, plate_no AS label FROM ${db.t('transport_vehicles')} WHERE deleted_at IS NULL ORDER BY plate_no`), group: 'سفر', col: 6 },
      { name: 'trip_date', label: 'تاریخ سفر', type: 'date', required: true, group: 'سفر', col: 4 },
      { name: 'direction', label: 'جهت', type: 'select', options: [{ value: 'outbound', label: 'رفت' }, { value: 'inbound', label: 'برگشت' }], group: 'سفر', col: 4 },
      st([{ value: 'scheduled', label: 'برنامه‌ریزی‌شده' }, { value: 'done', label: 'انجام‌شده' }, { value: 'canceled', label: 'لغو شده' }]),
      { name: 'driver_employee_id', label: 'راننده (کارمند)', type: 'lookup', source: empSource, group: 'راننده و زمان', col: 4 },
      { name: 'driver_name', label: 'نام راننده', type: 'text', group: 'راننده و زمان', col: 4 },
      { name: 'departed_at', label: 'ساعت حرکت', type: 'text', group: 'راننده و زمان', col: 2, dir: 'ltr' },
      { name: 'arrived_at', label: 'ساعت رسیدن', type: 'text', group: 'راننده و زمان', col: 2, dir: 'ltr' },
      { name: 'passenger_count', label: 'تعداد مسافر', type: 'number', group: 'آمار', col: 3 },
      { name: 'capacity', label: 'ظرفیت خودرو', type: 'number', group: 'آمار', col: 3 },
      { name: 'odometer_start', label: 'کیلومتر شروع', type: 'number', group: 'آمار', col: 3 },
      { name: 'odometer_end', label: 'کیلومتر پایان', type: 'number', group: 'آمار', col: 3 },
      { name: 'cost', label: 'هزینه سفر', type: 'money', group: 'مالی', col: 6 },
      { name: 'incident', label: 'رخداد / مشکل', type: 'textarea', group: 'تکمیلی' },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'transport-costs', module: 'transport', table: 'transport_costs', basePath: 'transport/costs',
    title: 'هزینه‌های ایاب و ذهاب', titleSingular: 'هزینه', icon: 'wallet',
    perm: { view: 'transport.view', create: 'transport.costs.manage', edit: 'transport.costs.manage', delete: 'transport.costs.manage', export: 'transport.export' },
    search: ['title', 'vendor'], orderBy: 'spent_on DESC, id DESC',
    filters: [{ name: 'spent_on', label: 'تاریخ', type: 'date_range' }, { name: 'category', label: 'دسته', type: 'select', options: ['fuel', 'repair', 'insurance', 'toll', 'driver', 'rent', 'other'] }],
    listColumns: [{ field: 'spent_on', label: 'تاریخ', type: 'date' }, { field: 'category', label: 'دسته' }, { field: 'title', label: 'عنوان' }, { field: 'vehicle_id', label: 'خودرو' }, { field: 'qty', label: 'مقدار' }, { field: 'amount', label: 'مبلغ', type: 'money' }, { field: 'vendor', label: 'پیمانکار' }],
    sumFields: [{ field: 'amount', alias: 'amount_sum' }],
    fields: [
      { name: 'title', label: 'عنوان هزینه', type: 'text', required: true, group: 'هزینه', col: 6 },
      { name: 'category', label: 'دسته', type: 'select', options: [{ value: 'fuel', label: 'سوخت' }, { value: 'repair', label: 'تعمیر و نگهداری' }, { value: 'insurance', label: 'بیمه' }, { value: 'toll', label: 'عوارض و جریمه' }, { value: 'driver', label: 'حقوق راننده' }, { value: 'rent', label: 'اجاره خودرو' }, { value: 'other', label: 'سایر' }], group: 'هزینه', col: 6 },
      { name: 'amount', label: 'مبلغ', type: 'money', required: true, group: 'هزینه', col: 4 },
      { name: 'spent_on', label: 'تاریخ هزینه', type: 'date', group: 'هزینه', col: 4 },
      { name: 'period_month', label: 'ماه مالی', type: 'text', group: 'هزینه', col: 4, dir: 'ltr', placeholder: '1404/07' },
      { name: 'vehicle_id', label: 'خودرو', type: 'lookup', source: src(`SELECT id, plate_no AS label FROM ${db.t('transport_vehicles')} WHERE deleted_at IS NULL ORDER BY plate_no`), group: 'مرجع', col: 4 },
      { name: 'route_id', label: 'مسیر', type: 'lookup', source: src(`SELECT id, name AS label FROM ${db.t('transport_routes')} WHERE deleted_at IS NULL ORDER BY name`), group: 'مرجع', col: 4 },
      { name: 'odometer', label: 'کارکرد (کیلومتر)', type: 'number', group: 'مرجع', col: 4 },
      { name: 'qty', label: 'مقدار', type: 'number', group: 'تکمیلی', col: 4 },
      { name: 'unit', label: 'واحد', type: 'text', group: 'تکمیلی', col: 4 },
      { name: 'vendor', label: 'پیمانکار / فروشنده', type: 'text', group: 'تکمیلی', col: 4 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },

  /* =============================== آشپزخانه =============================== */
  {
    key: 'meal-plans', module: 'kitchen', table: 'meal_plans', basePath: 'kitchen/plans',
    title: 'طرح‌های تغذیه', titleSingular: 'طرح', icon: 'utensils',
    perm: { view: 'kitchen.view', create: 'kitchen.menus.manage', edit: 'kitchen.menus.manage', delete: 'kitchen.menus.manage' },
    orderBy: 'id DESC',
    listColumns: [{ field: 'title', label: 'عنوان طرح' }, { field: 'from_date', label: 'از', type: 'date' }, { field: 'to_date', label: 'تا', type: 'date' }, { field: 'unit_price', label: 'قیمت هر وعده', type: 'money' }, { field: 'subsidy', label: 'یارانه شرکت', type: 'money' }, { field: 'is_active', label: 'فعال', type: 'checkbox' }],
    fields: [
      { name: 'title', label: 'عنوان طرح', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'طرح جاری است', group: 'مشخصات', col: 6 },
      { name: 'from_date', label: 'از تاریخ', type: 'date', group: 'بازه', col: 4 },
      { name: 'to_date', label: 'تا تاریخ', type: 'date', group: 'بازه', col: 4 },
      { name: 'unit_price', label: 'قیمت تمام‌شده هر وعده', type: 'money', group: 'بازه', col: 4 },
      { name: 'subsidy', label: 'یارانه شرکت برای هر وعده', type: 'money', group: 'مالی', col: 4 },
      { name: 'guest_price', label: 'قیمت مهمان', type: 'money', group: 'مالی', col: 4 },
      { name: 'meal_types', label: 'وعده‌ها', type: 'checkbox_group', options: ['صبحانه', 'نهار', 'شام', 'میان‌وعده'], group: 'مالی', col: 4 },
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'kitchen-menus', module: 'kitchen', table: 'kitchen_menus', basePath: 'kitchen/menus',
    title: 'برنامه غذایی روزانه', titleSingular: 'منوی روز', icon: 'chef',
    perm: { view: 'kitchen.view', create: 'kitchen.menus.manage', edit: 'kitchen.menus.manage', delete: 'kitchen.menus.manage' },
    search: ['title', 'description'], orderBy: 'menu_date DESC, id DESC',
    filters: [{ name: 'menu_date', label: 'تاریخ', type: 'date_range' }, { name: 'meal_type', label: 'وعده', type: 'select', options: ['breakfast', 'lunch', 'dinner', 'snack'] }],
    listColumns: [
      { field: 'menu_date', label: 'تاریخ', type: 'date' }, { field: 'meal_type', label: 'وعده' }, { field: 'title', label: 'عنوان غذا' },
      { field: 'cost', label: 'هزینه هر پرس', type: 'money' }, { field: 'capacity', label: 'ظرفیت' },
      { field: 'reserved_count', label: 'رزرو' }, { field: 'served_count', label: 'سروشده' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'menu_date', label: 'تاریخ', type: 'date', required: true, group: 'منو', col: 4 },
      { name: 'meal_type', label: 'وعده', type: 'select', options: [{ value: 'breakfast', label: 'صبحانه' }, { value: 'lunch', label: 'نهار' }, { value: 'dinner', label: 'شام' }, { value: 'snack', label: 'میان‌وعده' }], group: 'منو', col: 4 },
      { name: 'title', label: 'عنوان غذا', type: 'text', required: true, group: 'منو', col: 4 },
      { name: 'items', label: 'اجزای غذا (هر خط یک مورد)', type: 'textarea', group: 'منو', rows: 4 },
      { name: 'description', label: 'توضیحات / ارزش غذایی', type: 'textarea', group: 'منو' },
      { name: 'cost', label: 'هزینه هر پرس', type: 'money', group: 'ظرفیت', col: 4 },
      { name: 'capacity', label: 'ظرفیت', type: 'number', group: 'ظرفیت', col: 4 },
      { name: 'plan_id', label: 'طرح تغذیه', type: 'lookup', source: src(`SELECT id, title AS label FROM ${db.t('meal_plans')} ORDER BY id DESC`), group: 'ظرفیت', col: 4 },
      st([{ value: 'published', label: 'منتشر شده' }, { value: 'draft', label: 'پیش‌نویس' }, { value: 'closed', label: 'بسته‌شده' }], { col: 6 }),
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'meal-reservations', module: 'kitchen', table: 'meal_reservations', basePath: 'kitchen/reservations',
    title: 'رزرو و مصرف غذا', titleSingular: 'رزرو غذا', icon: 'coffee',
    perm: { view: 'kitchen.view', create: 'kitchen.reservation.manage', edit: 'kitchen.reservation.manage', delete: 'kitchen.reservation.manage', export: 'kitchen.export' },
    orderBy: 'meal_date DESC, id DESC',
    filters: [{ name: 'meal_date', label: 'تاریخ', type: 'date_range' }, { name: 'status', label: 'وضعیت', type: 'select', options: ['reserved', 'canceled', 'served', 'no_show'] }],
    listColumns: [
      { field: 'meal_date', label: 'تاریخ', type: 'date' }, { field: 'employee_id', label: 'کارمند' }, { field: 'meal_type', label: 'وعده' },
      { field: 'count', label: 'تعداد' }, { field: 'guest_count', label: 'مهمان' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    sumFields: [{ field: 'count', alias: 'count_sum' }, { field: 'guest_count', alias: 'guest_sum' }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'رزرو', col: 6 },
      { name: 'menu_id', label: 'منوی روز', type: 'lookup', required: true, source: src(`SELECT id, title AS label FROM ${db.t('kitchen_menus')} ORDER BY menu_date DESC LIMIT 200`), group: 'رزرو', col: 6 },
      { name: 'meal_date', label: 'تاریخ', type: 'date', group: 'رزرو', col: 4 },
      { name: 'meal_type', label: 'وعده', type: 'select', options: ['صبحانه', 'نهار', 'شام', 'میان‌وعده'], group: 'رزرو', col: 4 },
      { name: 'count', label: 'تعداد پرس', type: 'number', group: 'رزرو', col: 2 },
      { name: 'guest_count', label: 'تعداد مهمان', type: 'number', group: 'رزرو', col: 2 },
      st([{ value: 'reserved', label: 'رزرو شده' }, { value: 'served', label: 'سرو شده' }, { value: 'canceled', label: 'لغو شده' }, { value: 'no_show', label: 'عدم حضور' }], { col: 6 }),
      { name: 'cancel_reason', label: 'علت لغو', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'kitchen-inventory', module: 'kitchen', table: 'kitchen_inventory', basePath: 'kitchen/inventory',
    title: 'انبار آشپزخانه', titleSingular: 'قلم انبار', icon: 'box',
    perm: { view: 'kitchen.view', create: 'kitchen.inventory.manage', edit: 'kitchen.inventory.manage', delete: 'kitchen.inventory.manage' },
    search: ['title', 'category'], orderBy: 'title ASC',
    listColumns: [{ field: 'title', label: 'کالا' }, { field: 'category', label: 'دسته' }, { field: 'qty', label: 'موجودی' }, { field: 'unit', label: 'واحد' }, { field: 'min_qty', label: 'حد سفارش' }, { field: 'unit_price', label: 'قیمت واحد', type: 'money' }, { field: 'expiry_date', label: 'انقضا', type: 'date' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'نام کالا', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'category', label: 'دسته', type: 'select', options: ['مواد اولیه', 'گوشت و مرغ', 'لبنیات', 'خشکبار', 'نوشیدنی', 'ظروف', 'شوینده', 'سایر'], group: 'مشخصات', col: 6 },
      { name: 'qty', label: 'موجودی', type: 'number', group: 'موجودی', col: 3 },
      { name: 'unit', label: 'واحد', type: 'text', group: 'موجودی', col: 3 },
      { name: 'min_qty', label: 'حد سفارش مجدد', type: 'number', group: 'موجودی', col: 3 },
      { name: 'unit_price', label: 'قیمت واحد', type: 'money', group: 'موجودی', col: 3 },
      { name: 'expiry_date', label: 'تاریخ انقضا', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'location', label: 'محل نگهداری', type: 'text', group: 'اعتبار', col: 4 },
      st([{ value: 'ok', label: 'عادی' }, { value: 'low', label: 'کمبود' }, { value: 'expired', label: 'منقضی' }], { col: 4 }),
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'kitchen-costs', module: 'kitchen', table: 'kitchen_costs', basePath: 'kitchen/costs',
    title: 'هزینه‌های آشپزخانه', titleSingular: 'هزینه', icon: 'wallet',
    perm: { view: 'kitchen.view', create: 'kitchen.costs.manage', edit: 'kitchen.costs.manage', delete: 'kitchen.costs.manage', export: 'kitchen.export' },
    search: ['title', 'vendor'], orderBy: 'spent_on DESC, id DESC',
    filters: [{ name: 'spent_on', label: 'تاریخ', type: 'date_range' }, { name: 'category', label: 'دسته', type: 'select', options: ['materials', 'salary', 'gas', 'equipment', 'other'] }],
    listColumns: [{ field: 'spent_on', label: 'تاریخ', type: 'date' }, { field: 'category', label: 'دسته' }, { field: 'title', label: 'عنوان' }, { field: 'qty', label: 'مقدار' }, { field: 'amount', label: 'مبلغ', type: 'money' }, { field: 'vendor', label: 'فروشنده' }],
    sumFields: [{ field: 'amount', alias: 'amount_sum' }],
    fields: [
      { name: 'title', label: 'عنوان هزینه', type: 'text', required: true, group: 'هزینه', col: 6 },
      { name: 'category', label: 'دسته', type: 'select', options: [{ value: 'materials', label: 'مواد اولیه' }, { value: 'salary', label: 'حقوق پرسنل آشپزخانه' }, { value: 'gas', label: 'گاز و انرژی' }, { value: 'equipment', label: 'تجهیزات' }, { value: 'other', label: 'سایر' }], group: 'هزینه', col: 6 },
      { name: 'amount', label: 'مبلغ', type: 'money', required: true, group: 'هزینه', col: 4 },
      { name: 'spent_on', label: 'تاریخ', type: 'date', group: 'هزینه', col: 4 },
      { name: 'period_month', label: 'ماه مالی', type: 'text', group: 'هزینه', col: 4, dir: 'ltr', placeholder: '1404/07' },
      { name: 'qty', label: 'مقدار', type: 'number', group: 'تکمیلی', col: 4 },
      { name: 'unit', label: 'واحد', type: 'text', group: 'تکمیلی', col: 4 },
      { name: 'vendor', label: 'فروشنده', type: 'text', group: 'تکمیلی', col: 4 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },

  /* ================================ نگهبانی ================================ */
  {
    key: 'security-posts', module: 'security', table: 'security_posts', basePath: 'security/posts',
    title: 'پست‌های نگهبانی', titleSingular: 'پست', icon: 'shield',
    perm: { view: 'security.view', create: 'security.shifts.manage', edit: 'security.shifts.manage', delete: 'security.shifts.manage' },
    search: ['title'], orderBy: 'id ASC',
    listColumns: [{ field: 'title', label: 'عنوان پست' }, { field: 'location_id', label: 'محل' }, { field: 'type', label: 'نوع' }, { field: 'required_guards', label: 'تعداد نگهبان' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'عنوان پست', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'location_id', label: 'محل استقرار', type: 'lookup', source: locSource, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع پست', type: 'select', options: [{ value: 'main_gate', label: 'درب ورودی اصلی' }, { value: 'side_gate', label: 'درب فرعی' }, { value: 'warehouse', label: 'انبار' }, { value: 'parking', label: 'پارکینگ' }, { value: 'control_room', label: 'اتاق کنترل' }, { value: 'patrol', label: 'گشت' }], group: 'مشخصات', col: 6 },
      { name: 'required_guards', label: 'تعداد نگهبان مورد نیاز', type: 'number', group: 'مشخصات', col: 6 },
      st([{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }], { col: 6 }),
      { name: 'instructions', label: 'دستورالعمل پست', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'security-shifts', module: 'security', table: 'security_shifts', basePath: 'security/shifts',
    title: 'شیفت‌های نگهبانی', titleSingular: 'شیفت نگهبانی', icon: 'clock',
    perm: { view: 'security.view', create: 'security.shifts.manage', edit: 'security.shifts.manage', delete: 'security.shifts.manage' },
    search: ['shift_name', 'guard_name'], orderBy: 'from_date DESC, id DESC',
    filters: [{ name: 'from_date', label: 'از تاریخ', type: 'date_range' }],
    listColumns: [
      { field: 'from_date', label: 'از', type: 'date' }, { field: 'to_date', label: 'تا', type: 'date' },
      { field: 'shift_name', label: 'شیفت' }, { field: 'start_time', label: 'شروع' }, { field: 'end_time', label: 'پایان' },
      { field: 'guard_name', label: 'نگهبان' }, { field: 'guard_mobile', label: 'موبایل' }, { field: 'location_id', label: 'محل' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'shift_name', label: 'نام شیفت', type: 'text', required: true, group: 'شیفت', col: 4 },
      { name: 'start_time', label: 'ساعت شروع', type: 'text', group: 'شیفت', col: 4, dir: 'ltr', placeholder: '06:00' },
      { name: 'end_time', label: 'ساعت پایان', type: 'text', group: 'شیفت', col: 4, dir: 'ltr', placeholder: '14:00' },
      { name: 'from_date', label: 'از تاریخ', type: 'date', group: 'بازه', col: 4 },
      { name: 'to_date', label: 'تا تاریخ', type: 'date', group: 'بازه', col: 4 },
      { name: 'day_of_week', label: 'روز هفته', type: 'select', options: ['شنبه', 'یک‌شنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنج‌شنبه', 'جمعه'], group: 'بازه', col: 4 },
      { name: 'location_id', label: 'محل', type: 'lookup', source: locSource, group: 'محل و پست', col: 4 },
      { name: 'post_id', label: 'پست', type: 'lookup', source: src(`SELECT id, title AS label FROM ${db.t('security_posts')} ORDER BY title`), group: 'محل و پست', col: 4 },
      st([{ value: 'active', label: 'فعال' }, { value: 'done', label: 'پایان‌یافته' }, { value: 'absent', label: 'عدم حضور' }], { col: 4 }),
      { name: 'guard_employee_id', label: 'نگهبان (کارمند)', type: 'lookup', source: empSource, group: 'نگهبان', col: 4 },
      { name: 'guard_name', label: 'نام نگهبان', type: 'text', group: 'نگهبان', col: 4 },
      { name: 'guard_mobile', label: 'موبایل نگهبان', type: 'text', group: 'نگهبان', col: 4, dir: 'ltr' },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'security-patrols', module: 'security', table: 'security_patrols', basePath: 'security/patrols',
    title: 'گزارش گشت و نگهبانی', titleSingular: 'گزارش گشت', icon: 'route',
    perm: { view: 'security.view', create: 'security.patrol.manage', edit: 'security.patrol.manage', delete: 'security.patrol.manage' },
    orderBy: 'patrol_date DESC, id DESC',
    filters: [{ name: 'patrol_date', label: 'تاریخ', type: 'date_range' }],
    listColumns: [
      { field: 'patrol_date', label: 'تاریخ', type: 'date' }, { field: 'shift_name', label: 'شیفت' },
      { field: 'guard_name', label: 'نگهبان' }, { field: 'start_at', label: 'شروع' }, { field: 'end_at', label: 'پایان' },
      { field: 'location_id', label: 'محل' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'patrol_date', label: 'تاریخ', type: 'date', required: true, group: 'گشت', col: 4 },
      { name: 'shift_name', label: 'شیفت', type: 'text', group: 'گشت', col: 4 },
      { name: 'location_id', label: 'محل', type: 'lookup', source: locSource, group: 'گشت', col: 4 },
      { name: 'guard_employee_id', label: 'نگهبان (کارمند)', type: 'lookup', source: empSource, group: 'نگهبان', col: 4 },
      { name: 'guard_name', label: 'نام نگهبان', type: 'text', group: 'نگهبان', col: 4 },
      { name: 'start_at', label: 'ساعت شروع گشت', type: 'text', group: 'نگهبان', col: 2, dir: 'ltr' },
      { name: 'end_at', label: 'ساعت پایان گشت', type: 'text', group: 'نگهبان', col: 2, dir: 'ltr' },
      { name: 'checkpoints', label: 'ایست‌های بازدیدشده (هر خط یک مورد)', type: 'textarea', group: 'گزارش', rows: 4 },
      { name: 'incidents', label: 'رخدادهای مشاهده‌شده', type: 'textarea', group: 'گزارش' },
      { name: 'handover_note', label: 'تحویل شیفت', type: 'textarea', group: 'گزارش' },
      st([{ value: 'submitted', label: 'ثبت‌شده' }, { value: 'reviewed', label: 'بررسی‌شده' }, { value: 'issue', label: 'دارای مشکل' }], { col: 6 }),
      { name: 'supervisor_note', label: 'یادداشت سرپرست', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'security-incidents', module: 'security', table: 'security_incidents', basePath: 'security/incidents',
    title: 'وقایع و حوادث امنیتی', titleSingular: 'رخداد', icon: 'alert-triangle',
    perm: { view: 'security.view', create: 'security.incident.manage', edit: 'security.incident.manage', delete: 'security.incident.manage' },
    search: ['title', 'description', 'person_involved'], orderBy: 'happened_at DESC, id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['open', 'investigating', 'closed'] }, { name: 'severity', label: 'شدت', type: 'select', options: ['low', 'medium', 'high', 'critical'] }],
    listColumns: [
      { field: 'happened_at', label: 'زمان', type: 'datetime' }, { field: 'title', label: 'عنوان' }, { field: 'type', label: 'نوع' },
      { field: 'severity', label: 'شدت', badge: true }, { field: 'location_id', label: 'محل' }, { field: 'person_involved', label: 'فرد مرتبط' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان رخداد', type: 'text', required: true, group: 'رخداد', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'theft', label: 'سرقت' }, { value: 'fire', label: 'آتش‌سوزی' }, { value: 'injury', label: 'حادثه جانی' }, { value: 'trespass', label: 'ورود غیرمجاز' }, { value: 'damage', label: 'خسارت اموال' }, { value: 'other', label: 'سایر' }], group: 'رخداد', col: 6 },
      { name: 'happened_at', label: 'زمان وقوع', type: 'datetime', group: 'رخداد', col: 4 },
      { name: 'severity', label: 'شدت', type: 'select', options: [{ value: 'low', label: 'کم' }, { value: 'medium', label: 'متوسط' }, { value: 'high', label: 'زیاد' }, { value: 'critical', label: 'بحرانی' }], group: 'رخداد', col: 4 },
      { name: 'location_id', label: 'محل وقوع', type: 'lookup', source: locSource, group: 'رخداد', col: 4 },
      { name: 'person_involved', label: 'فرد / خودروی مرتبط', type: 'text', group: 'جزئیات', col: 6 },
      { name: 'description', label: 'شرح رخداد', type: 'textarea', group: 'جزئیات' },
      { name: 'action_taken', label: 'اقدام انجام‌شده', type: 'textarea', group: 'جزئیات' },
      st([{ value: 'open', label: 'باز' }, { value: 'investigating', label: 'در حال بررسی' }, { value: 'closed', label: 'بسته‌شده' }], { col: 6 }),
      { name: 'attachment', label: 'پیوست (عکس/فیلم)', type: 'file', group: 'تکمیلی', col: 6 },
    ],
  },
  {
    key: 'visitors-log', module: 'security', table: 'visitors_log', basePath: 'security/visitors',
    title: 'دفتر ورود و خروج مهمان', titleSingular: 'مهمان', icon: 'user-check',
    perm: { view: 'security.view', create: 'security.visitors.manage', edit: 'security.visitors.manage', delete: 'security.visitors.manage', export: 'security.export' },
    search: ['visitor_name', 'mobile', 'company', 'vehicle_plate'], orderBy: 'id DESC',
    filters: [{ name: 'entry_at', label: 'تاریخ ورود', type: 'date_range' }],
    listColumns: [
      { field: 'visitor_name', label: 'نام مهمان' }, { field: 'mobile', label: 'موبایل' }, { field: 'company', label: 'شرکت' },
      { field: 'host_employee_id', label: 'میزبان' }, { field: 'purpose', label: 'هدف' }, { field: 'badge_no', label: 'کارت' },
      { field: 'entry_at', label: 'ورود', type: 'datetime' }, { field: 'exit_at', label: 'خروج', type: 'datetime' },
    ],
    fields: [
      { name: 'visitor_name', label: 'نام و نام خانوادگی مهمان', type: 'text', required: true, group: 'مهمان', col: 6 },
      { name: 'national_id', label: 'کد ملی', type: 'text', group: 'مهمان', col: 6 },
      { name: 'mobile', label: 'شماره تماس', type: 'text', group: 'مهمان', col: 6, dir: 'ltr' },
      { name: 'company', label: 'شرکت / سازمان', type: 'text', group: 'مهمان', col: 6 },
      { name: 'host_employee_id', label: 'میزبان', type: 'lookup', source: empSource, group: 'بازدید', col: 6 },
      { name: 'purpose', label: 'هدف بازدید', type: 'text', group: 'بازدید', col: 6 },
      { name: 'entry_at', label: 'زمان ورود', type: 'datetime', group: 'زمان', col: 6 },
      { name: 'exit_at', label: 'زمان خروج', type: 'datetime', group: 'زمان', col: 6 },
      { name: 'badge_no', label: 'شماره کارت ورود', type: 'text', group: 'تکمیلی', col: 4 },
      { name: 'vehicle_plate', label: 'پلاک خودرو', type: 'text', group: 'تکمیلی', col: 4 },
      { name: 'items_in', label: 'اقلام همراه', type: 'text', group: 'تکمیلی', col: 4 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'gate-passes', module: 'security', table: 'gate_passes', basePath: 'security/gate-passes',
    title: 'مجوز خروج کالا', titleSingular: 'مجوز خروج', icon: 'file-check',
    perm: { view: 'security.view', create: 'security.gatepass.manage', edit: 'security.gatepass.manage', delete: 'security.gatepass.manage' },
    search: ['number', 'carrier_name', 'purpose', 'plate_no'], orderBy: 'id DESC',
    listColumns: [
      { field: 'number', label: 'شماره مجوز' }, { field: 'type', label: 'نوع' }, { field: 'employee_id', label: 'تحویل‌دهنده' },
      { field: 'carrier_name', label: 'حامل' }, { field: 'plate_no', label: 'پلاک' }, { field: 'exit_at', label: 'زمان خروج', type: 'datetime' },
      { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'number', label: 'شماره مجوز', type: 'text', group: 'مجوز', col: 4 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'exit', label: 'خروج کالا' }, { value: 'return', label: 'بازگشت کالا' }, { value: 'repair', label: 'ارسال برای تعمیر' }, { value: 'scrap', label: 'اسقاط' }], group: 'مجوز', col: 4 },
      st([{ value: 'pending', label: 'در انتظار تأیید' }, { value: 'approved', label: 'تأییدشده' }, { value: 'exited', label: 'خارج شده' }, { value: 'returned', label: 'بازگشته' }, { value: 'rejected', label: 'رد شده' }], { col: 4 }),
      { name: 'employee_id', label: 'کارمند تحویل‌دهنده', type: 'lookup', source: empSource, group: 'طرفین', col: 6 },
      { name: 'carrier_name', label: 'نام حامل / راننده', type: 'text', group: 'طرفین', col: 6 },
      { name: 'plate_no', label: 'پلاک خودرو', type: 'text', group: 'خروج', col: 4 },
      { name: 'destination', label: 'مقصد', type: 'text', group: 'خروج', col: 4 },
      { name: 'exit_at', label: 'زمان خروج', type: 'datetime', group: 'خروج', col: 4 },
      { name: 'return_at', label: 'زمان بازگشت', type: 'datetime', group: 'خروج', col: 4 },
      { name: 'items', label: 'شرح اقلام (هر خط یک مورد)', type: 'textarea', group: 'اقلام', rows: 4 },
      { name: 'purpose', label: 'علت خروج', type: 'textarea', group: 'اقلام' },
      { name: 'guard_employee_id', label: 'نگهبان کنترل‌کننده', type: 'lookup', source: empSource, group: 'اقلام', col: 6 },
      { name: 'file', label: 'تصویر مجوز', type: 'file', group: 'تکمیلی', col: 6 },
    ],
  },

  /* ================================ رفاهیات ================================ */
  {
    key: 'welfare-facilities', module: 'welfare', table: 'welfare_facilities', basePath: 'welfare/facilities',
    title: 'امکانات رفاهی', titleSingular: 'امکان رفاهی', icon: 'sparkles',
    perm: { view: 'welfare.view', create: 'welfare.facilities.manage', edit: 'welfare.facilities.manage', delete: 'welfare.facilities.manage' },
    search: ['name', 'type'], orderBy: 'name ASC',
    listColumns: [{ field: 'name', label: 'نام' }, { field: 'type', label: 'نوع' }, { field: 'location_id', label: 'محل' }, { field: 'capacity', label: 'ظرفیت' }, { field: 'open_hours', label: 'ساعت کاری' }, { field: 'fee', label: 'هزینه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'name', label: 'نام امکان', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'gym', label: 'سالن ورزش' }, { value: 'library', label: 'کتابخانه' }, { value: 'rest', label: 'اتاق استراحت' }, { value: 'nursery', label: 'اتاق مادر و کودک' }, { value: 'locker', label: 'رختکن و کمد' }, { value: 'prayer', label: 'نمازخانه' }, { value: 'parking', label: 'پارکینگ' }, { value: 'hall', label: 'سالن اجتماعات' }, { value: 'clinic', label: 'درمانگاه' }], group: 'مشخصات', col: 6 },
      { name: 'location_id', label: 'محل استقرار', type: 'lookup', source: locSource, group: 'مشخصات', col: 4 },
      { name: 'capacity', label: 'ظرفیت', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'open_hours', label: 'ساعت کاری', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'fee', label: 'هزینه استفاده', type: 'money', group: 'مالی', col: 6 },
      st([{ value: 'active', label: 'فعال' }, { value: 'maintenance', label: 'در تعمیر' }, { value: 'inactive', label: 'غیرفعال' }], { col: 6 }),
      { name: 'rules', label: 'مقررات استفاده', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'facility-bookings', module: 'welfare', table: 'facility_bookings', basePath: 'welfare/bookings',
    title: 'رزرو امکانات رفاهی', titleSingular: 'رزرو', icon: 'calendar-check',
    perm: { view: 'welfare.view', create: 'welfare.facilities.manage', edit: 'welfare.facilities.manage', delete: 'welfare.facilities.manage' },
    orderBy: 'booking_date DESC, id DESC',
    filters: [{ name: 'booking_date', label: 'تاریخ', type: 'date_range' }, { name: 'status', label: 'وضعیت', type: 'select', options: ['pending', 'approved', 'rejected', 'done', 'canceled'] }],
    listColumns: [
      { field: 'booking_date', label: 'تاریخ', type: 'date' }, { field: 'facility_id', label: 'امکان' }, { field: 'employee_id', label: 'کارمند' },
      { field: 'from_time', label: 'از' }, { field: 'to_time', label: 'تا' }, { field: 'guests', label: 'مهمان' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'facility_id', label: 'امکان رفاهی', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('welfare_facilities')} ORDER BY name`), group: 'رزرو', col: 6 },
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'رزرو', col: 6 },
      { name: 'booking_date', label: 'تاریخ', type: 'date', group: 'زمان', col: 4 },
      { name: 'from_time', label: 'از ساعت', type: 'text', group: 'زمان', col: 4, dir: 'ltr' },
      { name: 'to_time', label: 'تا ساعت', type: 'text', group: 'زمان', col: 4, dir: 'ltr' },
      { name: 'guests', label: 'تعداد همراه', type: 'number', group: 'تکمیلی', col: 4 },
      st([{ value: 'pending', label: 'در انتظار' }, { value: 'approved', label: 'تأییدشده' }, { value: 'done', label: 'انجام‌شده' }, { value: 'canceled', label: 'لغو شده' }, { value: 'rejected', label: 'رد شده' }], { col: 8 }),
      { name: 'purpose', label: 'هدف استفاده', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'welfare-requests', module: 'welfare', table: 'welfare_requests', basePath: 'welfare/requests',
    title: 'درخواست‌های رفاهی', titleSingular: 'درخواست رفاهی', icon: 'heart',
    perm: { view: 'welfare.view', create: 'welfare.request.create', edit: 'welfare.requests.manage', delete: 'welfare.requests.manage' },
    search: ['title', 'description'], orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['pending', 'approved', 'rejected', 'done'] }, { name: 'type', label: 'نوع', type: 'select', options: ['transport', 'meal', 'facility', 'loan', 'insurance', 'gift', 'other'] }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'type', label: 'نوع' }, { field: 'title', label: 'عنوان' },
      { field: 'amount', label: 'مبلغ', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'درخواست', col: 6 },
      { name: 'type', label: 'نوع درخواست', type: 'select', options: [{ value: 'transport', label: 'ایاب و ذهاب' }, { value: 'meal', label: 'تغذیه' }, { value: 'facility', label: 'امکانات رفاهی' }, { value: 'loan', label: 'وام و مساعده' }, { value: 'insurance', label: 'بیمه تکمیلی' }, { value: 'gift', label: 'هدیه و مناسبت' }, { value: 'other', label: 'سایر' }], group: 'درخواست', col: 6 },
      { name: 'title', label: 'عنوان', type: 'text', required: true, group: 'درخواست', col: 8 },
      { name: 'amount', label: 'مبلغ درخواستی', type: 'money', group: 'درخواست', col: 4 },
      { name: 'description', label: 'شرح درخواست', type: 'textarea', group: 'جزئیات' },
      st([{ value: 'pending', label: 'در انتظار' }, { value: 'approved', label: 'تأییدشده' }, { value: 'done', label: 'انجام‌شده' }, { value: 'rejected', label: 'رد شده' }], { col: 6 }),
      { name: 'decision_note', label: 'یادداشت تصمیم', type: 'textarea', group: 'جزئیات' },
    ],
  },
  {
    key: 'welfare-events', module: 'welfare', table: 'welfare_events', basePath: 'welfare/events',
    title: 'اردوها و رویدادهای رفاهی', titleSingular: 'رویداد', icon: 'gift',
    perm: { view: 'welfare.view', create: 'welfare.events.manage', edit: 'welfare.events.manage', delete: 'welfare.events.manage' },
    search: ['title', 'location'], orderBy: 'start_date DESC',
    listColumns: [{ field: 'start_date', label: 'تاریخ', type: 'date' }, { field: 'title', label: 'عنوان' }, { field: 'type', label: 'نوع' }, { field: 'location', label: 'محل' }, { field: 'budget', label: 'بودجه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'عنوان رویداد', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'event', label: 'جشن و مراسم' }, { value: 'trip', label: 'اردو و سفر' }, { value: 'celebration', label: 'مناسبت' }, { value: 'gift', label: 'هدیه' }, { value: 'sport', label: 'ورزشی' }, { value: 'cultural', label: 'فرهنگی' }], group: 'مشخصات', col: 6 },
      { name: 'start_date', label: 'تاریخ شروع', type: 'date', group: 'زمان و مکان', col: 4 },
      { name: 'end_date', label: 'تاریخ پایان', type: 'date', group: 'زمان و مکان', col: 4 },
      { name: 'location', label: 'محل برگزاری', type: 'text', group: 'زمان و مکان', col: 4 },
      { name: 'budget', label: 'بودجه مصوب', type: 'money', group: 'مالی', col: 4 },
      { name: 'cost', label: 'هزینه واقعی', type: 'money', group: 'مالی', col: 4 },
      st([{ value: 'planned', label: 'برنامه‌ریزی‌شده' }, { value: 'done', label: 'برگزار شده' }, { value: 'canceled', label: 'لغو شده' }], { col: 4 }),
      { name: 'organizer', label: 'برگزارکننده', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'welfare-insurance', module: 'welfare', table: 'welfare_insurance', basePath: 'welfare/insurance',
    title: 'بیمه تکمیلی کارکنان', titleSingular: 'بیمه تکمیلی', icon: 'shield-plus',
    perm: { view: 'welfare.view', create: 'welfare.insurance.manage', edit: 'welfare.insurance.manage', delete: 'welfare.insurance.manage' },
    search: ['policy_no', 'insurer'], orderBy: 'id DESC',
    listColumns: [{ field: 'employee_id', label: 'کارمند' }, { field: 'insurer', label: 'بیمه‌گر' }, { field: 'policy_no', label: 'شماره بیمه‌نامه' }, { field: 'type', label: 'نوع' }, { field: 'start_date', label: 'شروع', type: 'date' }, { field: 'end_date', label: 'پایان', type: 'date' }, { field: 'premium', label: 'حق بیمه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'بیمه‌نامه', col: 6 },
      { name: 'insurer', label: 'شرکت بیمه', type: 'text', group: 'بیمه‌نامه', col: 6 },
      { name: 'policy_no', label: 'شماره بیمه‌نامه', type: 'text', group: 'بیمه‌نامه', col: 4 },
      { name: 'type', label: 'نوع بیمه', type: 'select', options: [{ value: 'health', label: 'درمان تکمیلی' }, { value: 'life', label: 'عمر و حادثه' }, { value: 'travel', label: 'سفر' }, { value: 'dental', label: 'دندان‌پزشکی' }], group: 'بیمه‌نامه', col: 4 },
      { name: 'start_date', label: 'تاریخ شروع', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'end_date', label: 'تاریخ پایان', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'premium', label: 'حق بیمه پرداختی', type: 'money', group: 'اعتبار', col: 4 },
      { name: 'coverage', label: 'سقف پوشش', type: 'text', group: 'اعتبار', col: 4 },
      { name: 'dependents', label: 'افراد تحت پوشش (هر خط یک نفر)', type: 'textarea', group: 'پوشش' },
      st([{ value: 'active', label: 'فعال' }, { value: 'expired', label: 'منقضی' }, { value: 'canceled', label: 'لغو شده' }], { col: 6 }),
      { name: 'file', label: 'فایل بیمه‌نامه', type: 'file', group: 'تکمیلی', col: 6 },
    ],
  },

  /* ============================= مجوزها و دانش‌بنیان ============================= */
  {
    key: 'licenses', module: 'licensing', table: 'licenses', basePath: 'licensing/list',
    title: 'مجوزها و پروانه‌ها', titleSingular: 'مجوز', icon: 'certificate',
    perm: { view: 'licensing.view', create: 'licensing.create', edit: 'licensing.edit', delete: 'licensing.delete', export: 'licensing.export' },
    search: ['title', 'number', 'authority'], orderBy: 'expiry_date ASC',
    filters: [{ name: 'expiry_date', label: 'تاریخ انقضا', type: 'date_range' }, { name: 'status', label: 'وضعیت', type: 'select', options: ['valid', 'expiring', 'expired', 'renewing', 'revoked'] }],
    listColumns: [
      { field: 'title', label: 'عنوان مجوز' }, { field: 'number', label: 'شماره' }, { field: 'authority', label: 'مرجع صدور' },
      { field: 'type', label: 'نوع' }, { field: 'issue_date', label: 'صدور', type: 'date' },
      { field: 'expiry_date', label: 'انقضا', type: 'date' }, { field: 'responsible_name', label: 'مسئول پیگیری' },
      { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان مجوز', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'number', label: 'شماره مجوز', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'authority', label: 'مرجع صدور', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'license', label: 'پروانه فعالیت' }, { value: 'permit', label: 'مجوز' }, { value: 'certificate', label: 'گواهی‌نامه' }, { value: 'standard', label: 'استاندارد' }, { value: 'environmental', label: 'محیط زیست' }, { value: 'fire', label: 'آتش‌نشانی' }, { value: 'health', label: 'بهداشت' }], group: 'مشخصات', col: 6 },
      { name: 'category', label: 'دسته‌بندی', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'issue_date', label: 'تاریخ صدور', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'expiry_date', label: 'تاریخ انقضا', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'renewal_date', label: 'تاریخ تمدید', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'reminder_days', label: 'یادآوری چند روز قبل', type: 'number', group: 'اعتبار', col: 4 },
      { name: 'owner_user_id', label: 'مسئول داخلی', type: 'lookup', source: userSource, group: 'مسئولیت', col: 4 },
      { name: 'responsible_name', label: 'نام مسئول پیگیری', type: 'text', group: 'مسئولیت', col: 4 },
      { name: 'cost', label: 'هزینه صدور/تمدید', type: 'money', group: 'مالی', col: 6 },
      st([{ value: 'valid', label: 'معتبر' }, { value: 'expiring', label: 'نزدیک به انقضا' }, { value: 'expired', label: 'منقضی' }, { value: 'renewing', label: 'در حال تمدید' }, { value: 'revoked', label: 'لغو شده' }], { col: 6 }),
      { name: 'file', label: 'تصویر مجوز', type: 'file', group: 'مدارک', col: 6 },
      { name: 'notes', label: 'یادداشت', type: 'textarea', group: 'مدارک' },
    ],
  },
  {
    key: 'license-renewals', module: 'licensing', table: 'license_renewals', basePath: 'licensing/renewals',
    title: 'سوابق تمدید مجوزها', titleSingular: 'تمدید', icon: 'refresh',
    perm: { view: 'licensing.view', create: 'licensing.renew', edit: 'licensing.renew', delete: 'licensing.delete' },
    orderBy: 'renewed_at DESC',
    listColumns: [{ field: 'license_id', label: 'مجوز' }, { field: 'renewed_at', label: 'تاریخ تمدید', type: 'date' }, { field: 'new_expiry', label: 'انقضای جدید', type: 'date' }, { field: 'cost', label: 'هزینه', type: 'money' }, { field: 'reference', label: 'شماره نامه' }],
    sumFields: [{ field: 'cost', alias: 'cost_sum' }],
    fields: [
      { name: 'license_id', label: 'مجوز', type: 'lookup', required: true, source: src(`SELECT id, title AS label FROM ${db.t('licenses')} WHERE deleted_at IS NULL ORDER BY title`), group: 'تمدید', col: 6 },
      { name: 'renewed_at', label: 'تاریخ تمدید', type: 'date', group: 'تمدید', col: 4 },
      { name: 'new_expiry', label: 'تاریخ انقضای جدید', type: 'date', group: 'تمدید', col: 4 },
      { name: 'cost', label: 'هزینه تمدید', type: 'money', group: 'تمدید', col: 4 },
      { name: 'reference', label: 'شماره نامه/فیش', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'attachment', label: 'پیوست', type: 'file', group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'knowledge-based', module: 'knowledge', table: 'knowledge_based', basePath: 'knowledge-based',
    title: 'امور دانش‌بنیان', titleSingular: 'پرونده دانش‌بنیان', icon: 'atom',
    perm: { view: 'knowledge.view', create: 'knowledge.create', edit: 'knowledge.edit', delete: 'knowledge.delete' },
    search: ['title', 'assessment_no'], orderBy: 'expiry_date ASC',
    listColumns: [
      { field: 'title', label: 'عنوان' }, { field: 'status', label: 'وضعیت', badge: true }, { field: 'assessment_no', label: 'شماره ارزیابی' },
      { field: 'level', label: 'سطح' }, { field: 'evaluation_date', label: 'تاریخ ارزیابی', type: 'date' },
      { field: 'expiry_date', label: 'اعتبار تا', type: 'date' }, { field: 'authority', label: 'مرجع' },
    ],
    fields: [
      { name: 'title', label: 'عنوان', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'granted', label: 'دارای تأییدیه' }, { value: 'pending', label: 'در حال بررسی' }, { value: 'expired', label: 'منقضی' }, { value: 'rejected', label: 'رد شده' }], group: 'مشخصات', col: 6 },
      { name: 'assessment_no', label: 'شماره ارزیابی', type: 'text', group: 'ارزیابی', col: 6 },
      { name: 'level', label: 'سطح (نوع ۱/۲/۳)', type: 'text', group: 'ارزیابی', col: 6 },
      { name: 'evaluation_date', label: 'تاریخ ارزیابی', type: 'date', group: 'ارزیابی', col: 4 },
      { name: 'expiry_date', label: 'تاریخ اعتبار', type: 'date', group: 'ارزیابی', col: 4 },
      { name: 'authority', label: 'مرجع صدور', type: 'text', group: 'ارزیابی', col: 4 },
      { name: 'reminder_days', label: 'یادآوری چند روز قبل', type: 'number', group: 'ارزیابی', col: 4 },
      { name: 'responsible_name', label: 'مسئول پیگیری', type: 'text', group: 'ارزیابی', col: 4 },
      { name: 'product_desc', label: 'شرح محصولات دانش‌بنیان', type: 'textarea', group: 'جزئیات' },
      { name: 'revenue_share', label: 'سهم درآمد / تعهدات', type: 'text', group: 'جزئیات' },
      { name: 'tax_exempt_note', label: 'معافیت‌ها و مشوق‌ها', type: 'textarea', group: 'جزئیات' },
      { name: 'file', label: 'تصویر تأییدیه', type: 'file', group: 'مدارک', col: 6 },
      { name: 'notes', label: 'یادداشت', type: 'textarea', group: 'مدارک' },
    ],
  },
  {
    key: 'ip-assets', module: 'ip', table: 'ip_assets', basePath: 'ip',
    title: 'دارایی‌های مالکیت فکری', titleSingular: 'دارایی فکری', icon: 'lightbulb',
    perm: { view: 'ip.view', create: 'ip.create', edit: 'ip.edit', delete: 'ip.delete' },
    search: ['title', 'registry_no', 'owner'], orderBy: 'id DESC',
    listColumns: [
      { field: 'title', label: 'عنوان' }, { field: 'type', label: 'نوع' }, { field: 'registry_no', label: 'شماره ثبت' },
      { field: 'filing_date', label: 'تاریخ ثبت', type: 'date' }, { field: 'expiry_date', label: 'پایان اعتبار', type: 'date' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان دارایی', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'patent', label: 'اختراع' }, { value: 'trademark', label: 'علامت تجاری' }, { value: 'copyright', label: 'حق تألیف / نرم‌افزار' }, { value: 'industrial_design', label: 'طرح صنعتی' }, { value: 'trade_secret', label: 'اسرار تجاری' }, { value: 'utility_model', label: 'طرح جدید صنعتی' }], group: 'مشخصات', col: 6 },
      { name: 'registry_no', label: 'شماره ثبت', type: 'text', group: 'ثبت', col: 4 },
      { name: 'authority', label: 'مرجع ثبت', type: 'text', group: 'ثبت', col: 4 },
      { name: 'filing_date', label: 'تاریخ ثبت', type: 'date', group: 'ثبت', col: 4 },
      { name: 'grant_date', label: 'تاریخ صدور گواهی', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'expiry_date', label: 'تاریخ انقضا', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'renewal_date', label: 'تاریخ تمدید', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'owner', label: 'مالک', type: 'text', group: 'مالکیت', col: 6 },
      { name: 'inventors', label: 'مخترعان / پدیدآورندگان', type: 'text', group: 'مالکیت', col: 6 },
      { name: 'annual_fee', label: 'هزینه سالانه نگهداری', type: 'money', group: 'مالی', col: 6 },
      st([{ value: 'filed', label: 'ثبت‌شده' }, { value: 'pending', label: 'در حال بررسی' }, { value: 'granted', label: 'گواهی صادر شد' }, { value: 'expired', label: 'منقضی' }, { value: 'rejected', label: 'رد شده' }], { col: 6 }),
      { name: 'file', label: 'گواهی / مدارک', type: 'file', group: 'مدارک', col: 6 },
      { name: 'notes', label: 'یادداشت', type: 'textarea', group: 'مدارک' },
    ],
  },

  /* ============================ سهامداران و امور شرکت ============================ */
  {
    key: 'shareholders', module: 'shareholders', table: 'shareholders', basePath: 'shareholders/list',
    title: 'سهام‌داران', titleSingular: 'سهام‌دار', icon: 'pie-chart',
    perm: { view: 'shareholders.view', create: 'shareholders.create', edit: 'shareholders.edit', delete: 'shareholders.delete' },
    search: ['name', 'national_id', 'reg_no'], orderBy: 'share_percent DESC, id ASC',
    listColumns: [
      { field: 'name', label: 'نام سهام‌دار' }, { field: 'person_type', label: 'نوع شخص' }, { field: 'national_id', label: 'کد ملی / شناسه' },
      { field: 'share_type', label: 'نوع سهم' }, { field: 'shares_count', label: 'تعداد سهم', type: 'number' },
      { field: 'share_percent', label: 'درصد (٪)' }, { field: 'paid_amount', label: 'مبلغ پرداختی', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    sumFields: [{ field: 'shares_count', alias: 'shares_sum' }, { field: 'paid_amount', alias: 'paid_sum' }],
    fields: [
      { name: 'name', label: 'نام و نام خانوادگی / عنوان شرکت', type: 'text', required: true, group: 'مشخصات', col: 8 },
      { name: 'person_type', label: 'نوع شخص', type: 'select', options: [{ value: 'real', label: 'حقیقی' }, { value: 'legal', label: 'حقوقی' }], group: 'مشخصات', col: 4 },
      { name: 'national_id', label: 'کد ملی / شناسه ملی', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'father_name', label: 'نام پدر', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'birth_date', label: 'تاریخ تولد / ثبت', type: 'date', group: 'مشخصات', col: 4 },
      { name: 'reg_no', label: 'شماره ثبت (اشخاص حقوقی)', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'economic_code', label: 'کد اقتصادی', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'mobile', label: 'موبایل', type: 'text', group: 'تماس', col: 4, dir: 'ltr' },
      { name: 'phone', label: 'تلفن', type: 'text', group: 'تماس', col: 4, dir: 'ltr' },
      { name: 'email', label: 'ایمیل', type: 'text', group: 'تماس', col: 4, dir: 'ltr' },
      { name: 'address', label: 'نشانی', type: 'textarea', group: 'تماس' },
      { name: 'share_type', label: 'نوع سهام', type: 'select', options: [{ value: 'ordinary', label: 'عادی' }, { value: 'preferred', label: 'ممتاز' }, { value: 'founder', label: 'مؤسس' }, { value: 'board', label: 'هیئت‌مدیره' }], group: 'سهام', col: 4 },
      { name: 'shares_count', label: 'تعداد سهام', type: 'number', group: 'سهام', col: 4 },
      { name: 'share_percent', label: 'درصد مالکیت', type: 'number', group: 'سهام', col: 4 },
      { name: 'nominal_value', label: 'ارزش اسمی', type: 'money', group: 'مالی', col: 4 },
      { name: 'paid_amount', label: 'مبلغ پرداخت‌شده', type: 'money', group: 'مالی', col: 4 },
      { name: 'payment_date', label: 'تاریخ پرداخت', type: 'date', group: 'مالی', col: 4 },
      { name: 'join_date', label: 'تاریخ عضویت', type: 'date', group: 'مالی', col: 4 },
      st([{ value: 'active', label: 'فعال' }, { value: 'transferred', label: 'منتقل‌شده' }, { value: 'inactive', label: 'غیرفعال' }], { col: 4 }),
      { name: 'bank_account', label: 'شماره حساب (برای سود)', type: 'text', group: 'مالی', col: 4, dir: 'ltr' },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'shareholder-transactions', module: 'shareholders', table: 'shareholder_transactions', basePath: 'shareholders/transactions',
    title: 'گردش و نقل و انتقال سهام', titleSingular: 'معامله سهام', icon: 'refresh-cw',
    perm: { view: 'shareholders.view', create: 'shareholders.transaction.manage', edit: 'shareholders.transaction.manage', delete: 'shareholders.transaction.manage' },
    orderBy: 'tdate DESC, id DESC',
    listColumns: [
      { field: 'tdate', label: 'تاریخ', type: 'date' }, { field: 'type', label: 'نوع' }, { field: 'shareholder_id', label: 'سهام‌دار' },
      { field: 'shares', label: 'تعداد سهم', type: 'number' }, { field: 'price_per_share', label: 'قیمت هر سهم', type: 'money' },
      { field: 'amount', label: 'مبلغ کل', type: 'money' }, { field: 'reference', label: 'مرجع' },
    ],
    sumFields: [{ field: 'amount', alias: 'amount_sum' }],
    fields: [
      { name: 'shareholder_id', label: 'سهام‌دار', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('shareholders')} WHERE deleted_at IS NULL ORDER BY name`), group: 'معامله', col: 6 },
      { name: 'type', label: 'نوع معامله', type: 'select', options: [{ value: 'transfer', label: 'نقل و انتقال' }, { value: 'issue', label: 'صدور سهام جدید' }, { value: 'buyback', label: 'بازخرید' }, { value: 'capital_increase', label: 'افزایش سرمایه' }, { value: 'dividend', label: 'سود نقدی' }, { value: 'gift', label: 'اهدا' }, { value: 'inheritance', label: 'ارث' }], required: true, group: 'معامله', col: 6 },
      { name: 'tdate', label: 'تاریخ معامله', type: 'date', group: 'معامله', col: 4 },
      { name: 'shares', label: 'تعداد سهام', type: 'number', group: 'مالی', col: 4 },
      { name: 'price_per_share', label: 'قیمت هر سهم', type: 'money', group: 'مالی', col: 4 },
      { name: 'amount', label: 'مبلغ کل', type: 'money', group: 'مالی', col: 6 },
      { name: 'from_shareholder_id', label: 'از سهام‌دار (انتقال‌دهنده)', type: 'lookup', source: src(`SELECT id, name AS label FROM ${db.t('shareholders')} WHERE deleted_at IS NULL ORDER BY name`), group: 'طرفین', col: 6 },
      { name: 'to_shareholder_id', label: 'به سهام‌دار (گیرنده)', type: 'lookup', source: src(`SELECT id, name AS label FROM ${db.t('shareholders')} WHERE deleted_at IS NULL ORDER BY name`), group: 'طرفین', col: 6 },
      { name: 'reference', label: 'شماره صورت‌جلسه / سند', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'file', label: 'پیوست سند', type: 'file', group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'board-members', module: 'shareholders', table: 'board_members', basePath: 'shareholders/board',
    title: 'اعضای هیئت‌مدیره و بازرسان', titleSingular: 'عضو هیئت‌مدیره', icon: 'users',
    perm: { view: 'shareholders.view', create: 'shareholders.board.manage', edit: 'shareholders.board.manage', delete: 'shareholders.board.manage' },
    search: ['name', 'company'], orderBy: 'start_date DESC',
    listColumns: [
      { field: 'name', label: 'نام' }, { field: 'role', label: 'سمت' }, { field: 'member_type', label: 'نوع عضویت' },
      { field: 'start_date', label: 'از', type: 'date' }, { field: 'end_date', label: 'تا', type: 'date' },
      { field: 'attendance_rate', label: 'درصد حضور' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'name', label: 'نام و نام خانوادگی', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'national_id', label: 'کد ملی', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'role', label: 'سمت', type: 'select', options: [{ value: 'chairman', label: 'رئیس هیئت‌مدیره' }, { value: 'vice_chairman', label: 'نایب رئیس' }, { value: 'ceo', label: 'مدیرعامل' }, { value: 'member', label: 'عضو هیئت‌مدیره' }, { value: 'supervisor', label: 'بازرس' }, { value: 'inspector', label: 'بازرس قانونی' }], group: 'مشخصات', col: 6 },
      { name: 'member_type', label: 'نوع عضویت', type: 'select', options: [{ value: 'main', label: 'اصلی' }, { value: 'alternate', label: 'علی‌البدل' }, { value: 'observer', label: 'ناظر' }], group: 'مشخصات', col: 6 },
      { name: 'company', label: 'سازمان/شرکت', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'start_date', label: 'از تاریخ', type: 'date', group: 'دوره عضویت', col: 4 },
      { name: 'end_date', label: 'تا تاریخ', type: 'date', group: 'دوره عضویت', col: 4 },
      { name: 'attendance_rate', label: 'درصد حضور در جلسات', type: 'number', group: 'دوره عضویت', col: 4 },
      { name: 'reward', label: 'حق‌الزحمه / پرداختی', type: 'money', group: 'مالی', col: 6 },
      st([{ value: 'active', label: 'فعال' }, { value: 'ended', label: 'پایان دوره' }], { col: 6 }),
      { name: 'file', label: 'مدارک', type: 'file', group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'general-meetings', module: 'shareholders', table: 'general_meetings', basePath: 'shareholders/meetings',
    title: 'مجامع عمومی', titleSingular: 'مجمع', icon: 'gavel',
    perm: { view: 'shareholders.view', create: 'shareholders.meeting.manage', edit: 'shareholders.meeting.manage', delete: 'shareholders.meeting.manage' },
    search: ['title', 'agenda', 'decisions'], orderBy: 'meeting_date DESC',
    listColumns: [
      { field: 'meeting_date', label: 'تاریخ', type: 'date' }, { field: 'type', label: 'نوع' }, { field: 'title', label: 'عنوان' },
      { field: 'location', label: 'محل' }, { field: 'quorum_percent', label: 'درصد به‌نصاب' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان مجمع', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'ordinary', label: 'عادی' }, { value: 'extraordinary', label: 'فوق‌العاده' }, { value: 'board', label: 'هیئت‌مدیره' }, { value: 'committee', label: 'کمیته' }], group: 'مشخصات', col: 6 },
      { name: 'meeting_date', label: 'تاریخ برگزاری', type: 'date', group: 'زمان و مکان', col: 4 },
      { name: 'meeting_time', label: 'ساعت', type: 'text', group: 'زمان و مکان', col: 4, dir: 'ltr' },
      { name: 'location', label: 'محل برگزاری', type: 'text', group: 'زمان و مکان', col: 4 },
      { name: 'quorum_percent', label: 'درصد سهام حاضر (نصاب)', type: 'number', group: 'زمان و مکان', col: 4 },
      st([{ value: 'planned', label: 'برنامه‌ریزی‌شده' }, { value: 'held', label: 'برگزار شده' }, { value: 'canceled', label: 'لغو شده' }], { col: 8 }),
      { name: 'agenda', label: 'دستور جلسه', type: 'textarea', group: 'محتوا', rows: 4 },
      { name: 'decisions', label: 'مصوبات', type: 'textarea', group: 'محتوا', rows: 4 },
      { name: 'attendees', label: 'حاضران (هر خط یک نفر)', type: 'textarea', group: 'محتوا' },
      { name: 'file', label: 'صورت‌جلسه', type: 'file', group: 'مدارک', col: 6 },
    ],
  },
  {
    key: 'company-capital', module: 'shareholders', table: 'company_capital', basePath: 'shareholders/capital',
    title: 'سرمایه شرکت', titleSingular: 'رکورد سرمایه', icon: 'landmark',
    perm: { view: 'shareholders.view', create: 'shareholders.capital.manage', edit: 'shareholders.capital.manage', delete: 'shareholders.capital.manage' },
    orderBy: 'year DESC',
    listColumns: [{ field: 'year', label: 'سال' }, { field: 'capital_amount', label: 'سرمایه ثبت‌شده', type: 'money' }, { field: 'shares_total', label: 'تعداد سهام', type: 'number' }, { field: 'nominal_value', label: 'ارزش اسمی سهم', type: 'money' }, { field: 'increase_amount', label: 'افزایش سرمایه', type: 'money' }, { field: 'rdate', label: 'تاریخ ثبت', type: 'date' }],
    fields: [
      { name: 'year', label: 'سال', type: 'number', required: true, group: 'سرمایه', col: 4 },
      { name: 'capital_amount', label: 'سرمایه ثبت‌شده', type: 'money', group: 'سرمایه', col: 4 },
      { name: 'shares_total', label: 'تعداد کل سهام', type: 'number', group: 'سرمایه', col: 4 },
      { name: 'nominal_value', label: 'ارزش اسمی هر سهم', type: 'money', group: 'سرمایه', col: 4 },
      { name: 'increase_amount', label: 'مبلغ افزایش سرمایه', type: 'money', group: 'سرمایه', col: 4 },
      { name: 'rdate', label: 'تاریخ ثبت', type: 'date', group: 'ثبت', col: 4 },
      { name: 'reg_no', label: 'شماره ثبت', type: 'text', group: 'ثبت', col: 6 },
      { name: 'file', label: 'مدارک', type: 'file', group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'corporate-records', module: 'corporate', table: 'corporate_records', basePath: 'corporate',
    title: 'امور ثبتی شرکت', titleSingular: 'رکورد ثبتی', icon: 'file-text',
    perm: { view: 'corporate.view', create: 'corporate.create', edit: 'corporate.edit', delete: 'corporate.delete' },
    search: ['title', 'reg_no', 'authority'], orderBy: 'rdate DESC',
    listColumns: [{ field: 'title', label: 'عنوان' }, { field: 'type', label: 'نوع' }, { field: 'reg_no', label: 'شماره ثبت' }, { field: 'rdate', label: 'تاریخ', type: 'date' }, { field: 'expiry_date', label: 'انقضا', type: 'date' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'عنوان مدرک/اقدام', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'registration', label: 'ثبت شرکت' }, { value: 'certificate', label: 'گواهی' }, { value: 'charter', label: 'اساسنامه' }, { value: 'change', label: 'تغییرات' }, { value: 'announcement', label: 'آگهی رسمی' }, { value: 'license_extension', label: 'تمدید' }], group: 'مشخصات', col: 6 },
      { name: 'reg_no', label: 'شماره ثبت / نامه', type: 'text', group: 'ثبت', col: 4 },
      { name: 'authority', label: 'مرجع', type: 'text', group: 'ثبت', col: 4 },
      { name: 'rdate', label: 'تاریخ', type: 'date', group: 'ثبت', col: 4 },
      { name: 'expiry_date', label: 'تاریخ انقضا', type: 'date', group: 'اعتبار', col: 4 },
      st([{ value: 'active', label: 'جاری' }, { value: 'expired', label: 'منقضی' }, { value: 'archived', label: 'بایگانی' }], { col: 8 }),
      { name: 'description', label: 'شرح', type: 'textarea', group: 'جزئیات' },
      { name: 'file', label: 'فایل مدرک', type: 'file', group: 'تکمیلی', col: 6 },
    ],
  },
  {
    key: 'legal-contracts', module: 'legal', table: 'legal_contracts', basePath: 'legal/contracts',
    title: 'قراردادهای حقوقی', titleSingular: 'قرارداد', icon: 'file-signature',
    perm: { view: 'legal.view', create: 'legal.create', edit: 'legal.edit', delete: 'legal.delete' },
    search: ['title', 'party_name', 'subject'], orderBy: 'end_date ASC',
    filters: [{ name: 'end_date', label: 'تاریخ پایان', type: 'date_range' }, { name: 'status', label: 'وضعیت', type: 'select', options: ['draft', 'active', 'expired', 'terminated'] }],
    listColumns: [
      { field: 'title', label: 'عنوان قرارداد' }, { field: 'type', label: 'نوع' }, { field: 'party_name', label: 'طرف قرارداد' },
      { field: 'amount', label: 'مبلغ', type: 'money' }, { field: 'start_date', label: 'شروع', type: 'date' },
      { field: 'end_date', label: 'پایان', type: 'date' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان قرارداد', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: ['فروش', 'خرید', 'خدمات', 'پیمانکاری', 'مشاوره', 'اجاره', 'تأمین کالا', 'همکاری', 'محرمانگی'], group: 'مشخصات', col: 6 },
      { name: 'party_name', label: 'نام طرف قرارداد', type: 'text', group: 'طرفین', col: 6 },
      { name: 'party_national_id', label: 'کد ملی/شناسه طرف قرارداد', type: 'text', group: 'طرفین', col: 6 },
      { name: 'subject', label: 'موضوع قرارداد', type: 'textarea', group: 'طرفین' },
      { name: 'amount', label: 'مبلغ قرارداد', type: 'money', group: 'مالی و زمان', col: 4 },
      { name: 'start_date', label: 'تاریخ شروع', type: 'date', group: 'مالی و زمان', col: 4 },
      { name: 'end_date', label: 'تاریخ پایان', type: 'date', group: 'مالی و زمان', col: 4 },
      { name: 'renewal_notice_days', label: 'یادآوری تمدید (روز قبل)', type: 'number', group: 'مالی و زمان', col: 4 },
      { name: 'responsible_user_id', label: 'مسئول پیگیری', type: 'lookup', source: userSource, group: 'مالی و زمان', col: 4 },
      st([{ value: 'draft', label: 'پیش‌نویس' }, { value: 'active', label: 'جاری' }, { value: 'expired', label: 'منقضی' }, { value: 'terminated', label: 'فسخ‌شده' }], { col: 4 }),
      { name: 'file', label: 'فایل قرارداد', type: 'file', group: 'مدارک', col: 6 },
      { name: 'notes', label: 'یادداشت', type: 'textarea', group: 'مدارک' },
    ],
  },
  {
    key: 'legal-cases', module: 'legal', table: 'legal_cases', basePath: 'legal/cases',
    title: 'پرونده‌های قضایی', titleSingular: 'پرونده', icon: 'gavel',
    perm: { view: 'legal.view', create: 'legal.create', edit: 'legal.edit', delete: 'legal.delete' },
    search: ['title', 'case_no', 'opponent', 'court'], orderBy: 'next_hearing ASC',
    listColumns: [
      { field: 'title', label: 'عنوان پرونده' }, { field: 'type', label: 'نوع' }, { field: 'case_no', label: 'شماره پرونده' },
      { field: 'court', label: 'دادگاه/مرجع' }, { field: 'opponent', label: 'طرف مقابل' },
      { field: 'claim_amount', label: 'مبلغ خواسته', type: 'money' }, { field: 'next_hearing', label: 'جلسه بعدی', type: 'date' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان پرونده', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'claim', label: 'مطالبه' }, { value: 'defense', label: 'دفاع' }, { value: 'labor', label: 'کار و تأمین اجتماعی' }, { value: 'contract', label: 'قراردادی' }, { value: 'tax', label: 'مالیاتی' }, { value: 'criminal', label: 'کیفری' }], group: 'مشخصات', col: 6 },
      { name: 'case_no', label: 'شماره پرونده', type: 'text', group: 'مرجع', col: 4 },
      { name: 'court', label: 'دادگاه / مرجع', type: 'text', group: 'مرجع', col: 4 },
      { name: 'next_hearing', label: 'تاریخ جلسه بعدی', type: 'date', group: 'مرجع', col: 4 },
      { name: 'opponent', label: 'نام طرف مقابل', type: 'text', group: 'طرفین', col: 6 },
      { name: 'opponent_national_id', label: 'کد ملی طرف مقابل', type: 'text', group: 'طرفین', col: 6 },
      { name: 'claim_amount', label: 'مبلغ خواسته', type: 'money', group: 'مالی', col: 6 },
      { name: 'lawyer', label: 'وکیل / مشاور', type: 'text', group: 'مالی', col: 3 },
      { name: 'lawyer_phone', label: 'تلفن وکیل', type: 'text', group: 'مالی', col: 3, dir: 'ltr' },
      st([{ value: 'open', label: 'باز' }, { value: 'won', label: 'به نفع ما' }, { value: 'lost', label: 'به ضرر ما' }, { value: 'settled', label: 'سازش' }, { value: 'appealed', label: 'تجدیدنظر' }, { value: 'closed', label: 'بسته‌شده' }], { col: 6 }),
      { name: 'subject', label: 'موضوع پرونده', type: 'textarea', group: 'جزئیات' },
      { name: 'description', label: 'شرح و اقدامات', type: 'textarea', group: 'جزئیات' },
      { name: 'outcome', label: 'نتیجه نهایی', type: 'textarea', group: 'جزئیات' },
      { name: 'file', label: 'مدارک پرونده', type: 'file', group: 'مدارک', col: 6 },
    ],
  },
  {
    key: 'compliance-items', module: 'legal', table: 'compliance_items', basePath: 'legal/compliance',
    title: 'الزامات و تکالیف قانونی', titleSingular: 'تکلیف قانونی', icon: 'clipboard-check',
    perm: { view: 'legal.view', create: 'legal.compliance.manage', edit: 'legal.compliance.manage', delete: 'legal.compliance.manage' },
    search: ['title', 'authority', 'requirement'], orderBy: 'due_date ASC',
    listColumns: [{ field: 'due_date', label: 'مهلت', type: 'date' }, { field: 'title', label: 'عنوان' }, { field: 'authority', label: 'مرجع' }, { field: 'recurrence', label: 'تکرار' }, { field: 'status', label: 'وضعیت', badge: true }, { field: 'done_at', label: 'تاریخ انجام', type: 'date' }],
    fields: [
      { name: 'title', label: 'عنوان تکلیف', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'authority', label: 'مرجع قانونی', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'due_date', label: 'مهلت انجام', type: 'date', group: 'زمان‌بندی', col: 4 },
      { name: 'recurrence', label: 'تکرار', type: 'select', options: ['یک‌بار', 'ماهانه', 'فصلی', 'شش‌ماهه', 'سالانه'], group: 'زمان‌بندی', col: 4 },
      { name: 'owner_user_id', label: 'مسئول', type: 'lookup', source: userSource, group: 'زمان‌بندی', col: 4 },
      st([{ value: 'open', label: 'در جریان' }, { value: 'done', label: 'انجام‌شده' }, { value: 'overdue', label: 'معوق' }, { value: 'not_applicable', label: 'موضوعیت ندارد' }], { col: 6 }),
      { name: 'evidence', label: 'مدرک/پیوست', type: 'file', group: 'تکمیلی', col: 6 },
      { name: 'requirement', label: 'شرح الزام', type: 'textarea', group: 'تکمیلی' },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },

  /* ============================= اموال و درخواست‌ها ============================= */
  {
    key: 'assets', module: 'assets', table: 'assets', basePath: 'assets',
    title: 'اموال و تجهیزات', titleSingular: 'مال', icon: 'package',
    perm: { view: 'assets.view', create: 'assets.create', edit: 'assets.edit', delete: 'assets.delete', export: 'assets.export' },
    search: ['code', 'title', 'brand', 'model', 'serial'], orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['available', 'assigned', 'repair', 'retired', 'lost'] }],
    listColumns: [
      { field: 'code', label: 'کد اموال' }, { field: 'title', label: 'عنوان' }, { field: 'type', label: 'نوع' },
      { field: 'brand', label: 'برند' }, { field: 'serial', label: 'سریال' }, { field: 'employee_id', label: 'تحویل به' },
      { field: 'price', label: 'ارزش', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    sumFields: [{ field: 'price', alias: 'price_sum' }],
    fields: [
      { name: 'code', label: 'کد اموال', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'title', label: 'عنوان مال', type: 'text', required: true, group: 'مشخصات', col: 8 },
      { name: 'type', label: 'نوع', type: 'select', options: ['لپ‌تاپ', 'کیس کامپیوتر', 'مانیتور', 'گوشی موبایل', 'میز و صندلی', 'کمد', 'ابزار دستی', 'ابزار برقی', 'خودرو', 'دوچرخه', 'تجهیزات ایمنی', 'سایر'], group: 'مشخصات', col: 4 },
      { name: 'brand', label: 'برند', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'model', label: 'مدل', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'serial', label: 'شماره سریال', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'location_id', label: 'محل نگهداری', type: 'lookup', source: locSource, group: 'مکان و تحویل', col: 6 },
      { name: 'employee_id', label: 'کارمند تحویل‌گیرنده', type: 'lookup', source: empSource, group: 'مکان و تحویل', col: 6 },
      { name: 'assigned_at', label: 'تاریخ تحویل', type: 'date', group: 'مکان و تحویل', col: 6 },
      { name: 'purchase_date', label: 'تاریخ خرید', type: 'date', group: 'مالی و گارانتی', col: 4 },
      { name: 'price', label: 'ارزش/قیمت خرید', type: 'money', group: 'مالی و گارانتی', col: 4 },
      { name: 'warranty_expiry', label: 'پایان گارانتی', type: 'date', group: 'مالی و گارانتی', col: 4 },
      st([{ value: 'available', label: 'در انبار' }, { value: 'assigned', label: 'تحویل‌شده' }, { value: 'repair', label: 'در تعمیر' }, { value: 'retired', label: 'از رده خارج' }, { value: 'lost', label: 'مفقود' }], { col: 6 }),
      { name: 'condition_note', label: 'وضعیت ظاهری', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'asset-assignments', module: 'assets', table: 'asset_assignments', basePath: 'assets/assignments',
    title: 'تحویل و بازگشت اموال', titleSingular: 'تحویل مال', icon: 'repeat',
    perm: { view: 'assets.view', create: 'assets.assign', edit: 'assets.assign', delete: 'assets.assign' },
    orderBy: 'id DESC',
    listColumns: [{ field: 'asset_id', label: 'مال' }, { field: 'employee_id', label: 'کارمند' }, { field: 'assigned_at', label: 'تاریخ تحویل', type: 'datetime' }, { field: 'returned_at', label: 'تاریخ بازگشت', type: 'datetime' }, { field: 'condition_out', label: 'وضعیت تحویل' }, { field: 'condition_in', label: 'وضعیت بازگشت' }],
    fields: [
      { name: 'asset_id', label: 'مال', type: 'lookup', required: true, source: src(`SELECT id, title AS label FROM ${db.t('assets')} WHERE deleted_at IS NULL ORDER BY title`), group: 'تحویل', col: 6 },
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'تحویل', col: 6 },
      { name: 'assigned_at', label: 'تاریخ تحویل', type: 'datetime', group: 'زمان', col: 4 },
      { name: 'returned_at', label: 'تاریخ بازگشت', type: 'datetime', group: 'زمان', col: 4 },
      { name: 'condition_out', label: 'وضعیت هنگام تحویل', type: 'select', options: ['سالم', 'کارکرده', 'نیاز به تعمیر'], group: 'وضعیت', col: 2 },
      { name: 'condition_in', label: 'وضعیت هنگام بازگشت', type: 'select', options: ['سالم', 'خراب', 'مفقود'], group: 'وضعیت', col: 2 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'hr-requests', module: 'requests', table: 'hr_requests', basePath: 'requests',
    title: 'درخواست‌های پرسنلی', titleSingular: 'درخواست پرسنلی', icon: 'inbox',
    perm: { view: 'requests.view', create: 'requests.create', edit: 'requests.edit', delete: 'requests.edit' },
    search: ['subject', 'description', 'ref_no'], orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['pending', 'in_progress', 'done', 'rejected'] }, { name: 'type', label: 'نوع', type: 'select', options: ['letter', 'certificate', 'loan', 'advance', 'insurance', 'copy', 'other'] }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'type', label: 'نوع' }, { field: 'subject', label: 'موضوع' },
      { field: 'ref_no', label: 'شماره نامه' }, { field: 'status', label: 'وضعیت', badge: true }, { field: 'created_at', label: 'تاریخ ثبت', type: 'datetime' },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'درخواست', col: 6 },
      { name: 'type', label: 'نوع درخواست', type: 'select', options: [{ value: 'letter', label: 'نامه اداری' }, { value: 'certificate', label: 'گواهی اشتغال به کار' }, { value: 'loan', label: 'وام/مساعده' }, { value: 'advance', label: 'علی‌الحساب' }, { value: 'insurance', label: 'سابقه بیمه' }, { value: 'copy', label: 'رونوشت مدارک' }, { value: 'other', label: 'سایر' }], group: 'درخواست', col: 6 },
      { name: 'subject', label: 'موضوع', type: 'text', required: true, group: 'درخواست', col: 8 },
      { name: 'ref_no', label: 'شماره نامه صادره', type: 'text', group: 'درخواست', col: 4 },
      { name: 'description', label: 'شرح درخواست', type: 'textarea', group: 'جزئیات' },
      st([{ value: 'pending', label: 'در انتظار' }, { value: 'in_progress', label: 'در حال انجام' }, { value: 'done', label: 'انجام‌شده' }, { value: 'rejected', label: 'رد شده' }], { col: 6 }),
      { name: 'handled_by', label: 'کارشناس مسئول', type: 'lookup', source: userSource, group: 'جزئیات', col: 6 },
      { name: 'decision_note', label: 'یادداشت', type: 'textarea', group: 'جزئیات' },
      { name: 'file', label: 'فایل نامه صادره', type: 'file', group: 'مدارک', col: 6 },
      { name: 'attachment', label: 'پیوست درخواست', type: 'file', group: 'مدارک', col: 6 },
    ],
  },
  {
    key: 'letter-templates', module: 'requests', table: 'letter_templates', basePath: 'requests/templates',
    title: 'قالب‌های نامه و گواهی', titleSingular: 'قالب نامه', icon: 'file-text',
    perm: { view: 'requests.view', create: 'requests.templates.manage', edit: 'requests.templates.manage', delete: 'requests.templates.manage' },
    search: ['title', 'tkey'], orderBy: 'category ASC, id ASC',
    listColumns: [{ field: 'title', label: 'عنوان قالب' }, { field: 'tkey', label: 'کلید' }, { field: 'category', label: 'دسته' }, { field: 'is_active', label: 'فعال', type: 'checkbox' }],
    fields: [
      { name: 'title', label: 'عنوان قالب', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'tkey', label: 'کلید لاتین', type: 'text', group: 'مشخصات', col: 6, dir: 'ltr' },
      { name: 'category', label: 'دسته', type: 'select', options: ['گواهی', 'نامه اداری', 'حکم', 'ابلاغ', 'اطلاعیه', 'استعفا', 'سایر'], group: 'مشخصات', col: 6 },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'قابل استفاده در صدور نامه', group: 'مشخصات', col: 6 },
      { name: 'body', label: 'متن قالب', type: 'textarea', group: 'متن', rows: 12, help_text: 'متغیرها: {{employee_name}} {{national_id}} {{personnel_code}} {{job_title}} {{department}} {{hire_date}} {{today}} {{company_name}}' },
    ],
    beforeSave: (data, req, ctx) => {
      if ((ctx && ctx.isNew) && !data.tkey) {
        data.tkey = 'tpl_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);
      }
      return data;
    },
  },
  {
    key: 'announcements', module: 'announcements', table: 'announcements', basePath: 'announcements',
    title: 'اطلاعیه‌ها', titleSingular: 'اطلاعیه', icon: 'megaphone',
    perm: { view: 'announcements.view', create: 'announcements.create', edit: 'announcements.edit', delete: 'announcements.delete' },
    search: ['title', 'body'], orderBy: 'publish_at DESC, id DESC',
    listColumns: [{ field: 'title', label: 'عنوان' }, { field: 'audience', label: 'مخاطب' }, { field: 'publish_at', label: 'انتشار', type: 'datetime' }, { field: 'expire_at', label: 'انقضا', type: 'datetime' }, { field: 'is_pinned', label: 'سنجاق', type: 'checkbox' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'عنوان اطلاعیه', type: 'text', required: true, group: 'محتوا', col: 8 },
      { name: 'is_pinned', label: 'سنجاق در بالای فهرست', type: 'checkbox', checkLabel: 'اطلاعیه مهم است', group: 'محتوا', col: 4 },
      { name: 'body', label: 'متن اطلاعیه', type: 'textarea', group: 'محتوا', rows: 6 },
      { name: 'audience', label: 'مخاطب', type: 'select', options: [{ value: 'all', label: 'همه کارکنان' }, { value: 'hr', label: 'منابع انسانی' }, { value: 'managers', label: 'مدیران' }, { value: 'department', label: 'یک واحد خاص' }, { value: 'role', label: 'یک نقش خاص' }], group: 'انتشار', col: 4 },
      { name: 'department_id', label: 'واحد مخاطب', type: 'lookup', source: src(`SELECT id, name AS label FROM ${db.t('departments')} WHERE deleted_at IS NULL`), group: 'انتشار', col: 4 },
      { name: 'role_id', label: 'نقش مخاطب', type: 'lookup', source: src(`SELECT id, name AS label FROM ${db.t('roles')} WHERE status='active'`), group: 'انتشار', col: 4 },
      { name: 'publish_at', label: 'زمان انتشار', type: 'datetime', group: 'انتشار', col: 4 },
      { name: 'expire_at', label: 'زمان انقضا', type: 'datetime', group: 'انتشار', col: 4 },
      st([{ value: 'published', label: 'منتشر شده' }, { value: 'draft', label: 'پیش‌نویس' }, { value: 'archived', label: 'بایگانی' }], { col: 4 }),
      { name: 'attachment', label: 'پیوست', type: 'file', group: 'انتشار', col: 6 },
    ],
  },
  {
    key: 'tasks', module: 'announcements', table: 'tasks', basePath: 'tasks',
    title: 'کارها و وظایف', titleSingular: 'کار', icon: 'check-square',
    perm: { view: 'announcements.view', create: 'announcements.tasks.manage', edit: 'announcements.tasks.manage', delete: 'announcements.tasks.manage' },
    search: ['title', 'description'], orderBy: 'due_date ASC, id DESC',
    listColumns: [{ field: 'title', label: 'عنوان' }, { field: 'assignee_user_id', label: 'مسئول' }, { field: 'due_date', label: 'مهلت', type: 'date' }, { field: 'priority', label: 'اولویت', badge: true }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'عنوان کار', type: 'text', required: true, group: 'مشخصات', col: 8 },
      { name: 'priority', label: 'اولویت', type: 'select', options: [{ value: 'low', label: 'کم' }, { value: 'normal', label: 'عادی' }, { value: 'high', label: 'زیاد' }, { value: 'urgent', label: 'فوری' }], group: 'مشخصات', col: 4 },
      { name: 'assignee_user_id', label: 'مسئول انجام', type: 'lookup', source: userSource, group: 'ارجاع', col: 6 },
      { name: 'due_date', label: 'مهلت', type: 'date', group: 'ارجاع', col: 6 },
      { name: 'description', label: 'شرح کار', type: 'textarea', group: 'مشخصات' },
      st([{ value: 'open', label: 'باز' }, { value: 'in_progress', label: 'در حال انجام' }, { value: 'done', label: 'انجام‌شده' }, { value: 'canceled', label: 'لغو شده' }], { col: 6 }),
      { name: 'completed_at', label: 'تاریخ انجام', type: 'datetime', group: 'وضعیت', col: 6 },
    ],
  },
  {
    key: 'kpis', module: 'performance', table: 'kpis', basePath: 'performance/kpis',
    title: 'شاخص‌های عملکردی', titleSingular: 'شاخص', icon: 'target',
    perm: { view: 'performance.view', create: 'performance.kpi.manage', edit: 'performance.kpi.manage', delete: 'performance.kpi.manage' },
    search: ['title', 'description'], orderBy: 'id DESC',
    listColumns: [{ field: 'title', label: 'عنوان شاخص' }, { field: 'department_id', label: 'واحد' }, { field: 'period', label: 'دوره' }, { field: 'target', label: 'هدف' }, { field: 'unit', label: 'واحد سنجش' }, { field: 'weight', label: 'وزن' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'عنوان شاخص', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'department_id', label: 'واحد سازمانی', type: 'lookup', source: src(`SELECT id, name AS label FROM ${db.t('departments')} WHERE deleted_at IS NULL`), group: 'مشخصات', col: 6 },
      { name: 'job_title_id', label: 'عنوان شغلی', type: 'lookup', source: src(`SELECT id, title AS label FROM ${db.t('job_titles')} WHERE deleted_at IS NULL`), group: 'مشخصات', col: 6 },
      { name: 'period', label: 'دوره ارزیابی', type: 'select', options: [{ value: 'monthly', label: 'ماهانه' }, { value: 'quarterly', label: 'فصلی' }, { value: 'biannual', label: 'شش‌ماهه' }, { value: 'yearly', label: 'سالانه' }], group: 'مشخصات', col: 6 },
      { name: 'target', label: 'هدف', type: 'text', group: 'سنجش', col: 4 },
      { name: 'unit', label: 'واحد سنجش', type: 'text', group: 'سنجش', col: 4 },
      { name: 'weight', label: 'وزن', type: 'number', group: 'سنجش', col: 4 },
      st([{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }], { col: 6 }),
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'performance-reviews', module: 'performance', table: 'performance_reviews', basePath: 'performance/reviews',
    title: 'ارزیابی‌های عملکرد', titleSingular: 'ارزیابی', icon: 'chart',
    perm: { view: 'performance.view', create: 'performance.review.create', edit: 'performance.review.fill', delete: 'performance.review.create' },
    orderBy: 'id DESC',
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'period_label', label: 'دوره' }, { field: 'review_date', label: 'تاریخ', type: 'date' },
      { field: 'type', label: 'نوع' }, { field: 'overall_score', label: 'امتیاز کل' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'period_label', label: 'دوره ارزیابی', type: 'text', required: true, group: 'مشخصات', col: 6, placeholder: 'مثال: نیمه اول ۱۴۰۴' },
      { name: 'review_date', label: 'تاریخ ارزیابی', type: 'date', group: 'مشخصات', col: 4 },
      { name: 'type', label: 'نوع ارزیابی', type: 'select', options: [{ value: 'manager', label: 'توسط مدیر' }, { value: 'self', label: 'خودارزیابی' }, { value: 'peer', label: 'همکاران' }, { value: '360', label: '۳۶۰ درجه' }], group: 'مشخصات', col: 4 },
      { name: 'reviewer_user_id', label: 'ارزیاب', type: 'lookup', source: userSource, group: 'مشخصات', col: 4 },
      { name: 'overall_score', label: 'امتیاز کل (۱۰۰)', type: 'number', group: 'نتیجه', col: 4 },
      st([{ value: 'draft', label: 'پیش‌نویس' }, { value: 'pending_employee', label: 'در انتظار نظر کارمند' }, { value: 'done', label: 'نهایی‌شده' }], { col: 4 }),
      { name: 'summary', label: 'جمع‌بندی', type: 'textarea', group: 'نتیجه' },
      { name: 'strengths', label: 'نقاط قوت', type: 'textarea', group: 'نتیجه' },
      { name: 'improvements', label: 'زمینه‌های بهبود', type: 'textarea', group: 'نتیجه' },
      { name: 'employee_comment', label: 'نظر کارمند', type: 'textarea', group: 'نتیجه' },
    ],
  },
  {
    key: 'message-templates', module: 'messaging', table: 'message_templates', basePath: 'messaging/templates',
    title: 'قالب‌های پیام', titleSingular: 'قالب پیام', icon: 'message-square',
    perm: { view: 'messaging.view', create: 'messaging.templates.manage', edit: 'messaging.templates.manage', delete: 'messaging.templates.manage' },
    search: ['title', 'mkey'], orderBy: 'id ASC',
    listColumns: [{ field: 'title', label: 'عنوان' }, { field: 'mkey', label: 'کلید' }, { field: 'channel', label: 'کانال' }, { field: 'provider_pattern', label: 'کد الگو' }, { field: 'is_active', label: 'فعال', type: 'checkbox' }],
    fields: [
      { name: 'title', label: 'عنوان قالب', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'mkey', label: 'کلید لاتین', type: 'text', group: 'مشخصات', col: 6, dir: 'ltr' },
      { name: 'channel', label: 'کانال', type: 'select', options: [{ value: 'sms', label: 'پیامک' }, { value: 'email', label: 'ایمیل' }, { value: 'notification', label: 'اطلاع‌رسانی داخلی' }], group: 'مشخصات', col: 4 },
      { name: 'provider_pattern', label: 'کد الگو در آی‌پی‌پنل', type: 'text', group: 'مشخصات', col: 4, dir: 'ltr' },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'استفاده در ارسال خودکار', group: 'مشخصات', col: 4 },
      { name: 'body', label: 'متن پیام', type: 'textarea', group: 'متن', rows: 5, help_text: 'متغیرها: {{name}} {{position}} {{date}} {{time}} {{code}} {{company}}' },
    ],
    beforeSave: (data, req, ctx) => {
      if ((ctx && ctx.isNew) && !data.mkey) {
        data.mkey = 'msg_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);
      }
      return data;
    },
  },
  {
    key: 'sms-logs', module: 'messaging', table: 'sms_logs', basePath: 'messaging/logs',
    title: 'گزارش ارسال پیامک', titleSingular: 'پیامک', icon: 'send',
    perm: { view: 'messaging.logs' },
    orderBy: 'id DESC',
    filters: [{ name: 'created_at', label: 'تاریخ ارسال', type: 'date_range' }, { name: 'status', label: 'وضعیت', type: 'select', options: ['sent', 'failed', 'pending'] }],
    listColumns: [
      { field: 'created_at', label: 'زمان', type: 'datetime' }, { field: 'mobile', label: 'شماره' }, { field: 'type', label: 'نوع' },
      { field: 'template_key', label: 'کلید قالب' }, { field: 'body', label: 'متن' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'mobile', label: 'شماره موبایل', type: 'text', group: 'پیامک', col: 4, dir: 'ltr' },
      { name: 'type', label: 'نوع', type: 'select', options: ['text', 'pattern', 'otp'], group: 'پیامک', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'sent', label: 'ارسال‌شده' }, { value: 'failed', label: 'ناموفق' }, { value: 'pending', label: 'در صف' }], group: 'پیامک', col: 4 },
      { name: 'template_key', label: 'کلید قالب', type: 'text', group: 'پیامک', col: 6 },
      { name: 'provider_id', label: 'شناسه سرویس‌دهنده', type: 'text', group: 'پیامک', col: 6, dir: 'ltr' },
      { name: 'body', label: 'متن پیام', type: 'textarea', group: 'جزئیات' },
      { name: 'error', label: 'خطا', type: 'textarea', group: 'جزئیات' },
    ],
    beforeSave: (data) => {
      if (!data.mobile) data.mobile = '0000000000';
      return data;
    },
  },
  {
    key: 'employee-kits', module: 'onboarding', table: 'employee_kits', basePath: 'onboarding/employee-kits',
    title: 'اقلام تحویلی کارکنان', titleSingular: 'قلم تحویلی', icon: 'package',
    perm: { view: 'onboarding.view', create: 'onboarding.edit', edit: 'onboarding.edit', delete: 'onboarding.edit' },
    orderBy: 'id DESC',
    listColumns: [{ field: 'employee_id', label: 'کارمند' }, { field: 'title', label: 'قلم' }, { field: 'quantity', label: 'تعداد' }, { field: 'delivered', label: 'تحویل شد', type: 'checkbox' }, { field: 'delivered_at', label: 'تاریخ تحویل', type: 'datetime' }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'تحویل', col: 6 },
      { name: 'title', label: 'عنوان قلم', type: 'text', group: 'تحویل', col: 6 },
      { name: 'item_id', label: 'از فهرست اقلام', type: 'lookup', source: src(`SELECT id, title AS label FROM ${db.t('onboarding_kit_items')}`), group: 'تحویل', col: 6 },
      { name: 'quantity', label: 'تعداد', type: 'number', group: 'تحویل', col: 3 },
      { name: 'delivered', label: 'تحویل شده', type: 'checkbox', checkLabel: 'تحویل داده شده است', group: 'تحویل', col: 3 },
      { name: 'delivered_at', label: 'تاریخ تحویل', type: 'datetime', group: 'تحویل', col: 6 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
];
