'use strict';
/**
 * تعریف منابع ماژول‌های منابع انسانی
 * (جذب، آزمون، بدو ورود، آموزش، حضور و مرخصی، حقوق، ترک کار)
 */
const db = require('../db');

/* ------------------------------ کمک‌کننده‌ها ------------------------------ */
const src = (sql) => () => sql;
const empSource = src(`SELECT id, full_name AS label FROM ${db.t('employees')} WHERE deleted_at IS NULL ORDER BY full_name`);
const userSource = src(`SELECT id, full_name AS label FROM ${db.t('users')} WHERE status = 'active' ORDER BY full_name`);
const deptSource = src(`SELECT id, name AS label FROM ${db.t('departments')} WHERE deleted_at IS NULL ORDER BY sort_order`);
const jobSource = src(`SELECT id, title AS label FROM ${db.t('job_titles')} WHERE deleted_at IS NULL ORDER BY title`);
const locSource = src(`SELECT id, name AS label FROM ${db.t('locations')} ORDER BY name`);
const reqSource = src(`SELECT id, title AS label FROM ${db.t('job_reqs')} WHERE deleted_at IS NULL ORDER BY id DESC`);
const courseSource = src(`SELECT id, title AS label FROM ${db.t('courses')} WHERE deleted_at IS NULL ORDER BY title`);
const compSource = src(`SELECT id, name AS label FROM ${db.t('payroll_components')} WHERE is_active = 1 ORDER BY sort_order`);
const periodSource = src(`SELECT id, title AS label FROM ${db.t('payroll_periods')} ORDER BY id DESC`);
const statusField = (options, extra = {}) => ({ name: 'status', label: 'وضعیت', type: 'select', options, group: 'وضعیت', col: 4, ...extra });

module.exports = [
  /* ============================== جذب و استخدام ============================== */
  {
    key: 'job-reqs', module: 'recruitment', table: 'job_reqs', basePath: 'recruitment/jobs',
    title: 'درخواست‌های جذب و آگهی‌ها', titleSingular: 'درخواست جذب', icon: 'briefcase',
    perm: { view: 'recruitment.view', create: 'recruitment.create', edit: 'recruitment.edit', delete: 'recruitment.delete', export: 'recruitment.export' },
    search: ['title', 'code', 'description'], orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['draft', 'open', 'paused', 'closed'] }],
    listColumns: [
      { field: 'code', label: 'کد' }, { field: 'title', label: 'عنوان آگهی' },
      { field: 'department_id', label: 'واحد' }, { field: 'employment_type', label: 'نوع همکاری' },
      { field: 'openings', label: 'ظرفیت', type: 'number' }, { field: 'applicants_count', label: 'داوطلب', type: 'number' },
      { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان آگهی', type: 'text', required: true, group: 'مشخصات آگهی', col: 8 },
      { name: 'code', label: 'کد', type: 'text', group: 'مشخصات آگهی', col: 4 },
      { name: 'department_id', label: 'واحد سازمانی', type: 'lookup', source: deptSource, group: 'مشخصات آگهی', col: 4 },
      { name: 'job_title_id', label: 'عنوان شغلی', type: 'lookup', source: jobSource, group: 'مشخصات آگهی', col: 4 },
      { name: 'location_id', label: 'محل کار', type: 'lookup', source: locSource, group: 'مشخصات آگهی', col: 4 },
      { name: 'employment_type', label: 'نوع همکاری', type: 'select', options: ['تمام‌وقت', 'پاره‌وقت', 'پروژه‌ای', 'قراردادی', 'کارآموزی', 'ساعتی'], group: 'مشخصات آگهی', col: 4 },
      { name: 'openings', label: 'تعداد ظرفیت', type: 'number', group: 'مشخصات آگهی', col: 4 },
      { name: 'salary_from', label: 'حقوق از', type: 'money', group: 'مشخصات آگهی', col: 2 },
      { name: 'salary_to', label: 'تا', type: 'money', group: 'مشخصات آگهی', col: 2 },
      { name: 'description', label: 'شرح آگهی', type: 'textarea', group: 'متن آگهی', rows: 4 },
      { name: 'requirements', label: 'شرایط و مهارت‌های لازم', type: 'textarea', group: 'متن آگهی', rows: 4 },
      { name: 'benefits', label: 'مزایا', type: 'textarea', group: 'متن آگهی', rows: 3 },
      { name: 'start_date', label: 'تاریخ شروع انتشار', type: 'date', group: 'زمان‌بندی', col: 4 },
      { name: 'end_date', label: 'مهلت ثبت‌نام', type: 'date', group: 'زمان‌بندی', col: 4 },
      { name: 'is_public', label: 'نمایش در صفحه فرصت‌های شغلی', type: 'checkbox', checkLabel: 'در سایت عمومی نمایش داده شود', group: 'تنظیمات', col: 4 },
      { name: 'require_mbti', label: 'آزمون MBTI', type: 'checkbox', checkLabel: 'برای این شغل آزمون شخصیت‌شناسی الزامی است', group: 'تنظیمات', col: 4 },
      { name: 'require_interview', label: 'مصاحبه', type: 'checkbox', checkLabel: 'داوطلب باید مرحله مصاحبه را طی کند', group: 'تنظیمات', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'draft', label: 'پیش‌نویس' }, { value: 'open', label: 'منتشر شده' }, { value: 'paused', label: 'متوقف' }, { value: 'closed', label: 'بسته‌شده' }], group: 'تنظیمات', col: 4, nullable: false },
    ],
  },
  {
    key: 'interviews', module: 'recruitment', table: 'interviews', basePath: 'recruitment/interviews',
    title: 'مصاحبه‌ها', titleSingular: 'مصاحبه', icon: 'calendar',
    perm: { view: 'recruitment.view', create: 'recruitment.interview.manage', edit: 'recruitment.interview.manage', delete: 'recruitment.interview.manage' },
    search: ['title', 'notes'], orderBy: 'scheduled_at DESC',
    listColumns: [
      { field: 'application_id', label: 'پرونده' }, { field: 'title', label: 'عنوان' },
      { field: 'type', label: 'نوع' }, { field: 'scheduled_at', label: 'زمان', type: 'datetime' },
      { field: 'status', label: 'وضعیت', badge: true }, { field: 'score', label: 'امتیاز', type: 'number' },
      { field: 'recommendation', label: 'پیشنهاد' },
    ],
    fields: [
      { name: 'application_id', label: 'شناسه پرونده داوطلب', type: 'number', required: true, group: 'ارجاع', col: 4 },
      { name: 'job_req_id', label: 'درخواست جذب', type: 'lookup', source: reqSource, group: 'ارجاع', col: 4 },
      { name: 'round', label: 'دور مصاحبه', type: 'number', group: 'ارجاع', col: 4 },
      { name: 'title', label: 'عنوان مصاحبه', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع مصاحبه', type: 'select', options: [{ value: 'phone', label: 'تلفنی' }, { value: 'online', label: 'آنلاین' }, { value: 'in_person', label: 'حضوری' }, { value: 'panel', label: 'پنل' }, { value: 'technical', label: 'فنی' }], group: 'مشخصات', col: 6 },
      { name: 'scheduled_at', label: 'زمان مصاحبه', type: 'datetime', group: 'زمان و مکان', col: 4 },
      { name: 'duration_minutes', label: 'مدت (دقیقه)', type: 'number', group: 'زمان و مکان', col: 4 },
      { name: 'location', label: 'محل برگزاری', type: 'text', group: 'زمان و مکان', col: 4 },
      { name: 'meeting_link', label: 'لینک جلسه آنلاین', type: 'text', group: 'زمان و مکان', col: 6, dir: 'ltr' },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'scheduled', label: 'برنامه‌ریزی‌شده' }, { value: 'done', label: 'برگزار شده' }, { value: 'canceled', label: 'لغو شده' }, { value: 'no_show', label: 'عدم حضور' }], group: 'نتیجه', col: 6 },
      { name: 'score', label: 'امتیاز کل (۱۰۰)', type: 'number', group: 'نتیجه', col: 4 },
      { name: 'recommendation', label: 'پیشنهاد', type: 'select', options: [{ value: 'hire', label: 'استخدام' }, { value: 'next_round', label: 'دور بعد' }, { value: 'hold', label: 'بررسی بیشتر' }, { value: 'reject', label: 'رد' }], group: 'نتیجه', col: 4 },
      { name: 'strengths', label: 'نقاط قوت', type: 'textarea', group: 'نتیجه' },
      { name: 'weaknesses', label: 'نقاط ضعف', type: 'textarea', group: 'نتیجه' },
      { name: 'notes', label: 'یادداشت مصاحبه‌گر', type: 'textarea', group: 'نتیجه' },
    ],
  },
  {
    key: 'interview-criteria', module: 'recruitment', table: 'interview_criteria', basePath: 'recruitment/criteria',
    title: 'معیارهای ارزیابی مصاحبه', titleSingular: 'معیار', icon: 'list',
    perm: { view: 'recruitment.view', create: 'recruitment.interview.manage', edit: 'recruitment.interview.manage', delete: 'recruitment.interview.manage' },
    search: ['title'], listColumns: [
      { field: 'title', label: 'معیار' }, { field: 'type', label: 'نوع' }, { field: 'weight', label: 'وزن' }, { field: 'max_score', label: 'حداکثر امتیاز' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان معیار', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: ['general', 'technical', 'behavioral', 'leadership'], group: 'مشخصات', col: 6 },
      { name: 'weight', label: 'وزن', type: 'number', group: 'امتیازدهی', col: 4 },
      { name: 'max_score', label: 'حداکثر امتیاز', type: 'number', group: 'امتیازدهی', col: 4 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'امتیازدهی', col: 4 },
      { name: 'description', label: 'توضیح معیار', type: 'textarea', group: 'تکمیلی' },
      statusField([{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }]),
    ],
  },
  {
    key: 'recruitment-stages', module: 'recruitment', table: 'recruitment_stages', basePath: 'recruitment/stages',
    title: 'مراحل استخدام', titleSingular: 'مرحله', icon: 'steps',
    perm: { view: 'recruitment.view', create: 'recruitment.stages.manage', edit: 'recruitment.stages.manage', delete: 'recruitment.stages.manage' },
    search: ['name'], orderBy: 'sort_order ASC',
    listColumns: [{ field: 'name', label: 'نام مرحله' }, { field: 'key', label: 'کلید (لاتین)' }, { field: 'color', label: 'رنگ' }, { field: 'sort_order', label: 'ترتیب' }, { field: 'is_final', label: 'پایانی', type: 'checkbox' }, { field: 'is_active', label: 'فعال', type: 'checkbox' }],
    fields: [
      { name: 'name', label: 'نام مرحله', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'key', label: 'کلید لاتین', type: 'text', group: 'مشخصات', col: 6, dir: 'ltr', help_text: 'مثال: screening — بدون فاصله و کاراکتر فارسی' },
      { name: 'color', label: 'رنگ', type: 'select', options: ['primary', 'success', 'warning', 'danger', 'info', 'muted'], group: 'نمایش', col: 4 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'نمایش', col: 4 },
      { name: 'is_final', label: 'مرحله پایانی', type: 'checkbox', checkLabel: 'پس از این مرحله فرآیند داوطلب خاتمه می‌یابد', group: 'نمایش', col: 4 },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'در کانبان نمایش داده شود', group: 'نمایش', col: 4 },
    ],
    beforeSave: (data, req, ctx) => {
      if ((ctx && ctx.isNew) && !data.key) {
        data.key = 'stage_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);
      }
      return data;
    },
  },

  /* ================================ بدو ورود ================================ */
  {
    key: 'onboarding-templates', module: 'onboarding', table: 'onboarding_templates', basePath: 'onboarding/templates',
    title: 'قالب‌های چک‌لیست بدو ورود', titleSingular: 'قالب', icon: 'check-square',
    perm: { view: 'onboarding.view', create: 'onboarding.templates.manage', edit: 'onboarding.templates.manage', delete: 'onboarding.templates.manage' },
    search: ['name', 'description'],
    listColumns: [{ field: 'name', label: 'نام قالب' }, { field: 'department_id', label: 'واحد' }, { field: 'is_default', label: 'پیش‌فرض', type: 'checkbox' }, { field: 'is_active', label: 'فعال', type: 'checkbox' }],
    fields: [
      { name: 'name', label: 'نام قالب', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'department_id', label: 'واحد سازمانی', type: 'lookup', source: deptSource, group: 'مشخصات', col: 6 },
      { name: 'job_title_id', label: 'عنوان شغلی', type: 'lookup', source: jobSource, group: 'مشخصات', col: 6 },
      { name: 'is_default', label: 'قالب پیش‌فرض', type: 'checkbox', checkLabel: 'برای کارکنان جدید به‌طور پیش‌فرض استفاده شود', group: 'مشخصات', col: 3 },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'فعال', group: 'مشخصات', col: 3 },
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'onboarding-tasks-def', module: 'onboarding', table: 'onboarding_tasks', basePath: 'onboarding/task-defs',
    title: 'کارهای قالب بدو ورود', titleSingular: 'کار', icon: 'list',
    perm: { view: 'onboarding.view', create: 'onboarding.templates.manage', edit: 'onboarding.templates.manage', delete: 'onboarding.templates.manage' },
    search: ['title'], orderBy: 'template_id ASC, sort_order ASC',
    listColumns: [{ field: 'template_id', label: 'قالب' }, { field: 'title', label: 'کار' }, { field: 'category', label: 'دسته' }, { field: 'owner_role', label: 'مسئول' }, { field: 'due_days', label: 'مهلت (روز)' }, { field: 'is_required', label: 'الزامی', type: 'checkbox' }],
    fields: [
      { name: 'template_id', label: 'قالب', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('onboarding_templates')} ORDER BY name`), group: 'مشخصات', col: 6 },
      { name: 'title', label: 'عنوان کار', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'category', label: 'دسته', type: 'select', options: ['document', 'it', 'hr', 'training', 'intro', 'finance', 'safety'], group: 'مشخصات', col: 4 },
      { name: 'owner_role', label: 'مسئول انجام', type: 'select', options: ['hr', 'manager', 'it', 'employee', 'finance', 'safety', 'training'], group: 'مشخصات', col: 4 },
      { name: 'due_days', label: 'مهلت (روز پس از استخدام)', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'is_required', label: 'الزامی', type: 'checkbox', checkLabel: 'تکمیل این کار الزامی است', group: 'مشخصات', col: 4 },
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'onboarding-kits', module: 'onboarding', table: 'onboarding_kit_items', basePath: 'onboarding/kits',
    title: 'اقلام تحویلی بدو ورود', titleSingular: 'قلم', icon: 'package',
    perm: { view: 'onboarding.view', create: 'onboarding.templates.manage', edit: 'onboarding.templates.manage', delete: 'onboarding.templates.manage' },
    search: ['title'],
    listColumns: [{ field: 'title', label: 'قلم' }, { field: 'type', label: 'نوع' }, { field: 'department_id', label: 'واحد' }, { field: 'quantity', label: 'تعداد' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'title', label: 'عنوان قلم', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: ['equipment', 'stationery', 'uniform', 'handbook', 'card', 'safety'], group: 'مشخصات', col: 6 },
      { name: 'department_id', label: 'واحد', type: 'lookup', source: deptSource, group: 'مشخصات', col: 4 },
      { name: 'quantity', label: 'تعداد', type: 'number', group: 'مشخصات', col: 4 },
      statusField([{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }]),
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },

  /* ================================= آموزش ================================= */
  {
    key: 'course-categories', module: 'training', table: 'course_categories', basePath: 'training/categories',
    title: 'دسته‌بندی دوره‌ها', titleSingular: 'دسته', icon: 'folder',
    perm: { view: 'training.view', create: 'training.create', edit: 'training.edit', delete: 'training.delete' },
    search: ['name'], orderBy: 'sort_order ASC',
    listColumns: [{ field: 'name', label: 'نام دسته' }, { field: 'sort_order', label: 'ترتیب' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'name', label: 'نام دسته', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'مشخصات', col: 6 },
      statusField([{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }]),
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'courses', module: 'training', table: 'courses', basePath: 'training/courses',
    title: 'دوره‌های آموزشی', titleSingular: 'دوره', icon: 'book',
    perm: { view: 'training.view', create: 'training.create', edit: 'training.edit', delete: 'training.delete', export: 'training.export' },
    search: ['title', 'code', 'provider'], orderBy: 'id DESC',
    listColumns: [
      { field: 'code', label: 'کد' }, { field: 'title', label: 'عنوان دوره' }, { field: 'category', label: 'دسته' },
      { field: 'type', label: 'نوع' }, { field: 'duration_hours', label: 'ساعت' },
      { field: 'is_mandatory', label: 'الزامی', type: 'checkbox' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'title', label: 'عنوان دوره', type: 'text', required: true, group: 'مشخصات', col: 8 },
      { name: 'code', label: 'کد دوره', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'category_id', label: 'دسته‌بندی', type: 'lookup', source: src(`SELECT id, name AS label FROM ${db.t('course_categories')} ORDER BY name`), group: 'مشخصات', col: 4 },
      { name: 'type', label: 'نوع دوره', type: 'select', options: [{ value: 'internal', label: 'داخلی (مدرس شرکت)' }, { value: 'external', label: 'خریداری‌شده / بیرونی' }, { value: 'online', label: 'آنلاین' }, { value: 'classroom', label: 'کلاس حضوری' }, { value: 'self_study', label: 'خودآموز' }], group: 'مشخصات', col: 4 },
      { name: 'provider', label: 'ارائه‌دهنده / مؤسسه', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'instructor_name', label: 'نام مدرس', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'duration_hours', label: 'مدت (ساعت)', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'level', label: 'سطح', type: 'select', options: ['مقدماتی', 'متوسط', 'پیشرفته'], group: 'مشخصات', col: 4 },
      { name: 'cost', label: 'هزینه دوره (هر نفر)', type: 'money', group: 'مالی', col: 4 },
      { name: 'capacity', label: 'ظرفیت', type: 'number', group: 'مالی', col: 4 },
      { name: 'pass_score', label: 'حد نمره قبولی', type: 'number', group: 'مالی', col: 4 },
      { name: 'is_mandatory', label: 'دوره الزامی', type: 'checkbox', checkLabel: 'برای همه کارکنان الزامی است', group: 'تنظیمات', col: 4 },
      { name: 'has_certificate', label: 'گواهی‌نامه دارد', type: 'checkbox', checkLabel: 'در پایان دوره گواهی صادر می‌شود', group: 'تنظیمات', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'draft', label: 'پیش‌نویس' }, { value: 'published', label: 'منتشر شده' }, { value: 'archived', label: 'بایگانی' }], group: 'تنظیمات', col: 4 },
      { name: 'description', label: 'شرح دوره', type: 'textarea', group: 'محتوا', rows: 4 },
      { name: 'objectives', label: 'اهداف یادگیری', type: 'textarea', group: 'محتوا', rows: 3 },
    ],
  },
  {
    key: 'course-lessons', module: 'training', table: 'course_lessons', basePath: 'training/lessons',
    title: 'جلسات و محتوای دوره', titleSingular: 'جلسه', icon: 'play',
    perm: { view: 'training.view', create: 'training.content.manage', edit: 'training.content.manage', delete: 'training.content.manage' },
    search: ['title'], orderBy: 'course_id ASC, sort_order ASC',
    listColumns: [{ field: 'course_id', label: 'دوره' }, { field: 'title', label: 'عنوان جلسه' }, { field: 'type', label: 'نوع' }, { field: 'duration_minutes', label: 'دقیقه' }, { field: 'is_active', label: 'فعال', type: 'checkbox' }],
    fields: [
      { name: 'course_id', label: 'دوره', type: 'lookup', required: true, source: courseSource, group: 'مشخصات', col: 6 },
      { name: 'title', label: 'عنوان جلسه', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع محتوا', type: 'select', options: [{ value: 'video', label: 'ویدیو' }, { value: 'text', label: 'متن آموزشی' }, { value: 'file', label: 'فایل ضمیمه' }, { value: 'link', label: 'لینک خارجی' }, { value: 'quiz', label: 'آزمون' }, { value: 'classroom', label: 'کلاس حضوری' }], group: 'مشخصات', col: 4 },
      { name: 'duration_minutes', label: 'مدت (دقیقه)', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'video_url', label: 'لینک ویدیو', type: 'text', group: 'محتوا', col: 6, dir: 'ltr' },
      { name: 'file', label: 'فایل ضمیمه', type: 'file', group: 'محتوا', col: 6 },
      { name: 'content', label: 'متن آموزشی', type: 'textarea', group: 'محتوا', rows: 6 },
      { name: 'is_preview', label: 'پیش‌نمایش رایگان', type: 'checkbox', checkLabel: 'قابل مشاهده پیش از ثبت‌نام', group: 'تنظیمات', col: 6 },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'فعال', group: 'تنظیمات', col: 6 },
    ],
  },
  {
    key: 'enrollments', module: 'training', table: 'enrollments', basePath: 'training/enrollments',
    title: 'ثبت‌نام دوره‌ها', titleSingular: 'ثبت‌نام', icon: 'check-square',
    perm: { view: 'training.view', create: 'training.assign', edit: 'training.edit', delete: 'training.delete' },
    search: [], orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['assigned', 'in_progress', 'completed', 'failed', 'expired'] }, { name: 'due_date', label: 'مهلت', type: 'date_range' }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'course_id', label: 'دوره' },
      { field: 'due_date', label: 'مهلت', type: 'date' }, { field: 'progress', label: 'پیشرفت (٪)', type: 'number' },
      { field: 'status', label: 'وضعیت', badge: true }, { field: 'score', label: 'نمره' },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'course_id', label: 'دوره', type: 'lookup', required: true, source: courseSource, group: 'مشخصات', col: 6 },
      { name: 'due_date', label: 'مهلت تکمیل', type: 'date', group: 'زمان‌بندی', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'assigned', label: 'تخصیص‌یافته' }, { value: 'in_progress', label: 'در حال یادگیری' }, { value: 'completed', label: 'تکمیل‌شده' }, { value: 'failed', label: 'قبول نشده' }, { value: 'expired', label: 'منقضی' }], group: 'وضعیت', col: 4 },
      { name: 'progress', label: 'درصد پیشرفت', type: 'number', group: 'وضعیت', col: 4 },
      { name: 'score', label: 'نمره', type: 'number', group: 'نتیجه', col: 4 },
      { name: 'completed_at', label: 'تاریخ تکمیل', type: 'date', group: 'نتیجه', col: 4 },
      { name: 'certificate_no', label: 'شماره گواهی', type: 'text', group: 'نتیجه', col: 4 },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'certificates', module: 'training', table: 'certificates', basePath: 'training/certificates',
    title: 'گواهی‌نامه‌های آموزشی', titleSingular: 'گواهی', icon: 'award',
    perm: { view: 'training.view', create: 'training.certificate.manage', edit: 'training.certificate.manage', delete: 'training.certificate.manage' },
    search: ['title', 'number'], orderBy: 'id DESC',
    listColumns: [{ field: 'employee_id', label: 'کارمند' }, { field: 'title', label: 'عنوان گواهی' }, { field: 'number', label: 'شماره' }, { field: 'issuer', label: 'صادرکننده' }, { field: 'issued_at', label: 'تاریخ صدور', type: 'date' }, { field: 'expires_at', label: 'انقضا', type: 'date' }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'title', label: 'عنوان گواهی', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'course_id', label: 'دوره', type: 'lookup', source: courseSource, group: 'مشخصات', col: 6 },
      { name: 'number', label: 'شماره گواهی', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'issuer', label: 'صادرکننده', type: 'text', group: 'اعتبار', col: 4 },
      { name: 'issued_at', label: 'تاریخ صدور', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'expires_at', label: 'تاریخ انقضا', type: 'date', group: 'اعتبار', col: 4 },
      { name: 'file', label: 'تصویر گواهی', type: 'file', group: 'فایل', col: 6 },
    ],
  },
  {
    key: 'training-requests', module: 'training', table: 'training_requests', basePath: 'training/requests',
    title: 'درخواست‌های آموزشی', titleSingular: 'درخواست', icon: 'send',
    perm: { view: 'training.view', create: 'training.request.create', edit: 'training.approve', delete: 'training.delete' },
    search: ['course_title', 'provider'], orderBy: 'id DESC',
    listColumns: [{ field: 'employee_id', label: 'کارمند' }, { field: 'course_title', label: 'دوره درخواستی' }, { field: 'provider', label: 'مؤسسه' }, { field: 'cost', label: 'هزینه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'درخواست', col: 6 },
      { name: 'course_title', label: 'عنوان دوره', type: 'text', required: true, group: 'درخواست', col: 6 },
      { name: 'provider', label: 'مؤسسه / ارائه‌دهنده', type: 'text', group: 'درخواست', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: ['internal', 'external', 'online', 'conference', 'certification'], group: 'درخواست', col: 6 },
      { name: 'cost', label: 'هزینه برآوردی', type: 'money', group: 'مالی', col: 4 },
      { name: 'start_date', label: 'از تاریخ', type: 'date', group: 'زمان', col: 4 },
      { name: 'end_date', label: 'تا تاریخ', type: 'date', group: 'زمان', col: 4 },
      { name: 'reason', label: 'دلیل درخواست', type: 'textarea', group: 'تکمیلی' },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار' }, { value: 'approved', label: 'تأییدشده' }, { value: 'rejected', label: 'رد شده' }, { value: 'done', label: 'برگزار شده' }], group: 'تصمیم', col: 4 },
      { name: 'decision_note', label: 'یادداشت تصمیم', type: 'textarea', group: 'تصمیم' },
    ],
  },

  /* ============================ حضور، مرخصی و مأموریت ============================ */
  {
    key: 'leave-types', module: 'attendance', table: 'leave_types', basePath: 'attendance/types',
    title: 'انواع مرخصی', titleSingular: 'نوع مرخصی', icon: 'calendar',
    perm: { view: 'attendance.view', create: 'attendance.types.manage', edit: 'attendance.types.manage', delete: 'attendance.types.manage' },
    search: ['name'], orderBy: 'sort_order ASC',
    listColumns: [{ field: 'name', label: 'عنوان' }, { field: 'is_paid', label: 'استحقاقی', type: 'checkbox' }, { field: 'max_days_year', label: 'سقف سالانه (روز)' }, { field: 'requires_approval', label: 'نیاز به تأیید', type: 'checkbox' }, { field: 'encashable', label: 'قابل تبدیل به نقد', type: 'checkbox' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'name', label: 'نام نوع مرخصی', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'lkey', label: 'کلید لاتین', type: 'text', group: 'مشخصات', col: 6, dir: 'ltr' },
      { name: 'color', label: 'رنگ', type: 'select', options: ['primary', 'success', 'warning', 'danger', 'info', 'muted'], group: 'نمایش', col: 4 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'نمایش', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'active', label: 'فعال' }, { value: 'inactive', label: 'غیرفعال' }], group: 'نمایش', col: 4 },
      { name: 'max_days_year', label: 'سقف سالانه (روز)', type: 'number', group: 'قواعد', col: 4 },
      { name: 'monthly_accrual', label: 'ذخیره ماهانه (روز)', type: 'number', group: 'قواعد', col: 4 },
      { name: 'is_paid', label: 'استحقاقی (با حقوق)', type: 'checkbox', checkLabel: 'در این مرخصی حقوق پرداخت می‌شود', group: 'قواعد', col: 3 },
      { name: 'requires_approval', label: 'نیاز به تأیید', type: 'checkbox', checkLabel: 'باید تأیید مدیر/منابع انسانی دریافت شود', group: 'قواعد', col: 3 },
      { name: 'requires_doc', label: 'نیاز به مدرک', type: 'checkbox', checkLabel: 'بارگذاری مدرک الزامی است', group: 'قواعد', col: 3 },
      { name: 'carry_forward', label: 'انتقال به سال بعد', type: 'checkbox', checkLabel: 'مانده قابل انتقال است', group: 'قواعد', col: 3 },
      { name: 'encashable', label: 'قابل تبدیل به نقد', type: 'checkbox', checkLabel: 'در تسویه قابل پرداخت است', group: 'قواعد', col: 3 },
      { name: 'hourly', label: 'ساعتی', type: 'checkbox', checkLabel: 'امکان ثبت ساعتی وجود دارد', group: 'قواعد', col: 3 },
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
    beforeSave: (data, req, ctx) => {
      if ((ctx && ctx.isNew) && !data.lkey) {
        data.lkey = 'leave_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);
      }
      return data;
    },
  },
  {
    key: 'leave-balances', module: 'attendance', table: 'leave_balances', basePath: 'attendance/balances',
    title: 'مانده مرخصی کارکنان', titleSingular: 'مانده مرخصی', icon: 'scale',
    perm: { view: 'attendance.view', create: 'attendance.balances.manage', edit: 'attendance.balances.manage', delete: 'attendance.balances.manage' },
    search: [], orderBy: 'employee_id ASC',
    sumFields: [{ field: 'entitled', alias: 'entitled_sum' }, { field: 'used', alias: 'used_sum' }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'leave_type_id', label: 'نوع مرخصی' }, { field: 'year', label: 'سال' },
      { field: 'entitled', label: 'استحقاق' }, { field: 'used', label: 'استفاده‌شده' }, { field: 'pending', label: 'در انتظار' }, { field: 'carried', label: 'انتقالی' },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'leave_type_id', label: 'نوع مرخصی', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('leave_types')} WHERE status='active' ORDER BY sort_order`), group: 'مشخصات', col: 6 },
      { name: 'year', label: 'سال', type: 'number', required: true, group: 'مشخصات', col: 4 },
      { name: 'entitled', label: 'استحقاق (روز)', type: 'number', group: 'مانده', col: 4 },
      { name: 'used', label: 'استفاده‌شده', type: 'number', group: 'مانده', col: 4 },
      { name: 'pending', label: 'در انتظار تأیید', type: 'number', group: 'مانده', col: 4 },
      { name: 'carried', label: 'انتقالی از سال قبل', type: 'number', group: 'مانده', col: 4 },
      { name: 'adjustment', label: 'اصلاح دستی', type: 'number', group: 'مانده', col: 4 },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'leave-requests', module: 'attendance', table: 'leave_requests', basePath: 'attendance/leaves',
    title: 'درخواست‌های مرخصی', titleSingular: 'درخواست مرخصی', icon: 'calendar',
    perm: { view: 'attendance.view', create: 'attendance.create', edit: 'attendance.approve', delete: 'attendance.edit' },
    search: ['reason'], orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['pending', 'approved', 'rejected', 'canceled'] }, { name: 'from_date', label: 'از تاریخ', type: 'date_range' }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'leave_type_id', label: 'نوع' },
      { field: 'from_date', label: 'از', type: 'date' }, { field: 'to_date', label: 'تا', type: 'date' },
      { field: 'days', label: 'روز' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'درخواست', col: 6 },
      { name: 'leave_type_id', label: 'نوع مرخصی', type: 'lookup', required: true, source: src(`SELECT id, name AS label FROM ${db.t('leave_types')} WHERE status='active' ORDER BY sort_order`), group: 'درخواست', col: 6 },
      { name: 'from_date', label: 'از تاریخ', type: 'date', required: true, group: 'بازه', col: 4 },
      { name: 'to_date', label: 'تا تاریخ', type: 'date', required: true, group: 'بازه', col: 4 },
      { name: 'days', label: 'تعداد روز', type: 'number', group: 'بازه', col: 4 },
      { name: 'is_hourly', label: 'ساعتی', type: 'checkbox', checkLabel: 'مرخصی ساعتی است', group: 'بازه', col: 4 },
      { name: 'hours', label: 'تعداد ساعت', type: 'number', group: 'بازه', col: 4 },
      { name: 'reason', label: 'علت درخواست', type: 'textarea', group: 'تکمیلی' },
      { name: 'address_during_leave', label: 'نشانی در طول مرخصی', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'contact_during_leave', label: 'شماره تماس', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار تأیید' }, { value: 'approved', label: 'تأییدشده' }, { value: 'rejected', label: 'رد شده' }, { value: 'canceled', label: 'لغو شده' }], group: 'تصمیم', col: 6 },
      { name: 'decision_note', label: 'یادداشت تصمیم', type: 'textarea', group: 'تصمیم' },
      { name: 'attachment', label: 'پیوست (مدرک)', type: 'file', group: 'تصمیم', col: 6 },
    ],
  },
  {
    key: 'attendance-records', module: 'attendance', table: 'attendance_records', basePath: 'attendance/records',
    title: 'کارکرد و حضور', titleSingular: 'رکورد کارکرد', icon: 'clock',
    perm: { view: 'attendance.view', create: 'attendance.create', edit: 'attendance.edit', delete: 'attendance.edit', export: 'attendance.report' },
    search: ['note'], orderBy: 'work_date DESC',
    filters: [{ name: 'work_date', label: 'تاریخ', type: 'date_range' }, { name: 'status', label: 'وضعیت', type: 'select', options: ['present', 'absent', 'leave', 'mission', 'holiday', 'remote'] }],
    importable: true,
    sumFields: [{ field: 'overtime_minutes', alias: 'ot_sum' }, { field: 'late_minutes', alias: 'late_sum' }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'work_date', label: 'تاریخ', type: 'date' },
      { field: 'check_in', label: 'ورود' }, { field: 'check_out', label: 'خروج' },
      { field: 'worked_minutes', label: 'کارکرد (دقیقه)' }, { field: 'overtime_minutes', label: 'اضافه‌کاری' },
      { field: 'late_minutes', label: 'تأخیر' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'کارکرد', col: 6 },
      { name: 'work_date', label: 'تاریخ', type: 'date', required: true, group: 'کارکرد', col: 3 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'present', label: 'حاضر' }, { value: 'absent', label: 'غایب' }, { value: 'leave', label: 'مرخصی' }, { value: 'mission', label: 'مأموریت' }, { value: 'holiday', label: 'تعطیل' }, { value: 'remote', label: 'دورکاری' }], group: 'کارکرد', col: 3 },
      { name: 'check_in', label: 'ساعت ورود', type: 'text', group: 'کارکرد', col: 3, dir: 'ltr', placeholder: '08:00' },
      { name: 'check_out', label: 'ساعت خروج', type: 'text', group: 'کارکرد', col: 3, dir: 'ltr', placeholder: '17:00' },
      { name: 'worked_minutes', label: 'کارکرد (دقیقه)', type: 'number', group: 'محاسبات', col: 3 },
      { name: 'overtime_minutes', label: 'اضافه‌کاری (دقیقه)', type: 'number', group: 'محاسبات', col: 3 },
      { name: 'late_minutes', label: 'تأخیر (دقیقه)', type: 'number', group: 'محاسبات', col: 3 },
      { name: 'early_leave_minutes', label: 'تعجیل خروج (دقیقه)', type: 'number', group: 'محاسبات', col: 3 },
      { name: 'source', label: 'منبع ثبت', type: 'select', options: ['manual', 'device', 'excel', 'mobile'], group: 'تکمیلی', col: 4 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'overtime-records', module: 'attendance', table: 'overtime_records', basePath: 'attendance/overtime',
    title: 'اضافه‌کاری و مأموریت', titleSingular: 'اضافه‌کاری', icon: 'timer',
    perm: { view: 'attendance.view', create: 'attendance.create', edit: 'attendance.approve', delete: 'attendance.edit' },
    search: ['reason'], orderBy: 'work_date DESC',
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'work_date', label: 'تاریخ', type: 'date' },
      { field: 'hours', label: 'ساعت' }, { field: 'type', label: 'نوع' }, { field: 'rate', label: 'ضریب' },
      { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'work_date', label: 'تاریخ', type: 'date', required: true, group: 'مشخصات', col: 3 },
      { name: 'hours', label: 'تعداد ساعت', type: 'number', required: true, group: 'مشخصات', col: 3 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'normal', label: 'روز عادی' }, { value: 'holiday', label: 'روز تعطیل' }, { value: 'night', label: 'شب‌کاری' }, { value: 'mission', label: 'مأموریت' }], group: 'مشخصات', col: 4 },
      { name: 'rate', label: 'ضریب', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'reason', label: 'علت / شرح', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار تأیید' }, { value: 'approved', label: 'تأییدشده' }, { value: 'rejected', label: 'رد شده' }, { value: 'paid', label: 'پرداخت‌شده' }], group: 'تصمیم', col: 6 },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تصمیم' },
    ],
  },
  {
    key: 'missions', module: 'attendance', table: 'missions', basePath: 'attendance/missions',
    title: 'مأموریت‌های کاری', titleSingular: 'مأموریت', icon: 'map',
    perm: { view: 'attendance.view', create: 'attendance.mission.manage', edit: 'attendance.mission.manage', delete: 'attendance.mission.manage' },
    search: ['title', 'destination'], orderBy: 'id DESC',
    listColumns: [{ field: 'employee_id', label: 'کارمند' }, { field: 'title', label: 'عنوان' }, { field: 'destination', label: 'مقصد' }, { field: 'from_date', label: 'از', type: 'date' }, { field: 'to_date', label: 'تا', type: 'date' }, { field: 'cost', label: 'هزینه', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مأموریت', col: 6 },
      { name: 'title', label: 'عنوان مأموریت', type: 'text', group: 'مأموریت', col: 6 },
      { name: 'destination', label: 'مقصد', type: 'text', group: 'مأموریت', col: 4 },
      { name: 'from_date', label: 'از تاریخ', type: 'date', group: 'مأموریت', col: 4 },
      { name: 'to_date', label: 'تا تاریخ', type: 'date', group: 'مأموریت', col: 4 },
      { name: 'days', label: 'تعداد روز', type: 'number', group: 'مأموریت', col: 4 },
      { name: 'transport_type', label: 'وسیله سفر', type: 'select', options: ['خودرو سازمانی', 'هواپیما', 'قطار', 'اتوبوس', 'خودرو شخصی'], group: 'هزینه', col: 4 },
      { name: 'cost', label: 'هزینه', type: 'money', group: 'هزینه', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار' }, { value: 'approved', label: 'تأییدشده' }, { value: 'rejected', label: 'رد شده' }, { value: 'done', label: 'انجام‌شده' }], group: 'تصمیم', col: 4 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تصمیم' },
    ],
  },
  {
    key: 'holidays', module: 'attendance', table: 'holidays', basePath: 'attendance/holidays',
    title: 'تعطیلات رسمی', titleSingular: 'تعطیل', icon: 'flag',
    perm: { view: 'attendance.view', create: 'attendance.types.manage', edit: 'attendance.types.manage', delete: 'attendance.types.manage' },
    search: ['title'], orderBy: 'gdate DESC',
    listColumns: [{ field: 'title', label: 'عنوان' }, { field: 'jdate', label: 'تاریخ شمسی' }, { field: 'gdate', label: 'تاریخ میلادی', type: 'date' }, { field: 'type', label: 'نوع' }, { field: 'is_paid', label: 'با حقوق', type: 'checkbox' }],
    fields: [
      { name: 'title', label: 'عنوان تعطیلی', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'gdate', label: 'تاریخ', type: 'date', group: 'مشخصات', col: 3 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'official', label: 'رسمی' }, { value: 'religious', label: 'مذهبی' }, { value: 'company', label: 'تعطیلی شرکت' }], group: 'مشخصات', col: 3 },
      { name: 'is_paid', label: 'با حقوق', type: 'checkbox', checkLabel: 'حقوق این روز پرداخت می‌شود', group: 'مشخصات', col: 4 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },

  /* ============================== حقوق و دستمزد ============================== */
  {
    key: 'payroll-components', module: 'payroll', table: 'payroll_components', basePath: 'payroll/components',
    title: 'مزایا و کسورات حقوق', titleSingular: 'قلم حقوق', icon: 'coins',
    perm: { view: 'payroll.view', create: 'payroll.components.manage', edit: 'payroll.components.manage', delete: 'payroll.components.manage' },
    search: ['name', 'ckey', 'description'], orderBy: 'sort_order ASC',
    listColumns: [
      { field: 'name', label: 'عنوان قلم' }, { field: 'type', label: 'نوع' }, { field: 'category', label: 'دسته' },
      { field: 'calc_type', label: 'روش محاسبه' }, { field: 'default_value', label: 'مقدار پیش‌فرض', type: 'money' },
      { field: 'taxable', label: 'مشمول مالیات', type: 'checkbox' }, { field: 'insurable', label: 'مشمول بیمه', type: 'checkbox' },
      { field: 'is_active', label: 'فعال', type: 'checkbox' },
    ],
    fields: [
      { name: 'name', label: 'عنوان قلم', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'ckey', label: 'کلید لاتین', type: 'text', group: 'مشخصات', col: 6, dir: 'ltr' },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'earning', label: 'مزایا (افزایش حقوق)' }, { value: 'deduction', label: 'کسورات (کاهش حقوق)' }], required: true, group: 'مشخصات', col: 4 },
      { name: 'category', label: 'دسته', type: 'select', options: ['base', 'allowance', 'overtime', 'bonus', 'insurance', 'tax', 'loan', 'deduction', 'other'], group: 'مشخصات', col: 4 },
      { name: 'calc_type', label: 'روش محاسبه', type: 'select', options: [{ value: 'fixed', label: 'مبلغ ثابت' }, { value: 'formula', label: 'فرمول' }, { value: 'percent', label: 'درصدی' }, { value: 'hours', label: 'ساعتی' }, { value: 'days', label: 'روزمزد' }, { value: 'manual', label: 'دستی (هر ماه)' }], group: 'محاسبه', col: 4 },
      { name: 'default_value', label: 'مقدار پیش‌فرض', type: 'money', group: 'محاسبه', col: 4 },
      { name: 'percent_of', label: 'مبنای درصد', type: 'text', group: 'محاسبه', col: 4, dir: 'ltr', help_text: 'مثال: base_salary' },
      { name: 'percentage', label: 'درصد', type: 'number', group: 'محاسبه', col: 4 },
      { name: 'formula', label: 'فرمول سفارشی', type: 'text', group: 'محاسبه', col: 8, dir: 'ltr' },
      { name: 'taxable', label: 'مشمول مالیات', type: 'checkbox', checkLabel: 'مشمول مالیات است', group: 'قواعد', col: 3 },
      { name: 'insurable', label: 'مشمول بیمه', type: 'checkbox', checkLabel: 'مشمول بیمه است', group: 'قواعد', col: 3 },
      { name: 'affects_net', label: 'در جمع خالص مؤثر', type: 'checkbox', checkLabel: 'در خالص پرداختی محاسبه شود', group: 'قواعد', col: 3 },
      { name: 'is_employer_cost', label: 'هزینه کارفرما', type: 'checkbox', checkLabel: 'فقط هزینه کارفرما — از حقوق کارمند کسر نمی‌شود', group: 'قواعد', col: 3 },
      { name: 'show_on_payslip', label: 'نمایش در فیش', type: 'checkbox', checkLabel: 'در فیش حقوقی چاپ شود', group: 'قواعد', col: 3 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'قواعد', col: 3 },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'در محاسبات استفاده شود', group: 'قواعد', col: 3 },
      { name: 'description', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
    beforeSave: (data, req, ctx) => {
      if ((ctx && ctx.isNew) && !data.ckey) {
        data.ckey = 'comp_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);
      }
      return data;
    },
  },
  {
    key: 'payroll-adjustments', module: 'payroll', table: 'payroll_adjustments', basePath: 'payroll/adjustments',
    title: 'موارد خاص فیش‌ها (اصلاحات)', titleSingular: 'اصلاح حقوق', icon: 'edit',
    perm: { view: 'payroll.view', create: 'payroll.adjustment.create', edit: 'payroll.edit', delete: 'payroll.edit' },
    search: ['title', 'reason'], orderBy: 'id DESC',
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'title', label: 'عنوان' }, { field: 'type', label: 'نوع' },
      { field: 'amount', label: 'مبلغ', type: 'money' }, { field: 'period_id', label: 'دوره' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    sumFields: [{ field: 'amount', alias: 'amount_sum' }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'title', label: 'عنوان قلم', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'component_id', label: 'قلم حقوق مرتبط', type: 'lookup', source: compSource, group: 'مشخصات', col: 6 },
      { name: 'period_id', label: 'دوره حقوق', type: 'lookup', source: periodSource, group: 'مشخصات', col: 6 },
      { name: 'type', label: 'نوع', type: 'select', options: [{ value: 'earning', label: 'مزایا' }, { value: 'deduction', label: 'کسورات' }], required: true, group: 'مبلغ', col: 4 },
      { name: 'amount', label: 'مبلغ', type: 'money', required: true, group: 'مبلغ', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار تأیید' }, { value: 'approved', label: 'تأییدشده' }, { value: 'applied', label: 'اعمال‌شده در فیش' }, { value: 'rejected', label: 'رد شده' }], group: 'مبلغ', col: 4 },
      { name: 'reason', label: 'علت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'loans', module: 'payroll', table: 'loans', basePath: 'payroll/loans',
    title: 'وام و مساعده', titleSingular: 'وام', icon: 'hand-coins',
    perm: { view: 'payroll.view', create: 'payroll.loan.manage', edit: 'payroll.loan.manage', delete: 'payroll.loan.manage' },
    search: ['title', 'code', 'reason'], orderBy: 'id DESC',
    listColumns: [
      { field: 'code', label: 'کد' }, { field: 'employee_id', label: 'کارمند' }, { field: 'title', label: 'عنوان' },
      { field: 'amount', label: 'مبلغ وام', type: 'money' }, { field: 'installments', label: 'تعداد قسط' },
      { field: 'installment_amount', label: 'مبلغ قسط', type: 'money' }, { field: 'paid_installments', label: 'اقساط پرداخت‌شده' },
      { field: 'remaining', label: 'مانده', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'title', label: 'عنوان وام/مساعده', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'code', label: 'کد', type: 'text', group: 'مشخصات', col: 4 },
      { name: 'amount', label: 'مبلغ کل', type: 'money', required: true, group: 'شرایط', col: 4 },
      { name: 'installments', label: 'تعداد اقساط', type: 'number', group: 'شرایط', col: 4 },
      { name: 'installment_amount', label: 'مبلغ هر قسط', type: 'money', group: 'شرایط', col: 4 },
      { name: 'remaining', label: 'مانده', type: 'money', group: 'شرایط', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار تأیید' }, { value: 'active', label: 'در حال بازپرداخت' }, { value: 'settled', label: 'تسویه‌شده' }, { value: 'rejected', label: 'رد شده' }, { value: 'canceled', label: 'لغو شده' }], group: 'وضعیت', col: 4 },
      { name: 'reason', label: 'علت درخواست', type: 'textarea', group: 'تکمیلی' },
      { name: 'guarantee', label: 'تضمین / ضامن', type: 'text', group: 'تکمیلی' },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'loan-installments', module: 'payroll', table: 'loan_installments', basePath: 'payroll/installments',
    title: 'اقساط وام', titleSingular: 'قسط', icon: 'list',
    perm: { view: 'payroll.view', create: 'payroll.loan.manage', edit: 'payroll.loan.manage', delete: 'payroll.loan.manage' },
    orderBy: 'loan_id ASC, no ASC',
    listColumns: [{ field: 'loan_id', label: 'وام' }, { field: 'no', label: 'شماره قسط' }, { field: 'amount', label: 'مبلغ', type: 'money' }, { field: 'period_id', label: 'دوره' }, { field: 'status', label: 'وضعیت', badge: true }, { field: 'deducted_at', label: 'تاریخ کسر', type: 'datetime' }],
    fields: [
      { name: 'loan_id', label: 'وام', type: 'lookup', required: true, source: src(`SELECT id, title AS label FROM ${db.t('loans')} ORDER BY id DESC`), group: 'مشخصات', col: 6 },
      { name: 'no', label: 'شماره قسط', type: 'number', group: 'مشخصات', col: 6 },
      { name: 'amount', label: 'مبلغ قسط', type: 'money', group: 'مشخصات', col: 6 },
      { name: 'period_id', label: 'دوره حقوق', type: 'lookup', source: periodSource, group: 'مشخصات', col: 6 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار' }, { value: 'deducted', label: 'کسر شده' }, { value: 'paid', label: 'پرداخت‌شده' }], group: 'وضعیت', col: 6 },
      { name: 'note', label: 'یادداشت', type: 'text', group: 'وضعیت', col: 6 },
    ],
  },
  {
    key: 'tax-brackets', module: 'payroll', table: 'tax_brackets', basePath: 'payroll/tax',
    title: 'پله‌های مالیات بر درآمد', titleSingular: 'پله مالیات', icon: 'percent',
    perm: { view: 'payroll.view', create: 'payroll.tax.manage', edit: 'payroll.tax.manage', delete: 'payroll.tax.manage' },
    orderBy: 'year DESC, sort_order ASC',
    listColumns: [{ field: 'year', label: 'سال' }, { field: 'title', label: 'عنوان' }, { field: 'from_amount', label: 'از مبلغ', type: 'money' }, { field: 'to_amount', label: 'تا مبلغ', type: 'money' }, { field: 'rate_percent', label: 'نرخ (٪)' }, { field: 'is_active', label: 'فعال', type: 'checkbox' }],
    fields: [
      { name: 'year', label: 'سال', type: 'number', required: true, group: 'مشخصات', col: 3 },
      { name: 'title', label: 'عنوان پله', type: 'text', group: 'مشخصات', col: 5 },
      { name: 'sort_order', label: 'ترتیب', type: 'number', group: 'مشخصات', col: 4 },
      { name: 'from_amount', label: 'از مبلغ (ریال)', type: 'money', group: 'مبالغ', col: 4 },
      { name: 'to_amount', label: 'تا مبلغ (ریال)', type: 'money', group: 'مبالغ', col: 4 },
      { name: 'rate_percent', label: 'نرخ مالیات (٪)', type: 'number', group: 'مبالغ', col: 4 },
      { name: 'exemption', label: 'مبلغ معافیت', type: 'money', group: 'مبالغ', col: 6 },
      { name: 'is_active', label: 'فعال', type: 'checkbox', checkLabel: 'در محاسبه مالیات استفاده شود', group: 'مبالغ', col: 6 },
    ],
  },
  {
    key: 'payroll-employee-settings', module: 'payroll', table: 'payroll_employee_settings', basePath: 'payroll/employee-items',
    title: 'اقلام اختصاصی هر کارمند', titleSingular: 'قلم اختصاصی', icon: 'user-cog',
    perm: { view: 'payroll.view', create: 'payroll.employee.manage', edit: 'payroll.employee.manage', delete: 'payroll.employee.manage' },
    orderBy: 'employee_id ASC',
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'component_id', label: 'قلم حقوق' },
      { field: 'value', label: 'مبلغ', type: 'money' }, { field: 'percent', label: 'درصد' },
      { field: 'effective_from', label: 'از تاریخ', type: 'date' }, { field: 'effective_to', label: 'تا تاریخ', type: 'date' },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'component_id', label: 'قلم حقوق', type: 'lookup', required: true, source: compSource, group: 'مشخصات', col: 6 },
      { name: 'value', label: 'مبلغ', type: 'money', group: 'مقدار', col: 6 },
      { name: 'percent', label: 'درصد', type: 'number', group: 'مقدار', col: 6 },
      { name: 'effective_from', label: 'از تاریخ', type: 'date', group: 'اعتبار', col: 6 },
      { name: 'effective_to', label: 'تا تاریخ', type: 'date', group: 'اعتبار', col: 6 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'تکمیلی' },
    ],
  },
  {
    key: 'salary-payments', module: 'payroll', table: 'salary_payments', basePath: 'payroll/payments',
    title: 'پرداخت‌های حقوق', titleSingular: 'پرداخت', icon: 'credit-card',
    perm: { view: 'payroll.view', create: 'payroll.pay', edit: 'payroll.pay', delete: 'payroll.edit' },
    orderBy: 'id DESC',
    sumFields: [{ field: 'amount', alias: 'amount_sum' }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'period_id', label: 'دوره' }, { field: 'amount', label: 'مبلغ', type: 'money' },
      { field: 'method', label: 'روش' }, { field: 'bank', label: 'بانک' }, { field: 'reference', label: 'شماره پیگیری' }, { field: 'paid_at', label: 'تاریخ پرداخت', type: 'datetime' },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'پرداخت', col: 6 },
      { name: 'period_id', label: 'دوره حقوق', type: 'lookup', source: periodSource, group: 'پرداخت', col: 6 },
      { name: 'amount', label: 'مبلغ', type: 'money', required: true, group: 'پرداخت', col: 6 },
      { name: 'method', label: 'روش پرداخت', type: 'select', options: [{ value: 'bank', label: 'واریز به حساب' }, { value: 'cash', label: 'نقدی' }, { value: 'cheque', label: 'چک' }], group: 'پرداخت', col: 6 },
      { name: 'bank', label: 'بانک', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'reference', label: 'شماره پیگیری', type: 'text', group: 'تکمیلی', col: 6 },
      { name: 'paid_at', label: 'تاریخ پرداخت', type: 'datetime', group: 'تکمیلی', col: 6 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار' }, { value: 'paid', label: 'پرداخت‌شده' }, { value: 'failed', label: 'ناموفق' }], group: 'تکمیلی', col: 6 },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'تکمیلی' },
    ],
  },

  /* ============================ تسویه و ترک کار ============================ */
  {
    key: 'offboarding-requests', module: 'offboarding', table: 'offboarding_requests', basePath: 'offboarding/requests',
    title: 'درخواست‌های ترک کار', titleSingular: 'درخواست ترک کار', icon: 'log-out',
    perm: { view: 'offboarding.view', create: 'offboarding.create', edit: 'offboarding.edit', delete: 'offboarding.edit' },
    search: ['reason', 'description'], orderBy: 'id DESC',
    filters: [{ name: 'status', label: 'وضعیت', type: 'select', options: ['pending', 'approved', 'rejected', 'in_progress', 'completed'] }, { name: 'last_working_day', label: 'آخرین روز کاری', type: 'date_range' }],
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'type', label: 'نوع' },
      { field: 'requested_at', label: 'تاریخ درخواست', type: 'date' }, { field: 'last_working_day', label: 'آخرین روز کاری', type: 'date' },
      { field: 'status', label: 'وضعیت', badge: true }, { field: 'settlement_status', label: 'تسویه', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'درخواست', col: 6 },
      { name: 'title', label: 'عنوان پرونده', type: 'text', group: 'درخواست', col: 6, hidden: false, help_text: 'در صورت خالی بودن، خودکار ساخته می‌شود' },
      { name: 'type', label: 'نوع خاتمه همکاری', type: 'select', options: [{ value: 'resignation', label: 'استعفا' }, { value: 'termination', label: 'خاتمه از سوی کارفرما' }, { value: 'retirement', label: 'بازنشستگی' }, { value: 'end_of_contract', label: 'پایان قرارداد' }, { value: 'mutual', label: 'توافق دوطرفه' }], required: true, group: 'درخواست', col: 6 },
      { name: 'requested_at', label: 'تاریخ درخواست', type: 'date', group: 'زمان', col: 4 },
      { name: 'last_working_day', label: 'آخرین روز کاری', type: 'date', group: 'زمان', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار بررسی' }, { value: 'approved', label: 'تأییدشده' }, { value: 'rejected', label: 'رد شده' }, { value: 'in_progress', label: 'در حال انجام تسویه' }, { value: 'completed', label: 'خاتمه‌یافته' }], group: 'زمان', col: 4 },
      { name: 'reason', label: 'علت', type: 'textarea', group: 'جزئیات' },
      { name: 'description', label: 'توضیحات تکمیلی', type: 'textarea', group: 'جزئیات' },
      { name: 'handover_to', label: 'تحویل به', type: 'lookup', source: empSource, group: 'تحویل کار', col: 6 },
      { name: 'handover_notes', label: 'شرح تحویل کارها', type: 'textarea', group: 'تحویل کار', col: 6 },
      { name: 'file', label: 'فایل استعفا/نامه', type: 'file', group: 'تحویل کار', col: 6 },
    ],
  },
  {
    key: 'clearances', module: 'offboarding', table: 'clearances', basePath: 'offboarding/clearances',
    title: 'تسویه بین واحدی', titleSingular: 'برگه تسویه', icon: 'check-circle',
    perm: { view: 'offboarding.view', create: 'offboarding.clearance.manage', edit: 'offboarding.clearance.manage', delete: 'offboarding.clearance.manage' },
    search: ['department', 'title'], orderBy: 'id DESC',
    listColumns: [{ field: 'offboarding_id', label: 'پرونده ترک کار' }, { field: 'department', label: 'واحد' }, { field: 'title', label: 'عنوان' }, { field: 'status', label: 'وضعیت', badge: true }, { field: 'cleared_at', label: 'تاریخ تسویه', type: 'datetime' }],
    fields: [
      { name: 'offboarding_id', label: 'پرونده ترک کار', type: 'lookup', required: true, source: src(`SELECT id, title AS label FROM ${db.t('offboarding_requests')} ORDER BY id DESC`), group: 'مشخصات', col: 6 },
      { name: 'department', label: 'واحد', type: 'text', required: true, group: 'مشخصات', col: 6 },
      { name: 'title', label: 'عنوان برگه', type: 'text', group: 'مشخصات', col: 6 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'pending', label: 'در انتظار' }, { value: 'cleared', label: 'تسویه‌شده' }, { value: 'has_liability', label: 'بدهی/تعهد دارد' }], group: 'وضعیت', col: 6 },
      { name: 'items', label: 'اقلام چک‌لیست (هر خط یک مورد)', type: 'textarea', group: 'چک‌لیست' },
      { name: 'note', label: 'یادداشت', type: 'textarea', group: 'چک‌لیست' },
    ],
  },
  {
    key: 'settlements', module: 'offboarding', table: 'settlements', basePath: 'offboarding/settlements',
    title: 'صورت‌حساب تسویه نهایی', titleSingular: 'تسویه نهایی', icon: 'receipt',
    perm: { view: 'offboarding.view', create: 'offboarding.settlement.manage', edit: 'offboarding.settlement.manage', delete: 'offboarding.settlement.manage' },
    orderBy: 'id DESC',
    listColumns: [
      { field: 'employee_id', label: 'کارمند' }, { field: 'net_payable', label: 'خالص پرداختی', type: 'money' },
      { field: 'severance_amount', label: 'سنوات/پایان کار', type: 'money' }, { field: 'leave_amount', label: 'بازخرید مرخصی', type: 'money' },
      { field: 'loan_balance', label: 'مانده وام', type: 'money' }, { field: 'status', label: 'وضعیت', badge: true },
    ],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'offboarding_id', label: 'پرونده ترک کار', type: 'number', group: 'مشخصات', col: 6 },
      { name: 'last_salary', label: 'حقوق آخرین ماه', type: 'money', group: 'مزایا', col: 4 },
      { name: 'leave_days', label: 'روزهای مرخصی استفاده‌نشده', type: 'number', group: 'مزایا', col: 4 },
      { name: 'leave_amount', label: 'بازخرید مرخصی', type: 'money', group: 'مزایا', col: 4 },
      { name: 'bonus_amount', label: 'پاداش و عیدی', type: 'money', group: 'مزایا', col: 4 },
      { name: 'notice_amount', label: 'حق ایام آگهی / مابه‌التفاوت', type: 'money', group: 'مزایا', col: 4 },
      { name: 'severance_amount', label: 'حق سنوات / پایان کار', type: 'money', group: 'مزایا', col: 4 },
      { name: 'other_earnings', label: 'سایر مزایا', type: 'money', group: 'مزایا', col: 4 },
      { name: 'debt_amount', label: 'بدهی کارمند', type: 'money', group: 'کسورات', col: 4 },
      { name: 'loan_balance', label: 'مانده وام', type: 'money', group: 'کسورات', col: 4 },
      { name: 'other_deductions', label: 'سایر کسورات', type: 'money', group: 'کسورات', col: 4 },
      { name: 'net_payable', label: 'خالص پرداختی', type: 'money', group: 'نتیجه', col: 4 },
      { name: 'status', label: 'وضعیت', type: 'select', options: [{ value: 'draft', label: 'پیش‌نویس' }, { value: 'approved', label: 'تأییدشده' }, { value: 'paid', label: 'پرداخت‌شده' }], group: 'نتیجه', col: 4 },
      { name: 'note', label: 'توضیحات', type: 'textarea', group: 'نتیجه' },
    ],
  },
  {
    key: 'exit-interviews', module: 'offboarding', table: 'exit_interviews', basePath: 'offboarding/exit-interviews',
    title: 'مصاحبه‌های پایانی', titleSingular: 'مصاحبه پایانی', icon: 'message-circle',
    perm: { view: 'offboarding.view', create: 'offboarding.exit_interview', edit: 'offboarding.exit_interview', delete: 'offboarding.exit_interview' },
    search: ['pros', 'cons', 'suggestions'], orderBy: 'id DESC',
    listColumns: [{ field: 'employee_id', label: 'کارمند' }, { field: 'interview_date', label: 'تاریخ', type: 'date' }, { field: 'reason_category', label: 'دلیل اصلی' }, { field: 'satisfaction', label: 'رضایت (۱ تا ۵)' }, { field: 'would_recommend', label: 'توصیه به دیگران', type: 'checkbox' }],
    fields: [
      { name: 'employee_id', label: 'کارمند', type: 'lookup', required: true, source: empSource, group: 'مشخصات', col: 6 },
      { name: 'interview_date', label: 'تاریخ مصاحبه', type: 'date', group: 'مشخصات', col: 3 },
      { name: 'satisfaction', label: 'میزان رضایت (۱ تا ۵)', type: 'number', group: 'مشخصات', col: 3 },
      { name: 'reason_category', label: 'دلیل اصلی خروج', type: 'select', options: ['حقوق و مزایا', 'شرایط کاری', 'محیط و فرهنگ', 'مدیریت', 'رشد شغلی', 'مهاجرت', 'مسائل شخصی', 'بازنشستگی', 'سایر'], group: 'تحلیل', col: 6 },
      { name: 'would_recommend', label: 'به دیگران توصیه می‌کند', type: 'checkbox', checkLabel: 'این شرکت را به دیگران توصیه می‌کند', group: 'تحلیل', col: 6 },
      { name: 'pros', label: 'نقاط قوت شرکت', type: 'textarea', group: 'نظر کارمند' },
      { name: 'cons', label: 'نقاط ضعف و مشکلات', type: 'textarea', group: 'نظر کارمند' },
      { name: 'suggestions', label: 'پیشنهادهای بهبود', type: 'textarea', group: 'نظر کارمند' },
      { name: 'notes', label: 'یادداشت منابع انسانی', type: 'textarea', group: 'یادداشت' },
    ],
  },
];
